### ISSUE TITLE
Humanize datetimes

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#101]
When we show datetimes, we should provide a more humanized version (e.g. "5 mins ago"). I think Django has built in filters for this.

e.g. compare
http://resourceprojects-etl.dev.cove.opendataservices.coop/360/dataload/ to http://resourceprojects-wireframe.dev.cove.opendataservices.coop/resourceprojects/dataload/

**Comment by caprenter** [comment]
Looks like this is the filter:
https://docs.djangoproject.com/en/1.8/ref/contrib/humanize/#naturaltime

**Comment by Bjwebb** [comment]
Yep, that's the one.

**Comment by Bjwebb** [comment]
Remaining tasks:
- [ ] Ensure the full datetime is displayed somewhere. (This may be about using an abbr tag to display it on hover).
- [ ] Add tests for conversion etc., once those are testable
