### ISSUE TITLE
Improve OCDS record oneOf validation message

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#1015]
From https://github.com/OpenDataServices/cove/issues/951

**Comment by jpmckinney** [comment]
Potential duplicate of #895

**Comment by robredpath** [comment]
Agreed @jpmckinney , closing.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data Review Tool: Correct reporting of giant blocks of JSON](https://trello.com/c/dXzzBjKM/48-data-review-tool-correct-reporting-of-giant-blocks-of-json)
