### ISSUE TITLE
Add guidance to additional fields box

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#1020]
Some recent feedback suggested users were unsure what to do with additional fields flagged by the validator, citing adding a `deliveryAddress` to the `tender` object as an example. We also see lots of examples of draft data with additional fields which could be provided using fields in the core schema.

We should add guidance to the additional fields box in the validator results to address this:

![image](https://user-images.githubusercontent.com/19265814/40288770-ec29dbbe-5d08-11e8-88a2-f3c2aa603346.png)

Proposed text (we can remove the "fields in data not in schema" from the box title if we add this):

> This data includes the following fields which are not part of the OCDS schema. You should check whether the data in these fields could be provided by using a field in the OCDS schema or by using an existing [extension](http://standard.open-contracting.org/latest/en/extensions/) to the schema.

I think that's sufficient and concise, but if we wanted to be more explanatory we could add

> Using existing fields is important for the interoperability of data from different publishers

And if we wanted to use stronger language we could add:

> OCDS publications which use additional fields where existing fields would suffice do not [conform with the standard](http://standard.open-contracting.org/latest/en/schema/conformance_and_extensions/#conformance-and-extensions)

**Comment by Tim0th1** [comment]
I agree with above. All three helped me understand more.

I wanted to understand better:
- What are 'additional fields' (just extension fields or any non-OCDS fields)?
- Do we normatively say in the docs that additional fields MAY or MAY NOT exist outside extensions?
- I may have misunderstood, but I think additional fields can legitimately exist outside of extensions - if that is true, is there an example and a rationale why this could ever be a good idea?

I think we could be clearer in the docs. I was not able to find a clear answer using SEARCH. The closest topic I found was:
http://standard.open-contracting.org/latest/en/extensions/developing/?highlight=additional%20fields

**Comment by duncandewhurst** [comment]
> * What are 'additional fields' (just extension fields or any non-OCDS fields)?

Any field published in an OCDS release which is not included in either:

1. the core OCDS schema; or
2. an extension which is declared in the `extensions` key in the release package metadata.

> * Do we normatively say in the docs that additional fields MAY or MAY NOT exist outside extensions?

In the [conformance section](http://standard.open-contracting.org/latest/en/schema/conformance_and_extensions/) of the docs we say:

> [A conforming implementation] may use terms from outside this specification’s terms where this specification’s terms are insufficient.

and

> The schema for the standard by default allows for new fields, and does not fail validation of a file which contains unknown fields.

But I think we could definitely be clearer on the permissibility of additional fields outside an extension (good point for updates to the documentation)

> * I may have misunderstood, but I think additional fields can legitimately exist outside of extensions - if that is true, is there an example and a rationale why this could ever be a good idea?

That's correct, whilst in general we recommend that additional fields are documented as extensions we allow them outside of extensions in order to avoid publishers discarding data which [doesn't map](https://www.open-contracting.org/2018/01/30/fields-dont-map-first/).

**Comment by Bjwebb** [comment]
@duncandewhurst How does this look? http://1020-addfields-guidance.dev.cove.opendataservices.coop/validator/data/797a6367-da8d-4f71-96cf-eb74e0349708

**Comment by duncandewhurst** [comment]
@Bjwebb looks good, I think we can also remove the "(fields in data not in schema)" from the title of the box now we have added the explanatory text

**Comment by Bjwebb** [comment]
Thanks, I've made that change.

This needs Spanish translations. @kindly Would you be able to look at that with @
BibianaC  next week?

**Comment by BibianaC** [comment]
@kindly let me know what needs to be translated.

**Comment by Bjwebb** [comment]
@BibianaC Easiest way is to do this through Transifex. Link is https://www.transifex.com/OpenDataServices/cove/viewstrings/#es/cove_ocds/145107636?q=translated%3Ano. You'll need to create an account and request access. This could be something we look at on Monday.

**Comment by Bjwebb** [comment]
This is now live on http://standard.open-contracting.org/validator/
