### ISSUE TITLE
Show dates in the interface in a human friendly format

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#1022]
Dates in the **Key Field Information** and **Release Table** sections of the validator results are currently shown in ISO8601 format:

![image](https://user-images.githubusercontent.com/19265814/40462985-a3e0553a-5f66-11e8-9a25-704015cf95ed.png)

Since I assume we're only displaying valid dates there anyway and in the spirit of using CoVE to explore data, it would be nice to show those in a human friendly format.

**Comment by robredpath** [comment]
+1 - I'd be happy for us to do this. It'll require a bit of thought on the design (how to show timezones, for example) but I think is pretty straightforward to do.

**Comment by andylolz** [comment]
> how to show timezones, for example

Maybe hide time and timezone info? Looks like a bunch of stuff in the standard is documented as a date, but is represented by a date-time internally. Perhaps the interface should reflect the way it’s documented, rather than the internal representation. Idk
