### ISSUE TITLE
OCDS for PPPs: Data validates with incorrect value in closed codelist

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#1027]
In the course updating the sample data in the PPP profile, I tested [this data](https://gist.github.com/duncandewhurst/0eed80a7218517d303530ffdc724852e) which has an incorrect value in `release/initiationType` (a closed codelist).

The [validator results](http://standard.open-contracting.org/validator/data/aa0809e9-0d34-4f86-bb02-7f9bb194977b) picked up on the codelist validation error but still gave the data a pass:

![image](https://user-images.githubusercontent.com/19265814/41513008-d99bd9de-72e8-11e8-9c31-f700d653491d.png)

At the time of writing the OCDS for PPPs Consolidated Extension doesn't modify the initiationType codelist, so `ppp` should be an incorrect value.

I tried reproducing the issue by submitting the sample data from the core standard with an incorrect value in `release/initiationType` but that behaved as expected and failed validation

```

**Comment by robredpath** [comment]
@Bjwebb can we close this now?

**Comment by Bjwebb** [comment]
Yes, I think this is fixed.
