### ISSUE TITLE
OCDS: Link to codelists does not display extended codelists

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/cove#1029]
For codelist validation errors, the codelist is presented as a link, which goes to http://datapipes.okfnlabs.org/csv/html/?url=https://raw.githubusercontent.com/open-contracting/standard/1.1/standard/schema/codelists/{codelist}.csv

![image](https://user-images.githubusercontent.com/342624/41614120-818785ec-73ef-11e8-86dc-27edf70ed6ca.png)

This doesn't take account of when codelists have been extended, potentially causing user confusion.

We should allow users to view the extended codelist through this link.

**Comment by rhiaro** [comment]
First pass:
- adds the link to an extension codelist (via datapipes) if it's a totally new one.
- *replaces* the link with the extension codelist if it overrides core (which the `initiationType` example does).
- adds `+` and `-` links to extensions which add or remove things from a core codelist, beside the link to the core.

![screenshot at 2018-07-11 10-50-39](https://user-images.githubusercontent.com/466229/42557931-70fcf33c-84f8-11e8-938c-63ab41902d45.png)

(Note: only tested this with the PPP extension so far).

This doesn't give us a complete view of the final codelist being validated against, so a couple of clicks and mental hops are required.

We could do this by generating a new CSV of the codelist that results after applying extensions, save that (temporarily I guess?) to disc and link to that through datapipes instead. So the question is: would that be worth the effort?

**Comment by timgdavies** [comment]
Thanks @rhiaro 

This is really good to see. If this implemented (rather than mocked up) right now, then I think worth deploying as a first step - as it certainly is an improvement on current set-up. We might need to include a line of text at the bottom when + and - are present, perhaps to say:

"Where you see + or - this indicates that the codelist has been modified with these additions (+) or subtractions (-) by the extension."

In terms of longer-term, ideally I would love to see data pipes replaced with something we display within CoVE (like some of the other pop-ups), and which shows the modified codelist.

For that I'm wondering if there is a useful link to be made with work @kindly may do on extensions explorer, which may (in future iterations, not MVP as far as I know) have a similar need for feature to:

* Display a modified codelist with extensions applied;
* Indicate *how* the codelist has been modified (i.e. highlight on rows where there have been additions, or list deletions)
