### ISSUE TITLE
Implement loading to staging/live virtuoso

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#104]

**Comment by Bjwebb** [comment]
Some of the remaining tasks:
- [ ] Move DBA_PASS from being a direct environment variable to using Django's settings framework
- [ ] Add the staging/live graphs to different graph groups

**Comment by Bjwebb** [comment]
I've looked into graph groups, and as far as I can tell this involves running SQL rather than SPARQL commands. There is no nice REST endpoint for SQL that I can see. Thus I think we have 3 options:
1) Get pyodbc working - not sure how much work this is, but my exprience so far suggests it won't be straightforward.
2) Do the cookie based auth to get at http://localhost:8890/conductor/isql_main.vspx over HTTP - this is inelegant and brittle
3) Call virtuoso's isql command using subprocess. This requires running Cove in an environment that has access to virtuoso's isql - e.g. by building it in a container inherited from the virtuoso one.
I'm investigating option (3) for now.

**Comment by timgdavies** [comment]
+1 to Option 3.
