### ISSUE TITLE
OCDS: Handle translated codelists

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1042]
Using the Spanish translation of the PPPs profile (http://standard.open-contracting.org/profiles/ppp/translated-consolidated-extension/es/extension.json) produces "Codelist Error, Could not find code field in codelist", because "Code" is translated to "Código" (OCDS' approach has been to translate CSV headers in codelist files [since 1.0.1](https://github.com/open-contracting/standard/blob/1__0__1/standard/schema/utils/translate_codelists.py#L23-L27)).

This hasn't been an issue before, because no extension to date has made a translation available.

To resolve this issue, either CoVE would have to support translated headers, or OCDS would have to change its approach to translating codelists.

**Comment by Bjwebb** [comment]
Here's where we look up the "Code" column - https://github.com/OpenDataServices/lib-cove/blob/master/libcove/lib/common.py#L343
We already support "Code" and "code" — one approach would be to just add "Código" to this list. (And the equivalent for "Title").

**Comment by robredpath** [comment]
@romifz @yolile what would the appropriate Spanish alternative(s) be for Title? Are there any alternatives for 'Código' that we need to be aware of (ie, for other localisations?)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle translated codelists](https://trello.com/c/utQpREoi/56-handle-translated-codelists)

**Comment by jpmckinney** [comment]
`Code` is always translated as `Código` for OCDS codelists. Other Spanish terms are not supported/valid. Title is `Título` (note diacritic).

Our other translations are:

* French: Code (same), Titre
* Italian: Codice, Titolo

**Comment by jpmckinney** [comment]
Updated link for code location: https://github.com/OpenDataServices/lib-cove/blob/b8640ef77a20f139d7a7673677402781162155e5/libcove/lib/common.py#L292

**Comment by jpmckinney** [comment]
Moved
