### ISSUE TITLE
Integrate OCDS Show with CoVE OCDS [1.2]

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/cove#1050]
I've done some test work in the [ocds-show branch](https://github.com/OpenDataServices/cove/tree/ocds-show) to explore how OCDS Show could be integrated into CoVE.

I think it should be plausible for us to:

* Embed OCDS show for any files under a given size;
* Provide guidance on how users can work with this to review the intelligibility of their data;

The main issues to address with this are likely to be:

* (1) Translation
* (2) The user experience that we want

However, I'm re-assured with 30 minutes of testing that this is (a) achievable and (b) potentially v. useful indeed.

**Comment by robredpath** [comment]
A couple more points to consider:
- What do we we about extensions and additional fields? We know that publishers often use extensions and additional fields to add data that's locally useful, but we don't currently support these in ocds-show. Could we add some sort of basic viz (almost just key-value pairs in a table?) to avoid giving the message that this data has been lost? 
- Do we support 1.0 and 1.1? How do we detect the difference? Does it matter?

**Comment by robredpath** [comment]
- Would be good to link to the OCDS show viz from the top of the page to remind people that it's there

**Comment by BibianaC** [comment]
@kindly is this deployed? can the issue be closed?

**Comment by jpmckinney** [comment]
I think this is closed.
