### ISSUE TITLE
IATI CoVE - check codes from embedded codelists

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#1051]
Re: https://github.com/devinit/D-Portal/issues/483 (this data was produced with CoVE)

We could / should pull in embedded codelist values from IATI, and provide checks on these

This would require a new section - as it is neither schema validation of rulesets

When a code value is not on the list, then we would report it

This is very important for embedded codes - transaction types, date types, etc

Adding Assignees for feedback

**Comment by Bjwebb** [comment]
This is something where [pyIATI](https://github.com/IATI/pyIATI) is meant to be able to help us. I don't know where their codelist validation support is up to though.

**Comment by stevieflow** [comment]
> This is something where pyIATI is meant to be able to help us. I don't know where their codelist validation support is up to though.

Does anyone know the status of pyIATI?  @andylolz might do...

**Comment by andylolz** [comment]
You’d need to ask @IATI. I’m waiting on an official announcement.

**Comment by dalepotter** [comment]
> This is something where [pyIATI](https://github.com/IATI/pyIATI) is meant to be able to help us. I don't know where their codelist validation support is up to though.

To add my (now unofficial!) twopennysworth on this, it was intended that pyIATI would allow access to IATI codelists, and access to other SSOT content at the version shipped with the library.  Validation to check for valid codelists is possible - example: https://github.com/iati/pyiati#validating-datasets

**Comment by kindly** [comment]
This is done
