### ISSUE TITLE
ImportError: No module named django.core.management

### ISSUE THREAD

**Issue by tobybatch** [OpenDataServices/cove#1053]
Taryn wants to use the toolchain and Cove is reporting this error processing files.

Environment:

```
root@4f96b91bd64a:/opt/cove# echo $LC_ALL 
C.UTF-8
root@4f96b91bd64a:/opt/cove# echo $DJANGO_SETTINGS_MODULE 
cove_iati.settings
```

To reproduce:
```

git clone git@github.com:NeonOpenAG/AG.git
cd AG
docker-compose up --build
```

In another terminal:

```
docker exec -ti openag_cove bash
/opt/cove/iati-cli -d -o /opt/cove/cove_iati/fixtures/example.xml
Traceback (most recent call last):
  File "/opt/cove/iati-cli", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
```

**Comment by kindly** [comment]
I assume you are talking about the `docker-compose branch?

Something must have changed in your setup as /opt/cove/iati-cli uses the default python version on the system, which in this case is python 2 and cove will not work with it (and django is only installed in python 3 anyhow)

`python3 /opt/cove/iati-cli` will work.

Normally we set up cove in a virtualenv so this is not a problem.

**Comment by tobybatch** [comment]
Thanks, that does it.
