### ISSUE TITLE
Merge question

### ISSUE THREAD

**Issue by siemvaessen** [OpenDataServices/cove#1055]
We are making use of 2 separate branches, Master for our case of IATI activity file transformation and branch 959-org-file for organisation file transformation. While we are OK with managing 2 separate branches for now, we are wondering when ODS expects them to be merged. I know/guess this will happen at some stage, just looking for some ETA on this - 2018, 2019?

@robredpath @rory09 (bcc @stevieflow  bcc-backup @Bjwebb )

**Comment by andylolz** [comment]
@siemvaessen: There’s a TODO list here: https://github.com/OpenDataServices/cove/pull/993#issuecomment-415443602

Someone who’s not Ben (or me) needs to review the code.

**Comment by stevieflow** [comment]
I've reviewed the spreadsheet end of things, and works well.  I've a couple of questions about integration with the current setup

Have asked @rory09 to take another look at that

Over to @robredpath & @kindly in terms of code review.

**Comment by andylolz** [comment]
> Over to @robredpath & @kindly in terms of code review.

Do you think you could assign them as reviewers on #993?

**Comment by andylolz** [comment]
Haha well I meant assign them on #993, but this is fine too I guess.

**Comment by andylolz** [comment]
@siemvaessen good news I think! This appears to have been added to [the current sprint](https://github.com/OpenDataServices/cove/projects/18) just yesterday. So by the end of the month, this may very well be merged!

**Comment by siemvaessen** [comment]
yes! Good news indeed.

**Comment by andylolz** [comment]
Great – this is merged! :raised_hands:

@robredpath any chance PWYF could be credited for the work I did on this? Looks like I’m [currently the only external contributor to CoVE](https://github.com/OpenDataServices/cove/graphs/contributors), and I see there’s no changelog. But it would be cool if an acknowledgement could be added somewhere for this work (plus the related work I did on flatten-tool). Let me know if that’s possible, thanks.

**Comment by robredpath** [comment]
@andylolz of course - how's https://github.com/OpenDataServices/cove/pull/1061 ?

**Comment by andylolz** [comment]
PERFECT. Thanks!

**Comment by andylolz** [comment]
I read the CLA and wrote the following to Steven on Wednesday:

> ah right – I see. Yeah, I didn’t do this work as part of my employment, so my employer doesn’t need to sign anything.
>
> If that means rewording the credits section to remove mention of PWYF then that’s fine, although I personally don’t think that’s necessary.

Looks like you’ve reworded the credits. That’s fine I guess.

**Comment by andylolz** [comment]
@robredpath CLA looks good as is :+1:

**Comment by andylolz** [comment]
@robredpath thanks for updating. #1061 looks good to me

**Comment by andylolz** [comment]
> Is that something that PWYF will want to do?

Probably difficult to say without a link to the CLA.

I fixed the link, but actually the PDF that contributoragreements dot org generates looks pretty borked. I reckon it would be better to generate your own PDF and stick that on github. Or just drop the CLA?

**Comment by andylolz** [comment]
> Is that something that PWYF will want to do?

Kk, I checked – probably not. So #1061 LGTM as it stands (at 8ba37a8).
