### ISSUE TITLE
Rename the tool to “Data Review Tool” [1.1] [OCDS]

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1062]
See if https://github.com/OpenDataServices/cove/commits/ocds-data-review-tool by TimD needs more work or can be merged (currently build fails).

**Comment by robredpath** [comment]
@jpmckinney do we need to change the URL as well?

**Comment by jpmckinney** [comment]
That would make sense. We can add a redirect.

**Comment by robredpath** [comment]
@odscjames ^^

**Comment by rhiaro** [comment]
I think this is good to go; I fixed the tests and updated the urls from `/validator/` to `/review/`.

**Comment by jpmckinney** [comment]
Can be closed?

**Comment by BibianaC** [comment]
@rhiaro was this reviewed and deployed? can the issue be closed?
