### ISSUE TITLE
360Giving Cove additional check doesnt cite missing Geographic Code Type code

### ISSUE THREAD

**Issue by mrshll1001** [OpenDataServices/cove#1070]
We think there might be some slight errors in additional checks for Cove on 360Giving.

**Expected Behaviour**
Cove additional check for recipient org location is triggered for relevant entries, and a message returning the relevant row and header of Recipient Org:Location

**Actual Behaviour**
Cove additional check indicates entire dataset does not have location information, and message returned indicated the rows but gave the header Recipient Org:Identifier. When downloading the data, Recipient Org:Location information is given appropriately.

First noted on [this data](https://dataquality.threesixtygiving.org/data/44350a93-225f-4cad-9a35-d069b1792e00), several additional checks are triggered but the same message around recipient:org identifer is given.

@stevieflow noted [this](https://github.com/OpenDataServices/cove/blob/master/cove_360/tests.py#L359) as potentially relevant.

**Comment by robredpath** [comment]
@mrshll1001 Thanks for this. The link in CoVE no longer works (we delete data after 7 days) - please can you upload the data to somewhere that we can access it (maybe Google Drive?)

**Comment by stevieflow** [comment]
It'll replicate with the latest big lottery data on the registry?

**Comment by kindly** [comment]
@mrshll1001 I looked at this when you first posted the data, but can not see the example now.  Could you share a spreadsheet that displays this information.

From memory the issue was that `RecipiantOrg:Location:Geographic Code Type` was not in the spreadsheet at all, so every row (or grant) marked that there was not any valid location information.  So I think the behaviour is expected.

Possibly the better warning for this issue would be that there is a `Geographic Code` without any valid `Geographic Code Type` associate and the error should point to the  `Geographic Code` where there is no type.

**Comment by stevieflow** [comment]
I'm using this file:

https://www.biglotteryfund.org.uk/-/media/Files/Research%20Documents/aOpenDataFiles/BLFOpenData18-19.xlsx

CoVE results

https://dataquality.threesixtygiving.org/data/9fb77148-1af9-449c-8c87-2e28541bc14e

The query is on this feedback:

![360giving data quality tool 1](https://user-images.githubusercontent.com/1209944/49028117-919bd780-f199-11e8-9401-b46851bdc92f.png)

In the spreadsheet there are four fields that pertain to recipient org location info, I think:

Recipient Org:Location:0:Geographic Code
Recipient Org:Location:0:Name
Recipient Org:Location:1:Geographic Code
Recipient Org:Location:1:Name

> From memory the issue was that RecipiantOrg:Location:Geographic Code Type was not in the spreadsheet at all, so every row (or grant) marked that there was not any valid location information. So I think the behaviour is expected.

Yes, that seems to be the case here.  @KDuerden - would you know of a file that contains ``Recipient Org:Location:0:Geographic Code Type`` so we can double check?

> Possibly the better (or additional) warning for this issue would be that there is a Geographic Code without any valid Geographic Code Type associated with it and the error should point to the Geographic Code where there is no type.

Sure - one for the CoVE sprint @mrshll1001 @robredpath .

**Comment by KDuerden** [comment]
@stevieflow Comic Relief [UK data](https://www.comicrelief.com/sites/default/files/downloads/360_Giving_UK.xlsx) does.
[BBC CiN](http://downloads.bbc.co.uk/tv/pudsey/360_giving_data_02102016.xlsx) and [City Bridge Trust](http://1vfva1igmeah9lhs11aj1e1d-wpengine.netdna-ssl.com/wp-content/uploads/2018/10/CBT-360-data-Sept-2013-to-Oct-2018.xlsx) but this is with Recipient Org:Location:Geographic Code Type without the 0!

**Comment by stevieflow** [comment]
Thanks @KDuerden - those datasets do *not* seem to trigger this check

Therefore, I think this is what we look at:

> Possibly the better (or additional) warning for this issue would be that there is a Geographic Code without any valid Geographic Code Type associated with it and the error should point to the Geographic Code where there is no type.

Agree?

**Comment by KDuerden** [comment]
@stevieflow Yes.

**Comment by stevieflow** [comment]
Thanks @KDuerden - I've created a ticket on our "non-sprint" board to look at this

**Comment by michaelwood** [comment]
@KDuerden my colleague @BibianaC is available to work on this, as it's more than a year could you confirm that this is something that is still needed? Thanks

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Additional Check - recipient geography / area code not present](https://trello.com/c/q1sUUcsD/15-additional-check-recipient-geography-area-code-not-present)

**Comment by robredpath** [comment]
We'll likely review geo messaging as part of the work on that, separately.
