### ISSUE TITLE
cove/templates/500.html has wrong extends tag?

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/cove#1089]
https://github.com/OpenDataServices/cove/blob/master/cove/templates/500.html#L1 Has  

    {% extends app_base_template %}

Should this not be

    {% extends request.current_app_base_template %}

That's what the other templates have.

That variable is set by middleware BTW - https://github.com/OpenDataServices/cove/blob/master/cove/middleware.py#L7

**Comment by kindly** [comment]
I think there is a chance the 500 error happens before the middleware is run.

So I think that the variable is set directly from config here:
https://github.com/OpenDataServices/cove/blob/master/cove/urls.py

**Comment by odscjames** [comment]
This is sorted now - thanks!
