### ISSUE TITLE
Add google docs urls as an input

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#109]
We can use the API to CSVs for each sheet: https://github.com/NRGI/resource-projects-etl/blob/master/process/google-docs-reader/transform-from-gdocs.py

We may want to add this as a general input option, as 360/OCDS cove may also benefit from it.

**Comment by timgdavies** [comment]
Agreed that this would be a useful general input option.

**Comment by Bjwebb** [comment]
Need to make sure we're re-using the same TagLifter object for all sheets in a spreadsheet - https://github.com/NRGI/resource-projects-etl/blob/master/process/google-docs-reader/transform-from-gdocs.py

**Comment by Bjwebb** [comment]
@timgdavies When running your code (in https://github.com/NRGI/resource-projects-etl/tree/v0.3/process/google-docs-reader) I get this error:

```
python transform-from-gdocs.py https://docs.google.com/spreadsheets/d/17FDwVbDCReeWxufE2Gab1yw1PqJpQIt6pASM92d7sl4/edit test.ttl
Traceback (most recent call last):
  File "transform-from-gdocs.py", line 20, in <module>
    sheetjson = json.loads(sheetlist.text)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 2 column 1 (char 1)
```

I think the problem might be that this sheet is somehow protected? Is there one you've been using to test this?

**Comment by timgdavies** [comment]
Try now. I believe the sheet must be Published to the web, as well as shared via the Share button...

**Comment by Bjwebb** [comment]
@timgdavies That works, thanks.

**Comment by Bjwebb** [comment]
I'm getting taglifter errors on that particular speradsheet, so I decided to create a simpler one as a test fixture - https://docs.google.com/spreadsheets/d/1lZBVe6TGfrPYtaP4bqP9OZ0WG26vh_jTzOOm1h2Qdc4/edit#gid=0

However, I'm getting the sign in issue, even though the sharing settings are the same as the other one (as far as I can see). @timgdavies Have I missed an option somewhere?

**Comment by timgdavies** [comment]
You need to choose 'File -> Publish to the Web' rather than/in addition to - setting the sharing settings. 

(We might want a nice error message that explains this if we can easily detect the sign-in error you are currently getting)

**Comment by Bjwebb** [comment]
Oh I see, getting confused by the publish to the web stuff in sharing settings.
