### ISSUE TITLE
CoVE OCDS - typo in the headlines box ("applies1" rather than "applies 1") 

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/cove#1092]
Reported by @duncandewhurst

**Comment by jpmckinney** [comment]
Add "Bitesize" label?

**Comment by robredpath** [comment]
Template is https://github.com/OpenDataServices/cove/blob/master/cove_ocds/templates/cove_ocds/explore_release.html#L64

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [typo in the headlines box ("applies1" rather than "applies 1")](https://trello.com/c/y20hPofj/31-typo-in-the-headlines-box-applies1-rather-than-applies-1)
