### ISSUE TITLE
360 Check Language

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/cove#1094]
Recently we put live a change that changed:

![screen shot 2018-12-04 at 12 32 06](https://user-images.githubusercontent.com/37832009/49442800-7e54c180-f7c2-11e8-89c4-b5d5724f8602.png)

To:

![screen shot 2018-12-04 at 12 33 06](https://user-images.githubusercontent.com/37832009/49442807-83197580-f7c2-11e8-9beb-c1b25ec8b0cf.png)

As noted in https://opendataservices.plan.io/issues/18067 , 360 want to double-check the language about how this is reported.

**Comment by BibianaC** [comment]
@KDuerden what would be the "explanatory text" you would like to add?

**Comment by KDuerden** [comment]
Thanks @BibianaC
Is this live in CoVE at the moment? I haven't been able to get this to trigger with test data with non-unique IDs, so I'm not exactly sure what situation/error this is describing. I'll have a go at drafting some text once I have a better idea what we need to explain to users.

**Comment by BibianaC** [comment]
@KDuerden I thought so. @odscjames is it live?

**Comment by Bjwebb** [comment]
Looks like this only appears for JSON files https://dataquality.threesixtygiving.org/data/ee0ef527-7a32-47aa-8e62-0ef653a7ea23
(Because the spreadsheet conversion has its own way of dealing with duplicate IDs).
