### ISSUE TITLE
Cannot access original JSON

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1095]
For example: http://standard.open-contracting.org/review/data/dc62b3db-a524-4a26-a43e-81b77b711dbc

I've received data from publishers through CoVE, but I can't download their data.

Can you give me an estimate on when this will be fixed? For OCDS work, this is a higher priority.

**Comment by kindly** [comment]
@jpmckinney This is an odd issue, and odd we have not spotted it before. It looks like if the file uploaded does not have any group read access than apache can not read the file.  The server does not appear to be changing the permissions of the local uploaded file.

I have temporarily added
```
FILE_UPLOAD_PERMISSIONS = 0o644
```
to the django config on the server and that seems to set the permissions actively, so fixes it.

Also, I have changed the permissions of all uploaded files currently on the server, so all existing downloads now work.

**Comment by jpmckinney** [comment]
Wonderful - thanks!
