### ISSUE TITLE
Log what users are doing with the application

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#11]
We should be able to generate a report that gives us some idea about:
- How many 'files' have been uploaded/pasted/fetched via URL (recently, in the last week, etc)
- What kind of conversions have people been requesting?

Other things we might want to think about:
Average size of files, time to process, number of subsequent downloads of converted files.

We can use this thread to add more ideas.

**Comment by caprenter** [comment]
Consider whether or not we want to also add piwik, and do anything about server logs

**Comment by Bjwebb** [comment]
I think the first step to doing this, and the main task for this iteration is to log datetime and upload method for all supplied data: https://github.com/OpenDataServices/cove/issues/23
This is saved in the database, and we can look at methods of aggregating this up later.

I think in this iteration we also want to add piwik to the deployed copy. Analysis on server logs is pending on me looking into logstash more.

**Comment by caprenter** [comment]
I'd also like to see the type of file that has been uploaded (i.e. are people only supplying JSON)

Currently when we hit the 'explore' page, file type is auto detected, and conversions happen each time, so logging that might not give us the information we want at that point.

**Comment by Bjwebb** [comment]
The trouble with type of file uploaded is that we don't necessarily know this until the explore page is loaded, which may also be loaded multiple times. This makes recording this information slightly more difficult, which is why I'd recommend not implementing that at this stage.

What I think is useful to do now is to have a brief page that gives us some idea of what stats we do have. I've taken a stab at this, and you can now see it in action at http://dev.cove.opendataservices.coop/360/stats

**Comment by caprenter** [comment]
This is good. I think we should review our requirements for this and generate new tickets. Does that sound ok?

**Comment by Bjwebb** [comment]
Yes, new more specific tickets sounds good.

**Comment by Bjwebb** [comment]
@caprenter Could you review this, in terms of what new tickets we need around this?

**Comment by Bjwebb** [comment]
@caprenter has written some thoughts in an internal etherpad https://opendataservices.titanpad.com/350

Task is for me to look through this, then probably discuss with @caprenter, and then we can turn tasks into public GitHub issues.

**Comment by Bjwebb** [comment]
I've made some additions to our Piwik analytics that I think might be useful.

Next step is for me to check once we have some data for these whether they help answer @caprenter's questions.

**Comment by Bjwebb** [comment]
Further tasks:
- [ ] Track validation fails
- [ ] Set up geoip properly

**Comment by jpmckinney** [comment]
Adding that it'd be useful to track anonymous metrics from submitted data: common errors, extensions usage, field coverage.

**Comment by robredpath** [comment]
We discussed this briefly in Montreal. Technically speaking, this is relatively straightforward, but I think we'll need to update our Ts&Cs to permit us to do it. It shouldn't be a difficult or controversial update, though.

**Comment by robredpath** [comment]
@jpmckinney do you think this might still be relevant? We looked at it before Kingfisher did anywhere near as much coverage and validation reporting as it does now, so my sense is that tracking this in the DRT is a poor proxy for the state of real data 'out there'.

**Comment by jpmckinney** [comment]
I agree – I think Kingfisher is the better approach for OCDS.

**Comment by jpmckinney** [comment]
From OCP's perspective, this issue can be closed / 'OCDS' tag can be removed.
