### ISSUE TITLE
OCDS: Indent JSON with two spaces instead of four

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1105]
The JSON file made available (e.g. after converting from an input spreadsheet) indents with 4 spaces, but all OCDS JSON files across all open-contracting repositories use 2 spaces.

**Comment by jpmckinney** [comment]
Add "Bitesize" label?

**Comment by robredpath** [comment]
This requires changes to flatten-tool. Issue opened.

**Comment by duncandewhurst** [comment]
+1 for this, as it currently makes round tripping example data for editing more difficult

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Indent JSON with two spaces instead of four](https://trello.com/c/DNJOJNXI/38-indent-json-with-two-spaces-instead-of-four)

**Comment by jpmckinney** [comment]
Deferring to OpenDataServices/flatten-tool#289. Should be very simple once that's done.
