### ISSUE TITLE
IATI: XML file line number missing from validation report

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#1106]
See https://github.com/OpenDataServices/iati-sample-data/blob/master/iati-activity-standard-BROKEN-missing-mandatory-elements.xml for test file

This file is invalid

When I test this through CoVE I get:

http://iati.cove.opendataservices.coop/data/f48eae66-52a4-47e3-a5f5-f02c19350b89

![cove-noline](https://user-images.githubusercontent.com/1209944/50557485-82023800-0cdd-11e9-9156-d7b2c0c76347.png)

What's missing here is the line number in the XML file (which is what I am testing) to help me understand exactkly where the issue lies

When I test the same file via the IATI validator, I get

http://validator.iatistandard.org/?perm=iati-activity-standard-BROKEN-missing-mandatory-elements_1546247927.xml

![iati-linenumber](https://user-images.githubusercontent.com/1209944/50557507-b118a980-0cdd-11e9-8632-d9392bcb8dbe.png)

PLease can we refer to the line number when testing XML files in CoVE?

**Comment by Bjwebb** [comment]
@stevieflow @kindly 

How does this look?

![screenshot from 2019-01-22 17-36-58](https://user-images.githubusercontent.com/634/51522306-69b0b380-1e6c-11e9-9812-04598288fd26.png)

Or, for a spreadsheet:

![screenshot from 2019-01-22 17-38-01](https://user-images.githubusercontent.com/634/51522355-82b96480-1e6c-11e9-984e-97eacfa12f04.png)

**Comment by stevieflow** [comment]
Great @Bjwebb (and hi!)

**Comment by Bjwebb** [comment]
Here's a dev deploy to test: http://1106-xml-line-number.dev.cove.opendataservices.coop/

**Comment by stevieflow** [comment]
Thanks @Bjwebb 

Q - does this also include the codelist checking @kindly added?  I edited an embedded codelist value on a sample file, but didnt get any feedback via ^^ deployment

**Comment by Bjwebb** [comment]
This includes those codelist checks now.

**Comment by stevieflow** [comment]
Can this be closed @Bjwebb ?
