### ISSUE TITLE
OCDS: Support for translations of extensions

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1108]
CoVE uses translations of the titles/descriptions in OCDS core schema and codelists, but to my knowledge it doesn't use translations of those for extensions. Until recently, there were no translations to use. Now, with extension_registry.py's [generate-data-file](https://ocdsextensionregistry.readthedocs.io/en/latest/cli.html#generate-data-file) command, and using the translations in [ocds-extensions-translations](https://github.com/open-contracting/ocds-extensions-translations), it's possible to get translated versions of extension files. So, it should be possible to display translations of titles/descriptions in extensions' schema and codelists.

I anticipate that this would require a build step, perhaps daily, to cache the translations, and it would only support the translation of extensions that are listed (and that have been translated) in the Extension Explorer. However, that's still an improvement.

I think this has been discussed a few times but not logged, so opening the issue.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support for translations of extensions](https://trello.com/c/B0D1jlGx/41-support-for-translations-of-extensions)

**Comment by jpmckinney** [comment]
Moved
