### ISSUE TITLE
OCDS: Deployment: Update robots.txt to allow indexing

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1112]
http://standard.open-contracting.org/robots.txt

For Googlebot, it allows `/validator`, not `/review`.

**Comment by jpmckinney** [comment]
Add "Bitesize" label?

**Comment by robredpath** [comment]
This is controlled in https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/ocds-docs/robots_live.txt

**Comment by jpmckinney** [comment]
I've closed it, now that I can commit to the relevant deploy repo.

**Comment by jpmckinney** [comment]
I guess someone needs to deploy the change?

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OCDS: Deployment: Update robots.txt to allow indexing](https://trello.com/c/hevX32rF/69-ocds-deployment-update-robotstxt-to-allow-indexing)

**Comment by odscjames** [comment]
Deployed
