### ISSUE TITLE
OCDS: Report empty or blank fields, objects and arrays

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#1114]
Publishers commonly include empty or blank fields, objects and arrays in their OCDS data, e.g.

```json
{
"example1": "",
"example2": {},
"example3": []
}
```
The [OCDS documentation](http://standard.open-contracting.org/latest/en/schema/reference/?highlight=empty#empty-fields) states:

> Fields that are not being used, or that have no value, can be excluded in their entirety (key and value) from a published file.
>
> Only including fields which have values will keep versioned datasets cleaner.

This is a common feedback point from the helpdesk, so we should add it as a check in CoVE.

**Comment by jpmckinney** [comment]
On today's call, this was mentioned as a candidate for the Apr-May 2019 sprint.
