### ISSUE TITLE
[1.2] Group validation errors by type

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1117]
- We already have identifiers for each kind of check
- The work here is to categorise them and present them together
- Risk is that ungrouped errors disappear

**Comment by robredpath** [comment]
https://docs.google.com/document/d/1Jy0kbX7OhP5aY_j67VgTJe9mYcn8iuP3I6ahetfz9OE/edit#bookmark=id.pridbg17tk0 is @mrshll1001 's prototype for this

**Comment by Bjwebb** [comment]
> We already have identifiers for each kind of check

I think I said this. I'm referring to `e.validator` and `e.validator_value`which we have for each error `e` from jsonschema. e.g. for missing fields, `e.validator` is `required`, so we can match for that.

The validation grouping prototype looks good to me.

**Comment by Bjwebb** [comment]
I've split validation errors into 3 groups. Check out the [demo dev deploy](http://1117-group-validation.cove-360-dev.default.threesixtygiving.uk0.bigv.io/?source_url=https://github.com/OpenDataServices/cove/raw/master/cove_360/fixtures/badfile_all_validation_errors.xlsx).

Currently modals are broken. How best to fix that depends on how much more we're changing the tables. The prototype docs only has two columns - is that what we want, or is it just shorthand for the larger table?
