### ISSUE TITLE
[1.2] Add the ability to have one-from-many additional checks showing their results

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1118]
eg multiple messages depending on how many of your fundingOrgs have external org IDs

**Comment by robredpath** [comment]
To follow up on our conversation earlier, @BibianaC - the issue that we're trying to address here is that we want to be able to provide more nuanced feedback in the new additional checks sections. 

So, for example, in the check about use of externally referencable org-IDs, we want to be able to say "oh no! less than 30% of your grants use good org-ids, here's some help" OR "30-70% of your grants use decent org IDs - well done, here's some advice on how to make them better" OR ">70% of your grants use decent org IDs, very well done! Your data is already pretty useful. Here's some advice on how to get the final few" OR "100% of your grants use good org-ids, you're a superstar, your data can be used in all these cool ways".

**Comment by KDuerden** [comment]
@robredpath @BibianaC 
the caveat here is 100% is only possible for certain kinds of funders. 50% external org IDs could be excellent for a community foundation that funds small and often unregistered groups. 
So when it comes to the language (and any visual cues) 30% may be framed as 'more is better if possible' rather than a negative.

**Comment by robredpath** [comment]
Thanks @KDuerden - the task here is first of all about putting in place the mechanism to then allow the switching behaviour; but it's helpful to think about the words as well. 

Do you have a sense of how many choices we'll want to present? Would 3 be ok - a negative one, a 'could be better' one, and a 'very good' one? Or, do we want to keep our options open? I'm certainly not thinking of traffic lights or anything like that, after all!

**Comment by KDuerden** [comment]
@robredpath for org IDs I was thinking only 2
x% have external org IDs
0 have external org IDs
I roughed out text/thinking for this in CoVE feedback doc
