### ISSUE TITLE
Errors in large files result in lots of JSON shown to user

### ISSUE THREAD

**Issue by pindec** [OpenDataServices/cove#1121]
The Data Review Tool running on [this large OCDS JSON record package](http://ocds.mepps.openprocurement.io/api/records.json) quotes multiple very large sections of json as an error where it "is not valid under any of the given schemas".  

It makes a very large (size & page weight-wise) webpage that is not very user-friendly (~50MB).

([URL](http://standard.open-contracting.org/review/data/7a95f20a-38a7-497c-a26f-9eca14ce3a27) in case it hasn't expired yet)

Screenshot: 
![screenshot](https://user-images.githubusercontent.com/1897475/52774829-18907b80-3036-11e9-8e31-e1e04480303b.png)

To cross-ref in new process kingfisher: collection id = 12

**Comment by pindec** [comment]
Validation error is of type "oneOf", examples in ocdskingfisherprocess:
* collection_id = 12
* record_check ids = 12486 or 20586

**Comment by robredpath** [comment]
@bjwebb has done some work recently to improve oneOf handling in BODS CoVE - that could be ported to OCDS CoVE in the next sprint :)

**Comment by jpmckinney** [comment]
Related: #895

**Comment by robredpath** [comment]
This is basically the same issue as #895. The issues are now linked, so closing this one. This is a candidate for the next sprint.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data Review Tool: Correct reporting of giant blocks of JSON](https://trello.com/c/dXzzBjKM/48-data-review-tool-correct-reporting-of-giant-blocks-of-json)
