### ISSUE TITLE
[1.2] Add the ability to provide richer feedback in additional checks

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1122]
This is two things:
- Make it so that at least things like bolding, preformatted text and colour work
- (ideally) make it so that we can write copy of the form "x% of your grants have characteristic y" instead of just "x of your grants...."

**Comment by robredpath** [comment]
So, for example, instead of:

**15 grants have a value provided in the Recipient Org: Company Number column that doesn’t look like a company number**
Common causes of this are missing leading digits, typos or incorrect values being entered into this field. 

I'd like to be able to:

**25% of your grants have a value provided in the `Recipient Org: Company Number` column that doesn’t look like a company number**

Common causes of this are missing leading digits, typos or incorrect values being entered into this field. Company numbers are typically 8 digits, possibly starting SC, for example `SC01234569` or `09876543`. You can check company numbers online at [Companies House](https://beta.companieshouse.gov.uk/)

**Comment by robredpath** [comment]
@KDuerden is there any other richness you'd want in Additional Checks stuff?

**Comment by KDuerden** [comment]
@robredpath Thanks - the options you set out above sound good. 
eg bold, colour, hyperlinks and preformatting
