### ISSUE TITLE
Work out what we want to say in "Data Summary" 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1126]
Data Summary is where we have an opportunity to give a sense of the shape of the data to the person who just uploaded a file - either pre-publication or ahead of using it for some purpose. 

For the pre-publication use case, we already provide some helpful information. @KDuerden has suggested some further possibilities in https://docs.google.com/document/d/1EAE1ceK2GzbegbkDBEkQM-vK_tSTBxeckoz7b2zah1E/edit#bookmark=id.qey7ij7om6ph , relating to Funder data that's likely to be the same across lots of rows. This could be modelled as an additional check under-the-hood. 

For the 'ahead of using it' use case, we might want to give some more thought to what we want to say. However, this isn't a priority for now.

**Comment by mrshll1001** [comment]
I think we did this?
