### ISSUE TITLE
Conversion takes too long for a single request

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#113]
This also currently blocks any other requests.

This is likely to be fixed with some combination of:
* Using multi-workers for Gunicorn
* Running some sort of task runner like celery, so that the conversion doesn't happen in the request.
* Profiling taglifter to try to improve the speed

**Comment by timgdavies** [comment]
I would strongly encourage us to look at a task running approach / queue for asynchronous conversion. 

This might need us to introduce a 'task running' status to the dashboard.

I strongly suspect that even with optimisation, we will have cases of files needing to go through CoVE which cannot be processed in a reasonable response time on a web page.

**Comment by Bjwebb** [comment]
Priority for this is to have it "quick enough" in the short term.

**Comment by Bjwebb** [comment]
Gunicorn now has mulitple async workers, so although the experience when clicking th convert tab remains the same, it's now possible to navigate the rest of the site at the same time.

**Comment by robredpath** [comment]
Closing due to #399 - this functionality will be removed in a future iteration
