### ISSUE TITLE
[1.3] Write some new validation errors and additional checks to use new architecture

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1130]

**Comment by Bjwebb** [comment]
I've been doing some work on this for BODS, which isn't yet merged.

Here's a dev deploy to take a look at the updated messages: http://cove-bods-16-reword-validation.cove-360-dev.default.threesixtygiving.uk0.bigv.io/?source_url=https://github.com/OpenDataServices/cove/raw/master/cove_360/fixtures/badfile_all_validation_errors.xlsx
Here's the same file on the live deploy: https://dataquality.threesixtygiving.org/?source_url=https://github.com/OpenDataServices/cove/raw/master/cove_360/fixtures/badfile_all_validation_errors.xlsx

**Comment by KDuerden** [comment]
I mentioned this to @robredpath yesterday. 
Is there scope for only one version of "First three location" to appear depending on whether CoVE originally received spreadsheet or json file?
Both types of location could still appear in the full list, for completeness sake.

**Comment by robredpath** [comment]
@KDuerden I think that's implicit in #1131 , but we should check with @Bjwebb that it is, and it's doable.

**Comment by robredpath** [comment]
We've got a lot of the infrastructure in place now, so we've got a lot of a better idea of what the structure for words looks like. @BibianaC is going to have a chat with me and @mrshll1001 tomorrow to work out some more details. But, I think a good plan from here is:
- We put together a spreadsheet with current and new validation errors, proposing new text there
- We port all of the current additional checks to the new format, update https://dataquality.threesixtygiving.org/additional_checks with percentages, and add a tab to https://docs.google.com/spreadsheets/d/1NFjM0-6LqlSbI3dWXffZiad15VEI9gz4NJnraKk8CeU/edit?ts=5c6d12d0#gid=0 to supersede the current "feedback messages" tab. Then, we propose new text and percentages there based on @mrshll1001 and @KDuerden 's work so far. 
- Once we're happy with a first version of the new text, we apply it to the code and deploy 

How does that sound?

**Comment by Bjwebb** [comment]
@KDuerden 

> Is there scope for only one version of "First three location" to appear depending on whether CoVE originally received spreadsheet or json file?

Yes, in fact for spreadsheets I've merged this column into First 3 Examples too - https://github.com/OpenDataServices/cove/issues/1131#issuecomment-470416370

> Both types of location could still appear in the full list, for completeness sake.

Yes, this is also the behaviour at the above link.

**Comment by BibianaC** [comment]
@mrshll1001 was this not done?
