### ISSUE TITLE
Duplicate column headers lead to incorrect cell source map

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#1135]
![screenshot from 2019-03-06 14-35-21](https://user-images.githubusercontent.com/634/53858347-29248800-401d-11e9-9e3d-37eeee78d018.png)
[badfile_all_validation_errors_4_times.xlsx](https://github.com/OpenDataServices/cove/files/2934586/badfile_all_validation_errors_4_times.xlsx)

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicate column headers lead to incorrect cell source map](https://trello.com/c/UQwEhvQ4/114-duplicate-column-headers-lead-to-incorrect-cell-source-map)
