### ISSUE TITLE
UI for files with many releases

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#114]
I uploaded a file with 8000+  releases in it.  

At this level, the results page suffers slightly - in terms of:

-  the long list of identifiers is in the middle results panel is difficult to scroll to the end of
- the table below, is equally difficult

It could be an initial idea to tab the two types of results?

**Comment by Bjwebb** [comment]
We now have a paginated table, and hidden pops for lists of IDs.

@stevieflow Do you think this issue can now be closed?

**Comment by stevieflow** [comment]
Yes
