### ISSUE TITLE
JSON is loaded every time the page is loaded

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#115]
This means page load takes a long time for large files, like some of the recent OCDS data.

**Comment by timgdavies** [comment]
If we looked at the output being written as cached file to disk that might
be useful for future CoVE batch processing?

Alternatives to consider are a generic Web cache in front of CoVE although
this would still lead to slow loads whenever cache expired even if
underlying data is unchanged.

In future we may find that for some large files we also want to be loading
them into a datastore (eg elasticsearch) in ways that would allow an
explore page to produce dynamic reports about the data. Not sure this is
directly relevant here, but related.

**Comment by Bjwebb** [comment]
I think we may want to look at this in terms of storing the intermediate data  (e.g. dicts of aggregates) that are used to render the page - ie. by serialising and storing the data, or by creating and populating appropriate Django models. This would have the advantage of allowing us to do fast comparison/summary across multiple files.

**Comment by Bjwebb** [comment]
We're now caching various data for the page in flat files, and subsequent page loads are much faster now. Closing, and we can open a new issue if things get slow again.
