### ISSUE TITLE
Save or Share these results

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#116]
When you get the results page - there is a "Save or Share these results" paragraph

> Save or Share these results

> These results will be available for 7 days from the day the data was first uploaded. You can revisit these results until then.

> After 7 days all uploaded data is deleted from our servers, and the results will no longer be available. Anyone using the link to this page after that will be show a message that tells them the file has been removed.

Could it be possible to also include the actual URL to the results within this block?  This might not be clear to some users

**Comment by stevieflow** [comment]
linked to https://github.com/OpenDataServices/cove/issues/39, potentially

**Comment by Bjwebb** [comment]
This has now been done as part of https://github.com/OpenDataServices/cove/issues/39 and if deployed on the dev site.
