### ISSUE TITLE
OCDS: Flatten package metadata to Meta tab

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#1160]
Currently when flattening an OCDS release package the package metadata is lost.

This makes round tripping data between JSON and flat files difficult, because the package metadata has to be added back in manually.

This came up when I wanted to convert the OCDS for PPPs sample data to a spreadsheet to make some edits.

Can we use the package metadata in a JSON file to generate a Meta tab in the spreadsheet?

**Comment by jpmckinney** [comment]
Duplicate #683

**Comment by Bjwebb** [comment]
Closing in favour of this flatten-tool issue: https://github.com/OpenDataServices/flatten-tool/issues/176
