### ISSUE TITLE
OCDS - accessing a validation report

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#117]
This sample is reported as *not* being valid against the schema:

http://cove.opendataservices.coop/ocds/data/88094903-d148-4fdc-8f89-242d1011eb6f

How, as a user, can I find out what the specific validation issues are?

**Comment by Bjwebb** [comment]
Cove doesn't have specific validation output yet, the issue is https://github.com/OpenDataServices/cove/issues/46 . There is a basic OCDS validator at http://ocds.open-contracting.org/validator/validate/ which does have specific output, so you may find that useful.

**Comment by stevieflow** [comment]
*nods*

Shall I close this, as a duplicate of #46 therefore?

**Comment by Bjwebb** [comment]
Yep, I will.
