### ISSUE TITLE
OCDS: Is there a suite of valid/invalid files for testing the validator?

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1180]
I am thinking we can copy these files into a test suite, so that other implementations of validators (like jOCDS validator) can check (and demonstrate) that their implementation meets the validator specification. Right now, we have no way of robustly testing such validators, so users might, reasonably, be uncertain about whether they are properly implemented.

I think I remember seeing an invalid OCDS file that was intended to have as many faults as possible, for example. If you can point me to the files, I can start on the test suite.

Related: https://github.com/open-contracting/standard/issues/587

**Comment by jpmckinney** [comment]
cc @patxiworks, following up on our discussion.

**Comment by robredpath** [comment]
All the files that we use for the automated tests are in https://github.com/OpenDataServices/cove/tree/master/cove_ocds/fixtures 

In particular, badfile_all_validation_errors_results.json and badfile_all_validation_errors.json are useful for testing validators, as they cover all the JSON Schema features that we know OCDS uses, and none that it doesn't. As a result, we know that our tool responds to every error it's going to encounter, and we haven't had to worry about any that we won't. 

The rest of the files have evolved quite organically alongside the test suite for CoVE. A single central repository of known-bad data would be very helpful. Let us know if you'd like our input on that!

**Comment by jpmckinney** [comment]
This is in my backlog – will update issue when I have time to look at this again.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix incorrect spreadsheet validation errors when using hashcomments](https://trello.com/c/AkNYenvb/6-fix-incorrect-spreadsheet-validation-errors-when-using-hashcomments)

**Comment by jpmckinney** [comment]
I'll defer to open-contracting/standard#587 regarding whether to pursue this further.
