### ISSUE TITLE
OCDS: incorrect spreadsheet validation errors when using hashcomments

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#1186]
Validating spreadsheet data which uses `hashcomments` to comment out columns results in incorrect error messages.

For example, [this spreadsheet](https://docs.google.com/spreadsheets/d/1huNiQuBd-qmnwgdaZU0xNo2b1gJy_Pbmi-qLZKoDdhU/edit#gid=1361145596) has two errors:

![image](https://user-images.githubusercontent.com/19265814/59864054-e5f8e580-937d-11e9-8cfa-9ac56e44f922.png)

1. `initiationType` uses an invalid code
2. `ocid` is missing

For the first error, the issue is incorrectly reported as being in the `date` column:

![image](https://user-images.githubusercontent.com/19265814/59864126-0c1e8580-937e-11e9-838d-7cd2c0e9f417.png)

For the second error, the issue is incorrectly reported as being in the `#test` column:

![image](https://user-images.githubusercontent.com/19265814/59864185-27899080-937e-11e9-887e-869f4d7360bc.png)

This makes identifying the location of errors in spreadsheet data which uses `hashcomments` difficult.

**Comment by robredpath** [comment]
Well, that's alarming! 

@duncandewhurst can you give me an idea of how this affects usage of CoVE? Is `hashcomments` used a lot in practice, or is this something we're just starting to try out? Obviously, we need to get this fixed - but understanding urgency/impact would be helpful for prioritisation.

**Comment by duncandewhurst** [comment]
I'd like to see this in our first batch of priorities for the new non-sprint work.

We have one publisher actively working on producing data using this feature in spreadsheets and another one where it is being considered as an option, so it isn't used a lot yet, but the bug does severely impact how useful CoVE's validation feedback is for those using this feature.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix incorrect spreadsheet validation errors when using hashcomments](https://trello.com/c/AkNYenvb/6-fix-incorrect-spreadsheet-validation-errors-when-using-hashcomments)

**Comment by robredpath** [comment]
We did this, but apparently didn't tell anyone. Fixed now.
