### ISSUE TITLE
OCDS: Improve error messages for arrays of strings or numeric values

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#1188]
CoVE reports the array index at the start of the error message when array elements are of the wrong type, e.g:

![image](https://user-images.githubusercontent.com/19265814/60106120-8a06d600-975c-11e9-8f43-d69d321fed15.png)

This is confusing because it looks like the data contains a `0` or a `1` etc.

One option to make it clearer could be:

> Element X in the array is not a...

cc @jpmckinney

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make OCDS CoVE present errors in arrays more clearly](https://trello.com/c/83Dfbi82/23-make-ocds-cove-present-errors-in-arrays-more-clearly)

**Comment by robredpath** [comment]
@duncandewhurst is this Done, from your perspective? There's the work in https://github.com/OpenDataServices/lib-cove/pull/24 which I think fixes this (the correction from @jpmckinney notwithstanding)

**Comment by duncandewhurst** [comment]
Yep, looks good.
