### ISSUE TITLE
OCDS: Include a link to the publication policy in the headlines box

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#1194]
Publishers are encouraged to provide a link to their [publication policy](http://standard.open-contracting.org/latest/en/implementation/publication_policy/) in the `publicationPolicy` field in the package metadata.

Publication policies provide important contextual information for users of the data, so it would be good to include this link (where available) in the CoVE interface.

Putting it alongside the link to the license in the headlines box seems like the natural place.

I've tagged this as bitesize as I assume it's just a case of replicating what already happens for the licence link

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Include a link to the publication policy in the headlines box of CoVE](https://trello.com/c/BeuQn466/24-include-a-link-to-the-publication-policy-in-the-headlines-box-of-cove)
