### ISSUE TITLE
OCDS: Clarify "Download Data" text

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1196]
See https://github.com/OpenDataServices/cove-oc4ids/issues/30, replacing "OC4IDS project package" with the appropriate OCDS text (e.g. "OCDS release package").

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CoVE: Clarify "Download Data" text](https://trello.com/c/UPQs2jcZ/2-cove-clarify-download-data-text)

**Comment by jpmckinney** [comment]
Moved
