### ISSUE TITLE
OCDS: "First 3 examples" should not have ambiguous types

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1198]
From https://github.com/OpenDataServices/cove-oc4ids/issues/20

If the value is a string, it should be surrounded by quotation marks. This makes it easier to see that e.g. 500 is `"500"` instead of `500`. It also means something will be printed to the screen for the empty string (`""` instead of nothing).

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["First 3 examples" should not have ambiguous types](https://trello.com/c/vRR3Moi4/40-first-3-examples-should-not-have-ambiguous-types)

**Comment by jpmckinney** [comment]
Moved
