### ISSUE TITLE
OCDS: How frequently do people click on downloads?

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1202]
If this isn't possible to determine from server logs, it's easy to add Google Analytics events measurement, e.g. https://support.google.com/analytics/answer/1136960?hl=en&ref_topic=1033067

Since we are talking a lot recently about DRT as a conversion tool, it'd be useful to assess the popularity of the feature.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [How frequently do people click on downloads?](https://trello.com/c/NsA90WsT/36-how-frequently-do-people-click-on-downloads)

**Comment by robredpath** [comment]
I've had a quick look at this on server logs. Over the course of 13 days I can see 8 instances of what look like humans using the download function; 4 of these downloaded the JSON, and 4 downloaded the generated spreadsheet. We can (and should!) check this a few times in the future to see if that's a normal amount for us.

**Comment by jpmckinney** [comment]
The server keeps two weeks of `/var/log/apache2/other_vhosts_access.log*` files.

```
find /var/log/apache2 -name '*access.log*' -exec zgrep /media/ '{}' \+ | grep -v python-requests/2.24.0 | grep unflattened.json | wc
# 24
find /var/log/apache2 -name '*access.log*' -exec zgrep /media/ '{}' \+ | grep -v python-requests/2.24.0 | grep flattened.xlsx | wc
# 5
```

Non-bot requests over the same period:

```
find /var/log/apache2 -name 'other_vhosts_access.log*' -exec zgrep Mozilla/ {} \+ | grep -Eiv '(bot|AppBeat|CensysInspect|YandexImages|zgrab)/|Netcraft|Seekport|SemanticScholarBot|SEOkicks' | wc
# 6670
```

(User agents can be reviewed by replacing `wc` with `cut -d'"' -f 6 | sort | uniq`.)

So, in general, people do not click on downloads much, so I think it's safe to conclude that the DRT is not much used as a conversion tool.
