### ISSUE TITLE
[IATI] Include XML declaration in XML file 

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#1206]
I noticed that the converted file does *not* include the opening line:

> \<?xml version="1.0"?\>

This isn't a problem for some applications.  However, if I try to import a CoVE XML file into AidStream, it declares it not valid XML ---> I have to hand edit the CoVE file to get it imported

cc/ @rory09 @robredpath

**Comment by Bjwebb** [comment]
(angle bracets `<` `>` need to be escaped on Github `\<` `\>` or included in a codeblock e.g. ` ``` `, I've edited to fix this)

**Comment by Bjwebb** [comment]
Including the XML declaration is a SHOULD (not a MUST) in the XML spec https://www.w3.org/TR/xml/#sec-prolog-dtd. Aidstream should accept files without it, so we should report a bug.

Adding an XML declaration is a one line change in flatten-tool, so we can also do that. However, the XML declaration is slightly different from the above, as it has encoding information. Could you manually edit a file with this to check if it works in Aidstream:
```
<?xml version='1.0' encoding='utf-8'?>
```

**Comment by stevieflow** [comment]
>  Could you manually edit a file with this to check if it works in Aidstream

have tested a file with that.  It works fine @Bjwebb 

cc/ @rory09

**Comment by stevieflow** [comment]
> Adding an XML declaration is a one line change in flatten-tool, so we can also do that.

That would be great

**Comment by Bjwebb** [comment]
This is now deployed to live: https://iati.cove.opendataservices.coop/
