### ISSUE TITLE
OCDS: Remove homepage content from expired results pages

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1209]
e.g. https://standard.open-contracting.org/review/data/704b068b-af6b-4dbd-9001-e0430e2a8e16

It is just confusing and distracts from the main message.

**Comment by robredpath** [comment]
Agreed. We could probably make some use of that space, though - with some custom text that's helpful to someone who's come to an expired results page!

**Comment by jpmckinney** [comment]
Moved
