### ISSUE TITLE
Paste option should specify 'Paste JSON' 

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#121]
One use case for this would be copy+paste from Excel/Calc, but this is tab seperated, which flattentool doesn't currently support. https://github.com/OpenDataServices/cove/issues/122

**Comment by caprenter** [comment]
I think our original intention was that it would probably be useful for people to paste bits of JSON into the tool.

Now the tool supports uploads of JSON, CSV and Excel, potentially it could be confusing about what you can paste in.

One option might be to say PASTE (JSON only) - if we don't think there is a need to support CSV pasting.

I can see how I might want to paste the first 5 lines from a CSV text file into the app.
Also if you use the back button you can get back to your paste box with the content still in it, so potentially you could edit in line and resubmit stuff etc

Of course the paste from Excel could cause problems, and this might just be a feature we can live without.

**Comment by timgdavies** [comment]
I think this is something to add to the long-list of features, but only prioritise once we have a clear use case of someone wanting to do this.

I suspect it might be more of immediate use for other future CoVE processes (e.g. not flatten-tool, but taglifter in the first instance).

**Comment by Bjwebb** [comment]
We now say JSON only on the paste box on http://dev.cove.opendataservices.coop/ocds/

Since we have nothing in the current roadmap for additional paste formats I'm closing this issue.
