### ISSUE TITLE
OCDS: Link to OCDS Merge test cases if merged releases present

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1210]
Add a note to the Headlines like: "This file contains compiled releases [and versioned releases]. If you created these merged releases, we encourage you to test your implementation of the [merge routine](https://standard.open-contracting.org/latest/en/schema/merging/) using the [OCDS Merge test cases](https://github.com/open-contracting/ocds-merge#reference-implementation). For assistance, please contact the [OCDS Helpdesk](mailto:data@open-contracting.org)."

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Link to OCDS Merge test cases if merged releases present](https://trello.com/c/oboiSZH9/35-link-to-ocds-merge-test-cases-if-merged-releases-present)

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/cove-ocds/issues/54
