### ISSUE TITLE
"(giant block of JSON) has non-unique elements" validation error should be better presented

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1220]
Added 2019-09-10 by @Bjwebb:

In https://github.com/OpenDataServices/cove/issues/895#issuecomment-514122920 @duncandewhurst wrote:

> I came across [another variant](http://standard.open-contracting.org/review/data/a842e150-06a3-4c8a-b98d-e121919638e3) of this issue today when validating a record package from Uganda, the path to the error was `records`:
> 
> > (giant block of JSON) has non-unique elements.
> 
> ![image](https://user-images.githubusercontent.com/19265814/61698754-881b3d00-ad31-11e9-82a6-83632427a220.png)

**Comment by robredpath** [comment]
@Bjwebb is it fairly straightforward to remove the giant block of JSON and give some sort of meaningful feedback on where the error is so that the user can track it down?

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data Review Tool: Correct reporting of large blocks of JSON](https://trello.com/c/dXzzBjKM/48-data-review-tool-correct-reporting-of-large-blocks-of-json)

**Comment by Bjwebb** [comment]
I'm having a look at this to see what we can easily do. @duncandewhurst can you share the data that had this issue? (cove link has expired)

**Comment by duncandewhurst** [comment]
https://standard.open-contracting.org/review/data/5a270762-383e-4450-ab53-8111a9c68d89

**Comment by Bjwebb** [comment]
Looking into this, we already overwrite the `uniqueItems` validation function, to check the uniqueness of IDs instead, where they are available (https://github.com/OpenDataServices/cove/issues/155). However, this doesn't work for records, which only have OCIDs.

We can check OCIDs instead, if we know it's a record*. This should also speed up validation of records in CoVE, because checking the OCIDs for uniqueness is quicker than checking the whole record (see https://github.com/OpenDataServices/cove/issues/155).

.

\* From the validation function, the context we have is a bit limited (the key `records` doesn't get passed through). Here is the view we have of the schema:
```python
{'description': 'The records for this data package.', 'type': 'array', 'minItems': 1, 'items': {'$ref': '#/definitions/record'}, 'uniqueItems': True}
```
So, we can check this is about records using the `$ref`, but we must be aware that this could change.

**Comment by Bjwebb** [comment]
There's a lib-cove PR for this now: https://github.com/OpenDataServices/lib-cove/pull/35

Here's what it looks like in CoVE [[link]](http://1220-improve-non-unique-elements-error.dev.cove.opendataservices.coop/review/?source_url=https://raw.githubusercontent.com/OpenDataServices/lib-cove/1220-improve-non-unique-elements-error/tests/lib/fixtures/common/records_non_unique.json):

![Screenshot from 2019-10-25 12-36-31](https://user-images.githubusercontent.com/634/67568443-239ebe00-f724-11e9-8bd9-2048f169d0ce.png)


There's a new message for arrays missing ids/ocids too [[link]](http://1220-improve-non-unique-elements-error.dev.cove.opendataservices.coop/review/?source_url=https://raw.githubusercontent.com/OpenDataServices/lib-cove/1220-improve-non-unique-elements-error/tests/lib/fixtures/common/records_non_unique_no_ocid.json):

![Screenshot from 2019-10-25 12-37-57](https://user-images.githubusercontent.com/634/67568500-4cbf4e80-f724-11e9-82d5-57639348ee5b.png)

There's also been a change of case from "Non-unique ID Values" to "Non-unique id values", as this seems more consistent with what we're doing elsewhere: [[link]](http://1220-improve-non-unique-elements-error.dev.cove.opendataservices.coop/review/?source_url=https://raw.githubusercontent.com/OpenDataServices/lib-cove/1220-improve-non-unique-elements-error/tests/lib/fixtures/common/releases_non_unique.json):

![Screenshot from 2019-10-25 12-39-05](https://user-images.githubusercontent.com/634/67568812-1fbf6b80-f725-11e9-87f0-9c1edb924e58.png)

**Comment by duncandewhurst** [comment]
Thanks @Bjwebb, this looks good to me!

**Comment by Bjwebb** [comment]
This is fixed in the live deploy now — https://standard.open-contracting.org/review/?source_url=https://raw.githubusercontent.com/OpenDataServices/lib-cove/master/tests/lib/fixtures/common/records_non_unique.json
