### ISSUE TITLE
"missing but required" triggers lots of errors if a field is mis-spelled. 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1225]
We now group validation errors by type in 360 and OCDS CoVE, but if there's lots (eg a heading name is mis-spelled in a 360 spreadsheet) then the page is very long and can be offputting for a user who's only actually made one mistake. 

I think this might be a regression, as IATI CoVE groups them and displays only the first 3. I can't actually remember, though! 

Any thoughts @Bjwebb ?

**Comment by Bjwebb** [comment]
Looks like a regression bug with how we group validation messages coming from the JSON schema library. IATI CoVE is probably not affected because the XML schema library works slightly differently.

**Comment by robredpath** [comment]
@Bjwebb this seems to be fixed - did this...erm...happen?

**Comment by Bjwebb** [comment]
No, I think this is still broken: https://dataquality.threesixtygiving.org/data/3778f1a5-6dc4-4ed8-8bfc-dc183318cc88
Note that this applies to "X is missing but required", but not "X is missing but required within Y"

**Comment by KDuerden** [comment]
Yes, just been playing around and seen that it is grouping as intended for nested fields (eg in recipient object) but not for other fields like title, description etc

**Comment by Bjwebb** [comment]
Here's a spreadsheet to reproduce this: [missing.xlsx](https://github.com/OpenDataServices/cove/files/4317496/missing.xlsx)
It also includes an "X is missing but required within Y" row which is grouped correctly.

![Screenshot from 2020-03-11 10-10-20](https://user-images.githubusercontent.com/634/76405821-a5645080-6380-11ea-868f-7c265c2368e5.png)

**Comment by Bjwebb** [comment]
To fix this we need to make a change in lib-cove, that would affect the message text outputted by BODS CoVE. 360 and OCDS CoVE message text will not be affected (although obviously grouping will be).

My suggestion is to replace numbers in BODS error messages (indices of arrays), with some sort of generic placeholder (e.g. `[number]`). This would group cases of the same error messages with different array indices. The array index would still be visible in the full path ("Location of first 3 errors" column in the screenshot).

@odscjames @kd-ods @stevenday Does this sound okay?

![Screenshot from 2020-03-11 13-55-38](https://user-images.githubusercontent.com/634/76424399-18c98a80-63a0-11ea-806f-e0932a6e2758.png)

**Comment by kd-ods** [comment]
@Bjwebb I see no problem with that.

**Comment by Bjwebb** [comment]
This is now in lib-cove https://github.com/OpenDataServices/lib-cove/pull/51

**Comment by BibianaC** [comment]
@Bjwebb is this done?

**Comment by Bjwebb** [comment]
Yes.
