### ISSUE TITLE
OCDS: Don't report errors at different array indices separately

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1237]
![Screen Shot 2019-10-17 at 3 23 16 PM](https://user-images.githubusercontent.com/26463/67040778-2b41df80-f0f2-11e9-912a-f21b1fabb7c6.png)

"awardID is missing but required within contracts" should only appear once. It's not a relevant difference that the error occurred at index 0, 1, 2, etc. of the `contracts` array; these are presently reported separately.

**Comment by jpmckinney** [comment]
Please add to Trello. A data file (too big to upload) I received recently generated thousands of repetitions…

**Comment by duncandewhurst** [comment]
+1 I've come across this issue twice this week

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't report errors at different array indices separately](https://trello.com/c/6b5iP6ti/59-dont-report-errors-at-different-array-indices-separately)

**Comment by duncandewhurst** [comment]
Files to reproduce the issue:

[spreadsheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vTYez3rtlyL06ZTif6c3WC5JV24Jpvrf6UCH2HaJoE48SKpLifViOrbwXsp5bUbgkZ9xWGxZ0pL6zVk/pub?output=xlsx)

[json](https://drive.google.com/file/d/1hzuNPhwBUc-tYjtBr3Yw5oUUyLL35Zcy/view?usp=sharing)

**Comment by Bjwebb** [comment]
This is the same issue as https://github.com/OpenDataServices/cove/issues/1225

**Comment by Bjwebb** [comment]
This is now fixed in lib-cove https://github.com/OpenDataServices/lib-cove/pull/51. Next steps are to make a release and add it to cove-ocds.

**Comment by Bjwebb** [comment]
The fix is now live on https://standard.open-contracting.org/review/
@duncandewhurst Could you check that this now behaves as expected?

**Comment by duncandewhurst** [comment]
Looking good, thanks @Bjwebb!
