### ISSUE TITLE
OCDS: Move OCP logo to footer, using new logo

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1245]
![OC_logo_RGB_grey](https://user-images.githubusercontent.com/26463/68507566-39d76e80-023a-11ea-9da8-275ed7fca6ee.png)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move OCP logo to footer + use new logo](https://trello.com/c/qSRe3mn0/75-move-ocp-logo-to-footer-use-new-logo)

**Comment by jpmckinney** [comment]
Moved
