### ISSUE TITLE
OCDS: Cove reports duplication when an array of strings has more than 1 item

### ISSUE THREAD

**Issue by yolile** [OpenDataServices/cove#1246]
We hadnt noticed this yet because all of the string arrays in the schema currently doesn't have the property `"uniqueItems": true`, but the [coveredBy](https://github.com/open-contracting-extensions/ocds_coveredBy_extension) extension has it and when the field is populated with more than one string, cove reports it as a duplication: 

Minimal example:
![image](https://user-images.githubusercontent.com/6834122/68674009-cb452a00-0533-11ea-9fcb-80ba8a6b5861.png)

![image](https://user-images.githubusercontent.com/6834122/68673986-bf596800-0533-11ea-87b9-d8974d44b527.png)

**Comment by yolile** [comment]
Actually, this happens with any object that doesn't have the id field.

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data Review Tool: Correct reporting of large blocks of JSON](https://trello.com/c/dXzzBjKM/22-data-review-tool-correct-reporting-of-large-blocks-of-json)

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data Review Tool: Correct reporting of large blocks of JSON](https://trello.com/c/dXzzBjKM/22-data-review-tool-correct-reporting-of-large-blocks-of-json)

**Comment by Bjwebb** [comment]
Here's a text copy of the JSON you shared (yours seems to be an image):
```
{
  "version": "1.1",
  "extensions": [
    "https://raw.githubusercontent.com/open-contracting-extensions/ocds_coveredBy_extension/master/extension.json"
  ],
  "releases": [
    {
      "tender": {
        "coveredBy": [
          "a",
          "b"
        ]
      }
    }
  ]
}
```

**Comment by Bjwebb** [comment]
This should be fixed now on the live CoVE instance https://standard.open-contracting.org/review/
