### ISSUE TITLE
360Giving: Provide helpful feedback on Meta tab 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1290]
Right now, if you provide a Meta tab with some information missing / broken we don't really tell you - we expect you to work it out from the way that CoVE presents the information back to you. 

We should present some helpful feedback, such as identifying which fields haven't been provided if any metadata is present.

**Comment by KDuerden** [comment]
This has just been pointed out to me by publisher, seems sensible to add here
**The file was issued on** is blank on all data with meta tab I have tested - ([use this file for an example](https://www.dropbox.com/s/kwyobiawsppwauv/Mercers%20Company_360_data_FINAL.xlsx?dl=1)). If this is something that's not easy to display in current iteration of CoVE it seems sensible to remove the text for now.

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Provide helpful feedback on Meta tab](https://trello.com/c/UPF85aL2/112-provide-helpful-feedback-on-meta-tab)

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Metadata "The file was issued on"](https://trello.com/c/RmUnoxwy/119-metadata-the-file-was-issued-on)

**Comment by BibianaC** [comment]
@KDuerden the issue about "The file was issued on" is now fixed and deployed.

**Comment by KDuerden** [comment]
Thanks @BibianaC 
Is this intended to show the issued date if available and not if it isn't, or has this update removed the issued date from showing in CoVE entirely?

**Comment by BibianaC** [comment]
@KDuerden it only shows it if there is one available.

**Comment by KDuerden** [comment]
I have tested with files with meta tab and issued date but it doesn't appear.
Eg this [file](https://docs.google.com/spreadsheets/d/1ocHsmXqFY57EQvMo8736pQX4uflt-MT7cOwDvkH62NI/edit#gid=1949133049)
The [results in CoVE](https://dataquality.threesixtygiving.org/data/5a0b7c95-c2a0-434f-ae22-3cb4c64052bd).

**Comment by BibianaC** [comment]
@KDuerden thanks for the example, I will check it.

**Comment by BibianaC** [comment]
@KDuerden I have found that there were many information in the `metadata` tab that was not being displayed. I have fixed it and now the results look like this:

<img width="981" alt="Screen Shot 2020-10-15 at 14 29 47" src="https://user-images.githubusercontent.com/9610927/96134014-09d92680-0ef3-11eb-86fd-85b829200a4f.png">

(The fix is not deployed)

**Comment by KDuerden** [comment]
That looks great, really helpful. Thank you.

**Comment by BibianaC** [comment]
@KDuerden The fix is now deployed.

**Comment by KDuerden** [comment]
Brilliant!
