### ISSUE TITLE
Additional checks page formatting makes it hard to read

### ISSUE THREAD

**Issue by KDuerden** [OpenDataServices/cove#1293]
Making a note for future reference, to look at when doing development work on COVE
The formatting of the text is much less readable now it includes the trigger information etc. https://dataquality.threesixtygiving.org/additional_checks

As this is mainly a page for internal use it doesn't need to be pretty but an adjustment to the tables might help make it more useable.

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Additional checks formatting](https://trello.com/c/NT1WecpX/111-additional-checks-formatting)

**Comment by BibianaC** [comment]
@KDuerden is this change ok?

<img width="1203" alt="Screen Shot 2020-10-09 at 15 31 07" src="https://user-images.githubusercontent.com/9610927/95595917-a3608e00-0a44-11eb-9eb3-38f8b47cf9a7.png">

**Comment by KDuerden** [comment]
That looks great - big improvement thank you!

**Comment by BibianaC** [comment]
@KDuerden this has been now done and deployed.
