### ISSUE TITLE
Quality check email triggers for field intended for emails

### ISSUE THREAD

**Issue by KDuerden** [OpenDataServices/cove#1298]
Quality checks includes a look for text that might be an email. 

For files which include these details deliberately - eg Funding Org:Email or Recipient Org:Email could this feedback be suppressed?
![image](https://user-images.githubusercontent.com/20462640/93231001-3a049c80-f770-11ea-994e-f64e72267adc.png)

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quality check email triggers for field intended for emails](https://trello.com/c/nY3OYbqy/116-quality-check-email-triggers-for-field-intended-for-emails)

**Comment by BibianaC** [comment]
@KDuerden what file did you check?

**Comment by KDuerden** [comment]
It was a unpublished file, but this one has them too: https://localtrust.org.uk/wp-content/uploads/2018/10/2018-08-16-Big-Local-Trust-360-Giving-2010.2018.xlsx

Current results: https://dataquality.threesixtygiving.org/data/fc5ac075-54eb-4bb2-8bc5-ac9ff9f348d3

**Comment by BibianaC** [comment]
@KDuerden The issue has been fixed and deployed.
