### ISSUE TITLE
IATI CoVE - #hashcomments still needs to be included

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#1299]
It seems that the hashcomments setting still has to be explicitly referenced in the Meta sheet of an IATI workbook - is that correct?

I know that we bundled this in as a default for 360 CoVE (and maybe OCDS @duncandewhurst?) as the feature is a good utility that (as per our discussion at the time) that didnt need an explicit call.

Is this a setting within CoVE, that can be applied to the IATI instance, or is this something that requires more in depth development?

**Comment by duncandewhurst** [comment]
As far as I'm aware we need to set it in the Meta sheet for OCDS CoVE

**Comment by stevieflow** [comment]
Thanks @duncandewhurst 

Hmmm - maybe I dreamt it about 360!  @KDuerden can you recall?

**Comment by KDuerden** [comment]
@stevieflow I know you have included hashComment in a meta tab to hash out data from other tabs. However Meta tab works in 360 Cove without needing to use hashComment - all current examples in our data are hash-less!

**Comment by stevieflow** [comment]
Thanks @KDuerden 

> all current examples in our data are hash-less!

But I think you do need the hash control, if you include a sheet or comment you want to exclude from conversion?  The examples you cite don't have this, do they?  cc/ @mrshll1001

**Comment by KDuerden** [comment]
> But I think you do need the hash control, if you include a sheet or comment you want to exclude from conversion? The examples you cite don't have this, do they?

I don't think have anyone doing that in live data, but yes, anything that isn't 360Giving Data Standard data or in the Meta tab needs to be hashed or the data will be invalid.

**Comment by Bjwebb** [comment]
The hashComment setting should need to be included for OCDS, but not IATI or 360Giving. I've checked, and this seems to be the case. It should be easy to turn on/off.

**Comment by stevieflow** [comment]
Thanks @Bjwebb - have tested, and can confirm this is the case with IATI
