### ISSUE TITLE
Delete (or hide) a dataset from the dashboard

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#130]
When this can be done (only if not pushed to staging/live) relates to this workflow question https://github.com/OpenDataServices/cove/issues/111

**Comment by Bjwebb** [comment]
We now have a delete button on the dev site, e.g. http://etl.nrgi-dev2.default.opendataservices.uk0.bigv.io/dataload/1/

This will not delete unless the data is first removed from both staging and live.

@timgdavies Could you check this behaves how we want it to?

**Comment by timgdavies** [comment]
Delete function is working as expected - though error message when not removed from staging and live isn't terribly user friendly.

Can we disable button unless with tooltip on why disabled when it's not in a state that allows delete.

**Comment by Bjwebb** [comment]
Will look into doing that.

**Comment by Bjwebb** [comment]
I've disabled and added a tooltip as you suggest. Now deployed to http://etl.nrgi-dev2.default.opendataservices.uk0.bigv.io/
