### ISSUE TITLE
IATI - refresh of codelist values needed?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#1301]
@Bjwebb @kindly @BibianaC  I think our store of IATI codelists might be out of date/synch - there's Non Embedded codelist value errors, when the codes are valid (@siwhitehouse has an example)

This might be a better source of data from which to pull the codelist - https://codelists.codeforiati.org/ - but I'm not sure what the underlying process currently is...

**Comment by Bjwebb** [comment]
We have [a command to keep these in sync](https://github.com/OpenDataServices/cove/blob/master/get_iati_non_embedded_codelists.py), but I don't think its run automatically, meaning they're out of date.

**Comment by stevieflow** [comment]
Thanks

Please can we run it , to get back into synch, in the meantime?

**Comment by kindly** [comment]
This is merged and deployed.  @stevieflow could you check to see if the results (code-list values) are what you expect.

**Comment by stevieflow** [comment]
Thanks @kindly 

@siwhitehouse want to check this via the SDG vocab you observed?

**Comment by stevieflow** [comment]
I tested some data with an SDG vocabulary - and this pass without a fail warning

**Comment by stevieflow** [comment]
> We have a command to keep these in sync, but I don't think its run automatically

@Bjwebb @kindly @BibianaC  to avoid this (see #1354 for latest example), could the command be autorun with a github command?

(suggestion ^ from @andylolz , via code4IATI channels)

**Comment by andylolz** [comment]
Thanks @stevieflow,

Specifically on the [Reporting Organisation codelist](https://codelists.codeforiati.org/ReportingOrganisation/) – this codelist seems to update pretty frequently (more than once per week). You can get a sense of that from [its git history](https://github.com/codeforIATI/Unofficial-Codelists/commits/master/xml/ReportingOrganisation.xml). So auto-checking for updates pretty frequently (weekly or even daily) would help prevent validation false negatives.

**Comment by stevieflow** [comment]
Thanks @andylolz 

Yes - with the new org references check, being in synch with the Reporting Org codelist will have to be automated, to save multiple requests to @kindly @BibianaC and/or @Bjwebb !

**Comment by stevieflow** [comment]
On a backlog for @odscjames !

**Comment by Bjwebb** [comment]
FWIW, the new org ref work pulls from codeforiati each time https://github.com/OpenDataServices/cove/blob/live/cove_iati/lib/iati.py#L499
It would probably be good to be more consistent about this though.

**Comment by ghost** [comment]
So let me get this clear - this is updating some / all of the codelists in https://github.com/OpenDataServices/cove/tree/live/cove_iati/non_embedded_codelists regularly with the latest ones from https://codelists.codeforiati.org/ ? Am I correct?

If so, we can't do that in GitHub actions alone - once that is done we would still have to deploy the new version of cove regularly, or the new codelists would not make it to the server. We could do GitHub actions AND some kind of C.D./Cron tasks so deploys happen automatically.

Or we could take the approach Ben suggests and have the app download all codelists itself regularly.

**Comment by andylolz** [comment]
> FWIW, the new org ref work pulls from codeforiati each time https://github.com/OpenDataServices/cove/blob/live/cove_iati/lib/iati.py#L499

Aha, gotcha! I had missed that.

> If so, we can't do that in GitHub actions alone - once that is done we would still have to deploy the new version of cove regularly, or the new codelists would not make it to the server. We could do GitHub actions AND some kind of C.D./Cron tasks so deploys happen automatically.
> 
> Or we could take the approach Ben suggests and have the app download all codelists itself regularly.

Either of those options sounds good to me.

**Comment by stevieflow** [comment]
> Either of those options sounds good to me.

I agree.  I haven't a real preference.  The key bit is that the codelists update without our need to intervene manually.  @odscjames I'd also guess we'd need some kind of monitoring in place though, in case there was a fail?

As for timescales, then if it's confirmed that https://codelists.codeforiati.org/ReportingOrganisation/ is already auto synched, then this doesn't become _as_ urgent :)

**Comment by ghost** [comment]
Doing in parts - https://github.com/OpenDataServices/cove/issues/1301 adds a requests-cache framework and uses it for ReportingOrganisation.json & OrganisationRegistrationAgency.json
    
Previously these resources were fetched every time we processed something

If this is good, will do a second pull request that uses the same framework for the contents of https://github.com/OpenDataServices/cove/tree/live/cove_iati/non_embedded_codelists

**Comment by stevieflow** [comment]
Thanks @odscjames 

> If this is good 

I'm not qualified to answer - so wonder if @andylolz might take a look?

**Comment by andylolz** [comment]
Ah okay, I see. I haven’t tested it out, but this looks like a good improvement to me. So it will fetch at most once per day? That seems fine to me.

**Comment by ghost** [comment]
> So it will fetch at most once per day?

Yes

@Bjwebb  has approved https://github.com/OpenDataServices/cove/pull/1363 , I will put it live early next week

**Comment by ghost** [comment]
Deployed - ReportingOrganisation.json & OrganisationRegistrationAgency.json now fetched once per day (or on every deploy, if deploys are more regular)

TODO: Deal with files in https://github.com/OpenDataServices/cove/tree/live/cove_iati/non_embedded_codelists

**Comment by ghost** [comment]
Non-Embedded codelists are now loaded regularly from eg https://codelists.codeforiati.org/api/xml/ActivityScope.xml

@stevieflow I think this issue can be closed now?

**Comment by stevieflow** [comment]
Thanks @odscjames
