### ISSUE TITLE
sample links for conversion files on IATI xml are incorrect 

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#1331]
On

https://iati.cove.opendataservices.coop/

The open public google spreadsheet is 

https://docs.google.com/spreadsheets/d/1V8Cs4rivr6HDiDsne2bVECJiAXHcHBDiy_JEU9oPgRQ/edit?usp=sharing

Yet, when we provide the link to convert to XML, we have this link:

https://iati.cove.opendataservices.coop/?source_url=https://docs.google.com/spreadsheets/d/1WkCin68arZkAIhjxmKkml0MAskLcw9mkHctNmB_gH2I/export?format=xlsx

That ^ uses an older version of the demo data

Please change the link to convert the Activity file to xml:

![IATI-CoVE](https://user-images.githubusercontent.com/1209944/109638441-edf2bc00-7b45-11eb-9797-8f60382760c1.png)

to 

https://iati.cove.opendataservices.coop/?source_url=https://docs.google.com/spreadsheets/d/1V8Cs4rivr6HDiDsne2bVECJiAXHcHBDiy_JEU9oPgRQ/export?format=xlsx

**Comment by Bjwebb** [comment]
Live now https://iati.cove.opendataservices.coop/
