### ISSUE TITLE
[IATI] xls template use on Google Sheets (remote sheets)

### ISSUE THREAD

**Issue by siemvaessen** [OpenDataServices/cove#1350]
More of a question than an issue, but I am wondering if any work was done on using a single Google Sheet with tabs (like the current xls template. but then as a Google Sheet) rather than an offline xls file? 

We found this template in your guidance which references this google file template https://docs.google.com/spreadsheets/d/1V8Cs4rivr6HDiDsne2bVECJiAXHcHBDiy_JEU9oPgRQ/edit but that file is:

1. not http reachable by the link/pick up file provided in the cove UI
2. upon downloading that as a testing results.xlsx file no longer seems to a valid schema file for IATI?

**Comment by Bjwebb** [comment]
> 1. not http reachable by the link/pick up file provided in the cove UI

This is weird, it seems to be reachable by our CoVE instance, and by a private browsing window on my machine, but not by curl on the commandline. What software have you tried to access it with?

> 2. upon downloading that as a testing results.xlsx file no longer seems to a valid schema file for IATI?

For me, it validates according to our CoVE instance. What are you using to test if it's valid?

![Screenshot from 2021-06-24 15-24-32](https://user-images.githubusercontent.com/634/123280062-5bb16200-d500-11eb-826f-efdc667c59cc.png)

**Comment by siemvaessen** [comment]
Apologies @Bjwebb for some reason I had a very strange Browser session, as I retested and seemed to work.
