### ISSUE TITLE
COVID-19 DAC 5 Digit Sector code flagged as invalid

### ISSUE THREAD

**Issue by lucasfog1** [OpenDataServices/cove#1354]
Hello,

The new sector code for "COVID-19 Control" (12264) is being flagged as invalid by IATI Cove. Not sure if this is the correct place to report this.

![image](https://user-images.githubusercontent.com/66275247/131650187-53b6adc2-24d1-4786-ac6f-039f80e08bdf.png)

Many thanks

Lucas

**Comment by Bjwebb** [comment]
This is the best place to report this, thanks.

At the moment we don't pull in the new sector codes automatically. I will run the script to do this, and then put that change live over the next couple of days. I'll let you know once it's fixed.

**Comment by Bjwebb** [comment]
This should be fixed now.

**Comment by stevieflow** [comment]
Thanks @lucasfog1 for letting us know
