### ISSUE TITLE
[IATI] - IATI Registry (rather than "iati register")?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#1360]
When a match in the publisher list is found, we see:

> There are 1 publisher from the iati register used in this dataset

![IATI-CoVE (5)](https://user-images.githubusercontent.com/1209944/134191236-7ac94c90-99b0-48c7-a7b7-fa498e59ba4e.png)

Please can we change this text to :+1: 

There are 1 publisher from the IATI Reporting Org list used in this dataset

Please also link "Reporting Org list" to https://codelists.codeforiati.org/ReportingOrganisation/

**Comment by BibianaC** [comment]
@stevieflow would you not want to change "there are" for "there is" as well?

**Comment by stevieflow** [comment]
@BibianaC ideally, that would be conditional on the number of results.  When it's 1, then "there is", when > 1, "there are"...!

**Comment by BibianaC** [comment]
@stevieflow Maybe another ticket should be opened for this and linked to this one.

**Comment by stevieflow** [comment]
> Maybe another ticket should be opened for this and linked to this one.

Sure: https://github.com/OpenDataServices/cove/issues/1361

**Comment by Bjwebb** [comment]
Fixed.
