### ISSUE TITLE
[IATI] Merge indicators - text

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#1371]
Merge indicators by title.  This function will merge together any indicators in the result block, that share the same title.  No other data will be altered or changed.  This function is designed for instances where multiple periods exist within the same result/indicator, but are not uniquely referenced in the IATI standard or CoVE spreadsheet.

**Comment by Bjwebb** [comment]
@stevieflow How does this look:

![Screenshot from 2022-05-27 17-12-56](https://user-images.githubusercontent.com/634/170738082-c6967b93-a65c-41e7-b2a9-875a18ed15f6.png)

![Screenshot from 2022-05-27 17-13-28](https://user-images.githubusercontent.com/634/170738160-a23d2551-ab1a-4c5c-8175-17fe6e6b4e1f.png)

**Comment by stevieflow** [comment]
Perfect, thanks @Bjwebb
