### ISSUE TITLE
AidType codelist needs updating?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#1386]
I see teh AidType codelist has an additional value https://iatistandard.org/en/iati-standard/203/codelists/aidtype/

> H06 | Refugees and asylum seekers in other provider countries | Costs incurred in other non-ODA eligible provider countries for  basic assistance to asylum seekers and refugees from developing  countries, up to 12 months. The host and origin country of  refugees/asylum seekers shall be specified in one of the descriptive  fields of the CRS (fields 14 or 19).

This doesnt seem to have made its way into the IATI CoVE

Please could this codelist be updated?

cc/ @IsabelBirds

**Comment by markbrough** [comment]
This is now fixed in codelists.codeforiati.org (along with a few other updates), so you may wish to pull these files again from IATI CoVE. See this PR for more details of what else was just fixed:
https://github.com/codeforIATI/IATI-Codelists-NonEmbedded/pull/140

**Comment by Bjwebb** [comment]
Cove should have automatically started using the new Code for IATI codelist.
