### ISSUE TITLE
Update outdated requirements

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#142]
https://requires.io/github/OpenDataServices/cove/requirements/?branch=master

The versions in https://github.com/OpenDataServices/cove/blob/master/requirements.txt and https://github.com/OpenDataServices/cove/blob/master/requirements_dev.txt need updating, and then we need to check that tests run etc.

**Comment by idlemoor** [comment]
Thanks Ben, I'll block out Wednesday (18th) for this if that's ok?

**Comment by Bjwebb** [comment]
Sounds good.

**Comment by idlemoor** [comment]
For the record, the updates were
(live) Django==1.8.6 requests==2.8.1 raven==5.8.1 jdcal==1.2 pytz==2015.7 schema==0.4.0 sqlparse==0.1.18
(dev) flake8==2.5.0 coverage==4.0.2 Werkzeug==0.11.2 coveralls==1.1
