### ISSUE TITLE
Encoding errors on paste text box

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/cove#144]
When submitting [the example in this issue](https://github.com/open-contracting/implementation-and-extensions/issues/8#issuecomment-157862724) to the OCDS Cove via the paste text box, I get a server 500 error. 

Sentry reports:

```
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 250: ordinal not in range(128)
``` 

@Bjwebb suspects this is to do with the encoding set on that text box.

**Comment by kindly** [comment]
I can not reproduce this issue.
The example in the issue has an error.

 ```
"dateSigned": 2013-04-05 12:00:00,
```
There is no quotations marks round the date.

If I add these in then it appears to work fine for me. See:
http://dev.cove.opendataservices.coop/ocds/data/a4af23b8-64f8-481f-86b1-c551ce48e9bd

**Comment by Bjwebb** [comment]
Ah, I can reproduce this on the live site, but not the dev site, so I think it may be a deployment issues.

**Comment by caprenter** [comment]
If I put the example data into a file, and then use the upload options:
On both sites (live/dev) I get:
"We think you tried to upload a JSON file, but it is not well formed JSON.
Error message: Expecting ',' delimiter: line 33 column 27 (char 1212)"

If I then fix the 'quotes round the date' problem, then on both sites (live/dev) the file uploads fine and I get to the explore page and get given feedback on the file (i.e. no server error)

**Comment by timgdavies** [comment]
It was always working fine as an upload, but the issue was with the text box iirc.

**Comment by kindly** [comment]
This is a deployment issue.  It seems to me that uwsgi is for some reason mucking with its environment variables and messing up LANG.  What is confusing is that it is only doing this sometimes, and we are not sure what conditions trigger it.  To find out seems like will be a lot of work. 

Explictly putting
```env = LANG=en_US.utf8```
into the uwsgi config fixes this.
