### ISSUE TITLE
Friendly 500 error page

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/cove#145]
At the moment the 500 error page is unthemed.

It would be good to have a friendly page that lets people know the issue has been reported, and that fits in with the overall theme.

**Comment by timgdavies** [comment]
Any chance we can get this into an upcoming sprint? Would be good to having something so that people using OCDS validator who get errors get told that it will be reported to us.

Even better, if we can then have an internal process to forward any errors that seem to relate to invalid files onto the analyst team, so we can get back to people to help them fix files, that would be great.

**Comment by Bjwebb** [comment]
Yes, I think we can look to get this done in March.

We certainly could be better with how we respond to errors in sentry. It's possible to [display the sentry error ID on the 500 page](https://docs.getsentry.com/hosted/clients/python/integrations/django/#message-references) which I think  would help us respond to people who do contact us with an issue.

**Comment by Bjwebb** [comment]
There is now a test 500 error page at http://dev.cove.opendataservices.coop/ocds/test/500 and http://dev.cove.opendataservices.coop/360/test/500

The ID that's given can be pasted into the search box at https://app.getsentry.com/open-data-services/cove-dev/ (you'll need to clear it's current contents first).

I've assigned this to tim, but @ekoner and @stevieflow may also be able to give feedback. Particularly wrt. to the wording of the message, and what you think of the workflow for looking up the message on Sentry.

**Comment by caprenter** [comment]
I like this.

If we are saying 'get in touch' then I think we should also have a way for people to get in touch. I think that is probably a good thing as well in terms of making it easier for us to have conversations with our users.

Any objections to turning 'get in touch' into a mailto link? (either code[at] or support[at] specific org)?

**Comment by Bjwebb** [comment]
Yes, looks like there's an older issue about contact details. https://github.com/OpenDataServices/cove/issues/90

There's some other error pages in addition to the 500 error that we might want to put emails on, and also if relevant the sentry error ID e.g. the "Sorry we can't process this data" page: http://dev.cove.opendataservices.coop/ocds/data/c3763932-8b3f-4707-941f-857140451cf8

**Comment by Bjwebb** [comment]
I think we might be best using the default helpdesk emails ie. `support@threesixtygiving.org` and `data@open-contracting.org` - as the publisher may already be in contact with the helpdesk, and it makes it clear that it's the same people.

Not sure how helpful it is, but it's possible to construct the mailto link to automatically put that sentry id in the subject line.

**Comment by caprenter** [comment]
The emails and adding in the sentry id both seem like good ideas to me. I say do it.

**Comment by Bjwebb** [comment]
I'm working on this at http://90-error-contact-details.dev.cove.opendataservices.coop/ e.g.
http://90-error-contact-details.dev.cove.opendataservices.coop/ocds/test/500
http://90-error-contact-details.dev.cove.opendataservices.coop/360/test/500
http://90-error-contact-details.dev.cove.opendataservices.coop/ocds/data/026a1b01-1849-40b9-a421-9c9b1086d7cb
