### ISSUE TITLE
When uploading a file to CoVE, I do not know if it is uploading

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#157]
When I am processing a file through CoVE (upload / URL) I have no onscreen information to let me know if the file is "uploading"

Yes, I mean one of these progress bars/animated gifs!

**Comment by Bjwebb** [comment]
We now have a "spinner" on dev: http://dev.cove.opendataservices.coop/

@stevieflow Does that partly cover this issue?

This isn't quite a "progress bar" - it doesn't actually show any information about how far through the process is. On the other hand, I don't think we really know how we'd calculate that information at the moment.

**Comment by stevieflow** [comment]
@Bjwebb thanks

When I send a file through I get a "Loading" page, but I dont see an actual "spinner"....

**Comment by Bjwebb** [comment]
@stevieflow There should be a spinner there.... Is it possible it didn't load due to bad wifi? Could you try again at some point on a different connection?

**Comment by caprenter** [comment]
Is this a Firefox issue - I don't think I'm seeing the spinner gif in my Firefox (e.g. when running selenium tests)

**Comment by Bjwebb** [comment]
Looks like it is, I don't see it in firefox either.
