### ISSUE TITLE
CoVE handles duplicate IDs as duplicate records

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#159]
I've created that a 360 datafile that has two *different* grants (see Value), but the same Identifier.  This is a false environment, arguable, but I have done this to test out how CoVE reacts:

File: https://gist.github.com/stevieflow/45d47f0bff59a6deb524#file-360-duplicateid-differentgrants-xslx

CoVE: http://dev.cove.opendataservices.coop/360/data/38b16308-7b05-4452-abb5-65608813929e

These results suggest there is only one grant / record.  The main point being that nowehere within the results is the user informed of a duplicate Identifier

Hence, in a large dataset, where the potential for duplicate Identifiers might be high, the user would not be informed of such a situation, thus missing key intelligence

This might suggest that CoVE needs to handle records and identifiers differently?

**Comment by Bjwebb** [comment]
@stevieflow Could you upload the xlsx file itself?

**Comment by stevieflow** [comment]
[test.xlsx](https://github.com/OpenDataServices/cove/files/49797/test.xlsx)

I havent got it to hand, but have made something similar - attached

**Comment by Bjwebb** [comment]
That file will now produce this warning:
> Conflict when merging field "amountDisbursed" for id "360G-wolfson-19747" in sheet grants: "40000" != "0". If you were not expecting merging you may have a duplicate ID.

**Comment by Bjwebb** [comment]
There's now warnings for this, e.g. http://release-201604.dev.cove.opendataservices.coop/360/data/8a762a5d-a462-4d53-a207-afcbcaa4aabb
