### ISSUE TITLE
Test should not call external urls

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#16]
Where possible we should be using URLs created locally, so that running the tests doesn't depend on having an internet connection, and the availability of third party services.

**Comment by Bjwebb** [comment]
https://pypi.python.org/pypi/pytest-localserver may be a useful library to help with this.

**Comment by Bjwebb** [comment]
The remaining of external test urls are those of schemas. These are also fetched externally in the application proper, so I have opened a new issue about this https://github.com/OpenDataServices/cove/issues/52

**Comment by Bjwebb** [comment]
https://github.com/OpenDataServices/cove/pull/85 possibly introduces more dependency on external urls to FTS tests. However, I'm not sure if the FTS tests have ever passed without an internet connection,  due to use of external bootstrap.

**Comment by Bjwebb** [comment]
http://django-offlinecdn.readthedocs.org/en/latest/ is a possible approach to continuing to use an external CDN for bootstrap, but also having an offline copy for development.

**Comment by Bjwebb** [comment]
https://github.com/kevin1024/vcrpy is also an interesting approach of capturing what requests to external urls look like, and then automatically mocking them for future test runs.

**Comment by robredpath** [comment]
Closing out - it's pretty rare that we need to run tests entirely offline. We're also refactoring our tests to make it easier to run subsets of tests as necessary.
