### ISSUE TITLE
Failed files allows a converted download

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#165]
On 360Giving CoVE I use this url:
http://www.wolfson.org.uk/media/2740/wolfson-foundation-grants-2014.xlsx

CoVE processes it.
It fails to validate, but it offers me a converted JSON file.
http://dev.cove.opendataservices.coop/media/606b8983-c75c-4c6f-8c3d-23d2cf26ddae//unflattened.json

This file is not 360Giving standard JSON.

I can't decide if this is ok or not!

We could maybe only provide the JSON if the file is valid - although a non-valid file is arguably still of some use. If we did want to offer a non-valid file, would it make sense to indicate that in some way.

All opinions gratefully received

**Comment by Bjwebb** [comment]
Validation is performed on

**Comment by Bjwebb** [comment]
Validation is performed using the converted JSON, so I think we want to provide the invalid JSON to help people understand the validation messages, if nothing else.

**Comment by Bjwebb** [comment]
I strongly feel we should allow download, but flagging invalid JSON better may be useful. @kindly What are your thoughts on this?

**Comment by robredpath** [comment]
Closing - the new layout makes it clearer that the data is invalid. Please re-open if we want to revisit this!
