### ISSUE TITLE
Reduce Validation Errors section (allow download)

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#170]
The Validation Errors section can get incredibly long for some files. Can this be reduced or detail removed completely and replaced with a "Download as CSV" link and total count of errors?

**Comment by caprenter** [comment]
My guess would be that this depends on the type and amount of errors.

I don't know what UI options might be for showing e.g. the first 10 errors and then having an option to 'view all errors'

I think the download as CSV could be a nice feature - but I also like to see something visual on the screen. At the moment it provides a very clear warning that something is wrong, and in many cases it does provide enough information to get things fixed directly.

@ekoner can you provide a link to a file where this problematic behaviour is displayed?

**Comment by ekoner** [comment]
@caprenter No, I think I validated it over a week ago, so the link no longer works. It's a minor issue, so I'm closing for now.
