### ISSUE TITLE
Replace list of "Unique IDs" section with count

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#171]
With large files, this section becomes very long. The information can be found in the "Grants" section. Would a count work instead?

Additionally, can this be displayed only for valid files?

**Comment by caprenter** [comment]
There is conversation about this here.
https://github.com/OpenDataServices/cove/issues/158

Can I suggest that this is a duplicate, and that @ekoner closes this and adds anything from here to that issue?
