### ISSUE TITLE
Make version number of CoVe more visible

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#172]
Could this be displayed with the other information sections for both valid and invalid files?

**Comment by caprenter** [comment]
We don't yet have tagged release versions of CoVE as it is in rapid development just now.

The git commit that the site is running is given in the footer.

It is useful to be able to make a note of the version used when running files against CoVE. If the footer is not a good enough place, we can try other places.

I think longer term as we get to more stable versions, the version used is more likely to be stable for longer and may not need prominent display

**Comment by ekoner** [comment]
Closing after reviewing comments from @caprenter
