### ISSUE TITLE
Extend Grants section, reduce display (allow download)

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#173]
The Grants secion is very useful but for large files, a "download as CSV" link would be more useful than scrolling down potentially thousands of rows.

This would allow adding key information required for the grants section i.e.:
Identifier, Funding Org:Identifier, Funding Org:Name, Description, Title, Award Date, Amount Awarded, Currency, Recipient Org:Identifier, Recipient Org:Name

This only needs to be visible for valid files.

**Comment by caprenter** [comment]
I'm not sure what the download csv link gives you here as converted versions, and the original files (with all the fields) can already be downloaded.

Originally I added this table as a way to take a quick glance to see if the data in the table reflected (some of) the data supplied in the original file/upload/paste. (The idea of explore your data - with the idea that maybe you might want to click through to get more info on one or more grants based on the summary info in the table)

It also allows people to see that there is some useful data in a file even if it does not validate against the schema - so I'm not sure if we should ONLY be showing this table for valid files - I think it does have a use if files are NOT valid (against the schema)

However, it was done as a quick task just to show some rows of data and can certainly be changed.

So do we want a table (maybe just a list of grants is good enough)? (If a list is a list of the first 10 good enough with a click through to see all?) If we want a table, then what columns do we want to show?
Do we want a csv download?
Do we want a 'view' even if a file does not validate against (the schema/additional rules)?

**Comment by Bjwebb** [comment]
I think we've done some work on this table since this bug was raised.

@ekoner Could you check how well the current Cove addresses your concerns?

**Comment by ekoner** [comment]
@Bjwebb the new table is much more useable.
