### ISSUE TITLE
Key metrics for grant section

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#174]
Can we provide a section with some key metrics about the grant section i.e.

Counts for: 
Identifier

Min, max for: 
Award Date, Amount Awarded

Distinct counts for:
Funding Org:Identifier, Recipient Org:Identifier,  Currency 

e.g. "This file contains <count of Identifier> grants awarded between <min Award Date> and <max Award Date> for amounts between <min Amount Awarded> and <max Amount Awarded> in <distinct count of Currency> currencies. Funds were awarded by <distinct count of Funding Org:Identifier> funding organisation(s) to <distinct count of Recipient Org:Identifier> organisations."

This will provide a quick heads up for any issues which may need further analysis.

**Comment by Bjwebb** [comment]
I think the short answer is "yes".

Assigning to @kindly as I think he has a better idea of the detail here (and is likely to be the one implementing this).
