### ISSUE TITLE
XLSX file does not read 

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/cove#176]
The following file causes cove take forever
https://drive.google.com/file/d/0B8CYzWk4uxTVUE51clN3LVBJSW8/view?usp=sharing

The line in flattentool that starts the error is here
https://github.com/OpenDataServices/flatten-tool/blob/master/flattentool/input.py#L225

This basically is an issue with openpyxl.

**Comment by Bjwebb** [comment]
I'll take a look to see if this has anything to do with the fact we're using an older version of openpyxl https://github.com/OpenDataServices/flatten-tool/issues/57

**Comment by Bjwebb** [comment]
This looks like it's fixed in a newer version of openpyxl, so I'll look into how difficult it will be to upgrade.
