### ISSUE TITLE
Are we validating dates properly?

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#188]
The table at the bottom of http://python-jsonschema.readthedocs.org/en/latest/validate/ suggests that we might need an extra dependency for this.

**Comment by kindly** [comment]
Yes you need to add those dependencies but also add the format_checker attribute when validating.
```
validator(schema, format_checker=jsonschema.FormatChecker())
```

**Comment by caprenter** [comment]
So I think we established that we are not currently validating dates at all. We have an idea of how we can do that, can we get a suggested implementation in place?
