### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#195]
When I provide the link below to OCDS CoVE, I get a Bad Request (400) page. I can download the file and it works OK.

http://ville.montreal.qc.ca/vuesurlescontrats/api/releases.json?date_gt=2015-07-01&date_lt=2015-12-31&value_gt=0&value_lt=1000000000&type=contract&order_by=date&order_dir=desc&procuring_entity=comite-executif%3Bconseil-dagglomeration%3Bconseil-municipal%3Bfonctionnaires&activity=Arrondissements%3BCommunications+et+relations+publiques%3BD%C3%A9veloppement+%C3%A9conomique%3BEnvironnement%3BFoncier%3BGestion+de+l%27information%3BImmeubles+et+terrains%3BInfrastructures%3BJuridique%3BOrganisation+et+administration%3BRessources+financi%C3%A8res%3BRessources+humaines%3BRessources+mat%C3%A9rielles+et+services%3BS%C3%A9curit%C3%A9+publique%3BSports%2C+loisirs%2C+culture+et+d%C3%A9veloppement+social%3BTransport%3BUrbanisme+et+habitation%3BAutres&format=json&limit=10000&offset=0

**Comment by Bjwebb** [comment]
Running this locally, it looks like the error is:

```
SuspiciousFileOperation at /ocds/
Storage can not find an available filename for "947c34e5-4835-48f5-b999-93e34751baab/releases_VRSCMiP.json?date_gt=2015-07-01&date_lt=2015-12-31&value_gt=0&value_lt=1000000000&type=contract&order_by=date&order_dir=desc&procuring_entity=comite-". Please make sure that the corresponding file field allows sufficient "max_length".
```

We should be able to resolve this by truncating the filename somehow.
