### ISSUE TITLE
Do we want to keep google translated translations?

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#20]
In order to test the multilingual functionality, I created a Spanish translation using google translate (there's an option to upload a .po file and machine translate all of that).

There's also a French translation, which is similar, but with slightly more manual translations that are likely to be wrong (https://github.com/OpenDataServices/cove/issues/19#issue-71878572).

Do we want to keep the google translated translations as a starting point, or remove them for release, and wait until we have manually translated copies?

**Comment by caprenter** [comment]
I say go with the google translate options. Assigning to @timgdavies for comment.

**Comment by timgdavies** [comment]
Let's leave in for now, but make sure we note it in any announcement.

I can ask some of the Spanish speaking members of OC team at the bank to
help us correct before wide release...

**Comment by caprenter** [comment]
I've added some info to the README about this. Suggest we can close this if that commit is accepted.
