### ISSUE TITLE
Copy for the OCDS front page

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#200]
This has been flagged for review, but there is no further info at this stage

**Comment by timgdavies** [comment]
I've had a go [in this document](https://docs.google.com/document/d/1Tym-CqhVGhQdEsHmoGEARz52q41L0ycg42cCt5t6MJs/edit#) at a wireframe and new text for OCDS validator page. 

Comments / edits on that very welcome. 

(I've not added links in yet - as some will change with updated docs and OCP website)

**Comment by caprenter** [comment]
I'll check through the doc then assign back to @kindly

**Comment by caprenter** [comment]
This all looks good to me - there me be a few questions about how to integrate the header/footer - but that can't really be done yet. 

Also you might need a config addition around available languages. Ask if you have questions.

**Comment by Bjwebb** [comment]
The copy is now on http://dev.cove.opendataservices.coop/ocds/

**Comment by caprenter** [comment]
See also https://github.com/OpenDataServices/cove/issues/235

**Comment by Bjwebb** [comment]
Re:https://github.com/OpenDataServices/cove/issues/200#issuecomment-172508946 The current plan is to restrict all Cove deployments to English/Spanish for now. https://github.com/OpenDataServices/cove/issues/237 This avoids needing an extra config option. We can add one later if we do have other translations for 360Giving or the dev site but not the OCDS validator.

I've also created a separate issue for headers/footers https://github.com/OpenDataServices/cove/issues/240
