### ISSUE TITLE
360Giving: check for Title length 

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#201]
The title must not be more than 140 characters according to: http://www.threesixtygiving.org/standard/reference/

It would be good if CoVE could flag titles longer than 140chars.

This issue is copied over from:
https://github.com/ThreeSixtyGiving/standard/issues/97
where altering the schema to enable this check is discussed

**Comment by stevieflow** [comment]
Is this an example of additional tests (or is it a part of schema tests?)?

**Comment by robredpath** [comment]
Note that the standard says "should", not "must"

**Comment by robredpath** [comment]
This sprint: research what our approach to warning systems / audits / extra tests / 'should's can be

**Comment by Bjwebb** [comment]
We now have the additional checks framework in place such that we could do this.
