### ISSUE TITLE
Why does the dev site look broken?

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/cove#203]

**Comment by Bjwebb** [comment]
For extra points, is there an easy way of pulling in a generic check that tags aren't mismatched?

We had a similar problems with div tags on the NRGI frontend, although there I only got so far as doing a simple count of opening and closing divs.

**Comment by caprenter** [comment]
Like this:  https://github.com/OpenDataServices/resourceprojects.org-frontend/blob/master/fts/test_html.py

**Comment by Bjwebb** [comment]
@kindly I've deployed the commit on dev, but it still looks broken to me http://dev.cove.opendataservices.coop/ . Looks fine on my local copy.

This is presumeably either something to do with deployment, or with how the dev banner is inserted - but I'm not sure. I'll try and look into this further this afternoon, but if anyone else can see what's wrong, do shout!

**Comment by caprenter** [comment]
I think I might see a missing </p> - I'm happy to look into this

**Comment by kindly** [comment]
I have fixed all w3c errors now to see if any of them cause issues.

**Comment by Bjwebb** [comment]
Looks like this was actually a permissions issue on the CSS on the dev server. Will see if I can fix the deploy to avoid this in future.

**Comment by Bjwebb** [comment]
I've updated the salt state to make sure the permissions are correct.

I don't think the tags had anything to do with the underlying problem in the end, but will merge the pull request as it does make our code better.

**Comment by Bjwebb** [comment]
The live site now validates in https://validator.w3.org/nu/?doc=http%3A%2F%2Fcove.opendataservices.coop%2F \o/
