### ISSUE TITLE
More useful error messages

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#205]
Error messages eg: 
'id' is a required property -- how can we make these more "useful"?

**Comment by caprenter** [comment]
Changing these error messages is something that can be done but would be quite resource intensive (i.e. needs a lot of time, and would need a lot of input from a number of people)

Working out what 'more useful' means might help, but even with that it is likely that the effort involved to usefully change these would be difficult to prioritise and justify against other priorities.

An alternative approach we have used before is to have a 'common errors' page: http://validator.iatistandard.org/common_errors.php

**Comment by Bjwebb** [comment]
We've done a lot of this work on error messages, including a common errors page in the most recent sprint, see https://github.com/OpenDataServices/cove/issues/367 etc. I think this issue can be closed, do reopen if we're missed anything.
