### ISSUE TITLE
From OCDS/360 there is no link back to CoVE "homepage"

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#222]
From http://dev.cove.opendataservices.coop/360/ there is no link back to http://dev.cove.opendataservices.coop/

We may want to resolve this?

**Comment by Bjwebb** [comment]
I think we don't want to add this. I think the end goal is for the 360 and ocds tools to sit under their own urls e.g. http://standard.open-contracting.org/validator

**Comment by stevieflow** [comment]
ok understood
