### ISSUE TITLE
Create About CoVE / Info pages

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#223]
Suggestion: the content about how long data is kept for / why convert data could be housed in a new page , which is a navigation link - rather than text at the footer of every page.

This may also help us in terms of the translation issue https://github.com/OpenDataServices/cove/issues/95 - but that is not the driver.

**Comment by Bjwebb** [comment]
I don't think this makes any difference for translation.

For the OCDS validator this text is now in a collapse-able box: http://standard.open-contracting.org/validator/
@stevieflow Does this solve your issue here? Should we look into doing the same thing for 360?

**Comment by stevieflow** [comment]
Yes, hadnt seen the collapsed box when posting this ticket, so I think this is dealt with - or we know how to handle it

**Comment by Bjwebb** [comment]
Yep, it's new. Just realised we're already doing this for 360 too http://cove.opendataservices.coop/360/ (which I had forgotten!).
