### ISSUE TITLE
Give warning message on badly encoded files.

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/cove#229]
I think for all files if they are not encoded in what seems like UTF-8 we should give a warning in the explore pages. 
We do support cp1252 and latin1 but we should recommend UTF-8 in all cases.  Excel only really does csv in cp1252 but libreoffice and google docs should be fine. I think a warning is still valid as we do have xlsx support for excel.

**Comment by Bjwebb** [comment]
Yes, I definitely support such a warning. Might be worth explicitly bringing this to people's attention though, once it's on the dev version.

**Comment by robredpath** [comment]
It looks like we do this, now.
