### ISSUE TITLE
Is json schema validator checking format values?

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/cove#234]
The [release-package schema](https://github.com/open-contracting/standard/blob/master/standard/schema/release-package-schema.json#L9) has a number of fields, such as ```uri``` which have a format parameter noting that they should be validated as URIs. 

Does the current validation process use the [format checker](https://python-jsonschema.readthedocs.org/en/latest/validate/#jsonschema.IValidator)? 

Flagging as one OCDS publisher is noting inconsistencies between their local validation and validation on CoVE...

**Comment by kindly** [comment]
We are only validating dates at the moment not uris.  #259 adds the support.

**Comment by Bjwebb** [comment]
We still need some tests for this, and then it merged in https://github.com/OpenDataServices/cove/pull/259

**Comment by Bjwebb** [comment]
We now validate URIs on the dev site http://dev.cove.opendataservices.coop/
