### ISSUE TITLE
Add open contracting website header/footer to OCDS validator

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#240]
As suggested in the document at https://github.com/OpenDataServices/cove/issues/200#issuecomment-164748148

Currently we're waiting on more detail about the open contracting site.

**Comment by Bjwebb** [comment]
Not sure what we want to be doing for this if we're not using the header/footer per se for the docs.

One option is to make OCDS Cove look like part of the docs site, which may make sense since it'll be on that subdomain.

**Comment by kindly** [comment]
We currently have new design where this is not nessesery
