### ISSUE TITLE
Investigate the seperation of flatfile and json validation

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/cove#246]
This relies on knowledge of how we expect flattentool to work.
We need to create a validationion schema for all the possible input spreadsheets.  This will most likely have to be dynamically generated for each spreadsheet.

**Comment by Bjwebb** [comment]
We've gone for a different approach for this based of having a sourcemap so we can get back to spraedsheet info from the JSON validation. https://github.com/OpenDataServices/cove/issues/356
