### ISSUE TITLE
Moving variables outside of blocktrans will cause problems for some languages

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#249]
I merged https://github.com/OpenDataServices/cove/pull/241 as it's the easiest way to get Spanish translations for now, and I think the changes there are fine for Spanish.

However, moving variables outside of the blocktrans may cause trouble for some languages: e.g.
https://github.com/OpenDataServices/cove/pull/241/files#diff-4b7e6fde07397056e485f0601e1327dfR12
```diff
-    <h2 class="heading-in-panel" ><small>{% blocktrans %}How to use the {{ application_name }}{% endblocktrans %}</small></h2>
+    <h2 class="heading-in-panel" ><small>{% blocktrans %}How to use the {% endblocktrans %}{{ application_name }}</small></h2>
```
In some languages the word order will be different, e.g. so that the applications name must be at the start or middle of that sentence.

(The reason we made this change originally was to get Transifex's google translate working, so we may want to see if we can fix that some other way).

**Comment by kindly** [comment]
Did some looking into this.  Basically can not get google translate to correctly ignore %(block)s.  So for the time being, while we only have machine translation I will keep it as it is.

**Comment by robredpath** [comment]
Closing - we'll revisit this when we need to add a language that the current solution doesn't work for.
