### ISSUE TITLE
360 - fields with underscore not read

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#260]
If an extra field is contained in a 360 dataset, and that includes a column header with a ``_`` , this is not read in via CoVE

We'd expect this to be declared as an Additional field

**Comment by Bjwebb** [comment]
This is due to how we're excluding OCDS's country codes. @kindly is looking into a fix.

**Comment by Bjwebb** [comment]
The plan is to remove the exclusion based on underscores. We'll want some sort of warning for OCDS that fields with language suffices that are in the schema will be flagged incorrectly.
