### ISSUE TITLE
Issues with unique versus total counts (Items and Documents)

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#263]
When a file containing multiple releases is validated, the total count of items and documents are shown. For clarity, could we also include the unique count of:
- documents based on id
- items based on id

By showing that we found 19 mentions of a document and 4 unique document ids, publishers can be check the release has been validated correctly.

A sample file is included [here](https://drive.google.com/a/ekoner.com/file/d/0ByPHIGlaBXq1Qk9WMkZrbzRjYVk/view?usp=sharing).

**Comment by ekoner** [comment]
@Bjwebb Any progress on this?

**Comment by Bjwebb** [comment]
I don't think so. @kindly probably has a better idea.

**Comment by jpmckinney** [comment]
I have a great deal of difficulty understanding how each of the numbers are calculated (using the linked file as input). For example, 8 releases have an (identical) `planning` field, and the number is 1. However, I think we first need to determine how frequently this section is referenced, before investing time in improving its clarity.

**Comment by robredpath** [comment]
The original requests in this issue have been moved to https://github.com/open-contracting/cove-ocds/issues/68 and https://github.com/open-contracting/cove-ocds/issues/69 (as they relate to two separate areas of the interface)

@jpmckinney 's comment has been moved to https://github.com/open-contracting/cove-ocds/issues/70
