### ISSUE TITLE
OCDS CoVE in two places

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#264]
Just noting we have

http://cove.opendataservices.coop/ocds/

(link to from http://cove.opendataservices.coop/)

and 

http://standard.open-contracting.org/validator/

Is there anything to redirect here?

**Comment by Bjwebb** [comment]
Yes, but not immediately.

**Comment by Bjwebb** [comment]
A simple approach to this would just be to have an apache redirect from http://cove.opendataservices.coop/ocds/ to http://standard.open-contracting.org/validator. The advantage of doing this is it's less confusing to have two "live ocds coves", both for users and for us trying to troubleshoot their problems. The redirect requires no additional configuration of Cove, and means the link on http://cove.opendataservices.coop/ will continue to work correctly.

**Comment by Bjwebb** [comment]
This redirect now exists.
