### ISSUE TITLE
360 - postcode field is a string

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#267]
Should a user enter a numeric code (as in a US zip code or a five-digit European post code) in a spreadsheet source file, software will often auto format that as a number.  

CoVE would then interpret that field as a number and provide a validation issue:

![number](https://cloud.githubusercontent.com/assets/1209944/12983992/b4de8a8c-d0e3-11e5-821e-099929f16958.png)

@Bjwebb @kindly this might be for https://github.com/OpenDataServices/flatten-tool ?

**Comment by Bjwebb** [comment]
Yes, I've created a flatten-tool issue for this: https://github.com/OpenDataServices/flatten-tool/issues/85

**Comment by Bjwebb** [comment]
@stevieflow Is it easy for you to check whether this is just xlsx or csv, or both?

**Comment by stevieflow** [comment]
I think it was xlsx

Sorry, it was with the Wolfson data, but they have since corrected it: http://www.wolfson.org.uk/about-us/grant-data/

**Comment by Bjwebb** [comment]
This is fixed in our latest flatten-tool work, not yet in master but accessible at http://flatten-tool-updates.dev.cove.opendataservices.coop/

@stevieflow Did I spot in planio that there's some new data with this problem? If so, could you test it against the above url.

**Comment by stevieflow** [comment]
Thanks @Bjwebb 

Think @ekoner will know what data to use to test this.... (otherwise, we could/should get some example invalid file(s) together)

**Comment by ekoner** [comment]
@Bjwebb Looks like it's worked on XLSX See http://flatten-tool-updates.dev.cove.opendataservices.coop/360/data/abad74ef-744e-4952-a031-7dbbe54b83d9 vs http://cove.opendataservices.coop/360/data/c316927d-dca1-433f-abbc-9f6a8f9b451c
