### ISSUE TITLE
Write an introduction for the README

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#3]
https://github.com/OpenDataServices/cove#introduction

**Comment by caprenter** [comment]
I think you might be best placed to write this @timgdavies , but bat it back to me if you like

**Comment by timgdavies** [comment]
Here is a first go at some text. Working offline, so not sure how well this
fits with the other existing documentation:

# CoVE: Convert Validate & Explore

The W3C [Data on the Web Best Practices](www.w3.org/TR/dwbp/) recommend
making open data available in a range of formats to meet the needs of
different users. Developers may want JSON, researchers might prefer a
spreadsheet format.

CoVE manages the process of converting between JSON, Excel and CSV formats
for structured data.

It presents key validations information during the process, and can be
configured to display information about the contents of a data file,
allowing users to further validate their data by checking the numbers and
information presented back to them matches that which they feel the file
should contain.

## Supported formats

CoVE currently supports conversion from:

* JSON to multi-tabbed Excel files
* Excel to JSON

It uses the [flatten-tool](https://github.com/OpenDataServices/flatten-tool)
for conversion.

If a JSON schema is supplied, CoVE can use either field names, or
user-friendly column titles.

Exploration views need to be developed customised to the type of data being
converted.



On Thursday, April 30, 2015, caprenter <notifications@github.com> wrote:

> I think you might be best placed to write this @timgdavies
> <https://github.com/timgdavies> , but bat it back to me if you like
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenDataServices/cove/issues/3#issuecomment-97736336>.
>


-- 


+44 (0)7834 856 303
@timdavies
http://www.timdavies.org.uk
