### ISSUE TITLE
Create sphinx docs

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#307]
I'm looking for somewhere to write up how Cove approaches error pages.

I'm thinking we should have a docs folder, and maybe use sphinx to compile it. This will be particularly useful for documenting Cove's functions when we make it usable as a library.

**Comment by Bjwebb** [comment]
See https://github.com/OpenDataServices/cove/tree/307-sphinx-docs

**Comment by caprenter** [comment]
I can see there is a docs folder, and the branch is no longer there that is referred to in your comment. Can this be closed?

**Comment by Bjwebb** [comment]
No, sphinx is not set up. On that branch I only got as far as creating that docs folder, which is now merged.

**Comment by Bjwebb** [comment]
I've now set sphinx up on a branch, and also got readthedocs to build it: http://cove.readthedocs.io/en/307-sphinx-docs/

Now that we've restructured cove as a library, we can have Sphinx pull out documentation for each of the functions http://cove.readthedocs.io/en/307-sphinx-docs/lib/
