### ISSUE TITLE
Title truncated on IE?

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#318]
We had a report that the full Open Contracting Partnership title does not show on someone's screen.
![img_20160324_101753](https://cloud.githubusercontent.com/assets/185467/14103125/6ccfaabe-f596-11e5-8526-2f3d0ce94fe5.jpg)

**Comment by Bjwebb** [comment]
Looks like we can get VMs of IE from https://dev.windows.com/en-us/microsoft-edge/tools/vms/linux/

**Comment by Bjwebb** [comment]
This should now be fixed on dev http://dev.cove.opendataservices.coop/ocds/
