### ISSUE TITLE
When files are too large for us to handle, offer to chunk or extract a selection

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#324]
From https://github.com/OpenDataServices/cove/issues/210#issuecomment-165219915

@timgdavies 
> Is there a way to detect large files on the client side and potentially
suggest chucking them / extracting a selection?
>
> This could be best in terms of UX  and I've seen libraries with good in
browser CSV handling for large files...

@bjwebb
>I don't think chunking/extraction client side is particularly worth the effort (and it wouldn't work for fetching urls). We should be able to take the same sort of approach server side (and/or rewrite more of our code to be streaming).

**Comment by robredpath** [comment]
Closing - it's only really big lottery that are affected by this, and we can deal with cases on an ad hoc basis for now. When it starts to hurt, we'll come up with something!
