### ISSUE TITLE
Check if we can validate the text form of excel dates

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#334]

**Comment by KDuerden** [comment]
This issue has reappeared - a file with planned start and end dates formatted yyyy-mm-dd as text which includes impossible dates but is passing CoVE tests. 
This threw up some issues when @drkane was using the data, so I'm assuming it could also cause problems with / fail loading into GrantNav.

**Comment by robredpath** [comment]
Moved to https://github.com/ThreeSixtyGiving/dataquality/issues/39
