### ISSUE TITLE
Nicer error messages for *new* 360Giving schema

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#335]
(For the changes in https://github.com/ThreeSixtyGiving/standard/pull/128/ )

**Comment by stevieflow** [comment]
I'd like to progress this in the 360Giving / GrantNav sprint

How best to proceed?

Have a list of current error messages?

I guess it's both having the messages, and then looking at how / where to display them - and also what actions the user might make in relation to them

**Comment by Bjwebb** [comment]
This is a different issue to the one Steven was commenting about.

**Comment by Bjwebb** [comment]
New issue at https://github.com/OpenDataServices/cove/issues/358 to cover Steven's issue.

**Comment by stevieflow** [comment]
This seems very old (pre-additional checkecs for example).  Suggest we close it @robredpath @Bjwebb

**Comment by Bjwebb** [comment]
This was about date changes to the schema, which we're currently looking at again.
