### ISSUE TITLE
360 CoVE doesnt "care" about duplicate IDs in spreadsheet format

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#336]
Follow on from https://github.com/OpenDataServices/cove/issues/159

We think CoVE doesnt pick up on dupe grant IDs, as there  are other processes going on (eg merge/convert to JSON)

This might need some further thought

The feedback to the user may be a tad misleading , as in:

Grants: 2 
Grant IDs: 2 
Unique Grant IDs: 2 

(from attached file - with 3 grant records)
[test.xlsx](https://github.com/OpenDataServices/cove/files/232104/test.xlsx)

**Comment by robredpath** [comment]
Closing - I don't think we see this "in the wild" and other functions support publishers
