### ISSUE TITLE
No timezone displayed on datetime in key facts box

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#339]
For 360Giving we may want to think about using the UK's timezone, but for OCDS we probably need to go for UTC. Another option is trying to detect the users timezone, but I don't think that's possible without javascript https://github.com/adamcharnock/django-tz-detect

**Comment by caprenter** [comment]
Shouldn't we just be displaying what is reported in the data?
Is flatten tool getting involved here and being more opinionated than it needs to be?

(I'm thinking that if someone reports 2016-01-23T10:00:00Z, or 2016-01-23T10:00:00+03:00, then that is what should displayed)

I can't help thinking tho, that I've maybe missed the point here!

**Comment by Bjwebb** [comment]
This isn't from the data, it's the date/time the file was uploaded to Cove.
