### ISSUE TITLE
As a user / potential user of Cove/flatten-tool I want to know what encodings are supported

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#344]
Can we add on the OCDS validator page which encodings we support?

Related to #220

**Comment by Bjwebb** [comment]
Yes, we should 

To clarify in relation to that specific issue, the encodings we support are different for CSV and JSON.

For CSV we support UTF-8 and Windows-1252.

For JSON we suport UTF-8. There's also an issue about the possiblity of adding support for UTF-16 and UTF-32 https://github.com/OpenDataServices/cove/issues/79

Even if we don't require it, we should be strongly recommending that people publish UTF-8 JSON, as it's better for most data consumers https://tools.ietf.org/html/rfc7159#section-8.1 - might be good to add something to our implementation guidance http://standard.open-contracting.org/latest/en/implementation/serialization/#json

**Comment by Bjwebb** [comment]
We should also document this on the 360Giving validator page, and in the Cove and flatten-tool READMEs.

**Comment by ekoner** [comment]
@Bjwebb Can this be closed?

**Comment by robredpath** [comment]
#344 covers the title of the issue. How important is it that the implementation guidance for OCDS states that we strongly recommend UTF-8?

**Comment by Bjwebb** [comment]
Yes, I think this can now be closed. The change in https://github.com/OpenDataServices/cove/commit/394ce405bf6daaec15edab562e522e1b961d7b2c is now deployed to https://dataquality.threesixtygiving.org/ and http://dev.cove.opendataservices.coop/ocds/, so useful @ekoner if you could check the text there about encodings is what you're expecting. 

UTF-8 for OCDS was taken forward in https://github.com/open-contracting/standard/issues/323 which has riased some additional Cove tasks at https://github.com/OpenDataServices/cove/issues/535
