### ISSUE TITLE
As a developer, I should be able to run CoVE's tests in parallel where appropriate

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#347]
Running cove's tests on my laptop (in my VM!) takes ~12mins. TravisCI takes 8 mins to run them. If we can get that down, it becomes quicker and easier to test multiple iterations.

**Comment by robredpath** [comment]
@kindly @Bjwebb @caprenter Any objection to using pytest-xdist (https://pytest.org/latest/xdist.html) ? Tried it out on my dual-core VM and it halved execution time. All the tests passed. I had a read of the tests and couldn't see any that would have issues running in parallel, but you guys know them better than me.

**Comment by Bjwebb** [comment]
pytest-xdist looks like a sensible choice.

The tests *should* each be self contained such that running in parallel would be fine.

I'd be happy to see this enabled.

**Comment by robredpath** [comment]
I've given it a try locally and it's great - halves execution time with just -n2. How do I add this - there's two requirements.txts, and the .in files?

**Comment by Bjwebb** [comment]
Yes, how we do requirements needs documenting in the README. I'll look into doing this today.

**Comment by Bjwebb** [comment]
I've updated the script, and added some info to the README in https://github.com/OpenDataServices/cove/commit/f87c8f13eb84cb3a81086463235b43bda7d0dfe1

Hopefully that makes it a bit clearer how to do what you want. In this case `requirements_dev.in`is the one to add for, as we don't run the tests on the live deployed copy.
