### ISSUE TITLE
When I upload a file to CoVE, I want some feedback on my Recipient Org identifiers

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#349]
(this may or may not be unique to 360)

When I submit data to CoVE, I'd like my organisation identifiers to be "checked".  By this, I mean:

- ``Recipient Org: Identifier`` is this populated?  If blank - please tell me (which I think is part of schema validation anyway)

- ``Recipient Org: Identifier`` is this prefix present on the IATI Org Agency codelist: http://iatistandard.org/202/codelists/OrganisationRegistrationAgency/ ? 

- ``Recipient Org: Identifier`` - is the org number "valid" ? *

* Realistically, we probably want to only focus on England, Wales, Scotland and NI companies and charities, for 360Giving

NB: In 360Giving there are two additional columns for company and charity numbers.  We could dedicate resource to checking these numbers too, but I don't think so.  This can be especially complex as there is no means to declare if this number is on the England & Wales or Scotland register of charities, for example - whereby at least via ``Recipient Org: Identifier`` there are documented steps for publishers to take

**Comment by robredpath** [comment]
- regex check the field
- no external lookups
- feed back on if some grants are missing the recipient org block at all 
- check prefix against IATI org codelist

**Comment by robredpath** [comment]
- report on unique prefixes, how many of each type, etc

**Comment by Bjwebb** [comment]
Assinging me first of all, as I have knowledge about the IATI codelists, and I think this might relate to https://github.com/OpenDataServices/cove/issues/361 too.

**Comment by stevieflow** [comment]
@Bjwebb useful issue/content from @ekoner  at https://github.com/OpenDataServices/grantnav/issues/19

**Comment by Bjwebb** [comment]
@stevieflow Thanks for the link. Just to clarify, we're not thinking of performing lookups against external registers in this sprint, so I don't think the content of that issue is relevant yet.

**Comment by Bjwebb** [comment]
I'm planning on implementing this in `get_grants_aggregates` in https://github.com/OpenDataServices/cove/blob/master/cove/lib/threesixtygiving.py and then make some additions to the template along the lines of the current "Key field information" box.

**Comment by Bjwebb** [comment]
> - ``Recipient Org: Identifier`` is this populated?  If blank - please tell me (which I think is part of schema validation anyway)

Yes, this is part of schema validation. There was a bug where this didn't fail if there was no recipient org information at all, but this is now fixed https://github.com/OpenDataServices/cove/issues/360

**Comment by Bjwebb** [comment]
Some work on this in https://github.com/OpenDataServices/cove/commit/35b381d97dba6035859bc73e9961aa3ee568b262

We need to also allow the 360G prefix, but we may want a count of these too (as they're less preferable to other kinds of ID).
