### ISSUE TITLE
As a user of 360 CoVE , I'd like to know if my data can be used in GrantNav

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#354]
Ambiguous - but would be interested in a secondary check/report on data loaded in CoVE, to declare whether (or which records) could be fully used in GrantNav.

To do this, we would need to see evidence of certain fields - which I think would be:
- ID
- Title
- Description
- Amount Awarded
- Date Awarded
- Recipient Org: Identifier
- Recipient Org: Name
- Funding Org: Name
- Funding Org: Identifier

But - this evidence would also need to be "valid" 

And then - more problematic - 

Recipent Org: Postcode
and/or , some kind of location field we can use 

The issue with this is that the threshold for GrantNav could change in the future, but I'd be interested to explore this - with CoVE providing a more opinionated view of the data, in terms of a data use

I don't know if this means anything, but the IATI Rulesets might be worth a look: https://github.com/IATI/IATI-Rulesets.  @Bjwebb and @caprenter may well think otherwise

**Comment by stevieflow** [comment]
What do we need for GrantNav that is above and beyond schema validation?

We value when we have a postcode/location, and an organisation identifier - but I struggle to see if this a clear enough user story right now

**Comment by robredpath** [comment]
Look into why these aren't schema changes

**Comment by robredpath** [comment]
Recipient Org and Funding Org are now required in the schema (see https://github.com/ThreeSixtyGiving/standard/pull/147 )  

@stevieflow can you revisit the description of this and see if you can refine it further?

**Comment by stevieflow** [comment]
@robredpath thanks.   I think org stuff is clear - it's what we would do around location data that is less so, it seems

**Comment by robredpath** [comment]
@stevieflow Yeah, I don't have a great sense of the issues around that yet, other than the difference in location of organisation and work, and granularity considerations. 

I think it'll be interesting to hear from users what their requirements around location are, or if it even comes up at the user workshops (I'd be amazed if it didn't!).

**Comment by robredpath** [comment]
Closing - we address data quality questions in several ways
