### ISSUE TITLE
When I upload a spreadsheet, I want clear guidance on which cells and column headings I need to fix, to be valid (against the 360Giving schema)

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#356]

**Comment by stevieflow** [comment]
Columns , rows --> cells

**Comment by stevieflow** [comment]
(these are tests against schema validation)

**Comment by robredpath** [comment]
Scope for this sprint: Add all the rest of the fields that aren't covered yet, check that it works with both OCDS and 360. Then, either start improving test coverage or edge case usage.

**Comment by robredpath** [comment]
James will be working on this this sprint

**Comment by robredpath** [comment]
Need to be aware of how this works with large data sets, eg big lottery

**Comment by Bjwebb** [comment]
Specifically, it would be great if someone can record what the max memory footprint is for Cove processing the big lottery data before and after these changes. Would be interested to know what tools people think are best for this too, as I didn't get any further than manually watching the numbers in top last time I was looking at this.
