### ISSUE TITLE
 As a user of CoVE I'd like clearer error messages when my data doesnt meet 360Giving schema validation

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#358]
From https://github.com/OpenDataServices/cove/issues/335#issuecomment-219383499 @stevieflow said:

> I'd like to progress this in the 360Giving / GrantNav sprint
> 
> How best to proceed?
> 
> Have a list of current error messages?
>
> I guess it's both having the messages, and then looking at how / where to display them - and also what actions the user might make in relation to them

**Comment by robredpath** [comment]
- give the users much more narrative about what we've done and explain what the warnings that they're seeing 
- Split up the page into convert / validate / explore sections

**Comment by robredpath** [comment]
- link out to docs as to why we do what we do

**Comment by robredpath** [comment]
Related to #351
