### ISSUE TITLE
Investigate why tests are slow

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#359]

**Comment by robredpath** [comment]
Spent a couple of hours looking into this, and I don't think there's an issue - we just test a lot of stuff, including quite a lot of conversions, which are important for an app that does a lot of converting, and it looks like they're the tests which take the time.  Specifically, if I remove test_URL_input() from the tests, the execution time drops by over 50%. 

Most of the rest of the time seems to be consumed by the browser itself; even though it's quite a simple page, rendering takes clock cycles. 

If we're able to make the conversion process quicker / more efficient then it'll make tests quicker, but I think that otherwise, this app is slower than others might be because of the weight of the processing that it's doing. I quickly looked at if it would be possible to make the sample data any smaller, but I doubt it - none of the input files are particularly big apart from samplerubbish.json, and removing that test didn't have an appreciable impact on execution time.

**Comment by caprenter** [comment]
Does it help or is there a way to split tests out into groups?

I know there are options for pytest to use e.g. -k to run some tests, -x to run to first failure and so on.

But maybe splitting things into interface, conversion tests,or whatever would make life easier for development?

**Comment by robredpath** [comment]
#347 speeds up test execution dramatically by parallelising tests, and I'll document both -n for that and -x, just in case people didn't know about those switches. 

We could definitely also split out the selenium tests into multiple files so that we can run just the relevant sections.

**Comment by Bjwebb** [comment]
Splitting into multiple files is a good idea.

Another way of splitting up the tests is with custom markers https://pytest.org/latest/example/markers.html#marking-test-functions-and-selecting-them-for-a-run. I think the big use case of this would be if we wanted multiple overlapping categories of tests.

**Comment by robredpath** [comment]
Added #371 so we can separate out tests in the future.

**Comment by caprenter** [comment]
Is there a problem here: https://github.com/OpenDataServices/cove/blob/master/fts/tests.py#L255

The function `check_url_input_result_page` gets called again 2 lines later so runs through all those data uploads, conversions, and text matches a second time, with the same data, but just pulled from the repos on the web - I think to test the ?source_url GET option.

Am I right? If so does this test need to be run so many times on the same data?

**Comment by caprenter** [comment]
I think we agreed that there we probably don't need to re-run all of those tests again in a discussion on Friday. I think @kindly said he might sort this out so assigning to him,
