### ISSUE TITLE
RemovedInDjango19Warning

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#36]
When I spin up the server locally I see:

lib/python3.4/site-packages/django/templatetags/future.py:25: RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
  RemovedInDjango19Warning)

**Comment by Bjwebb** [comment]
This is due to the templates in django-debug-toolbar, and has been fixed on their master branch https://github.com/django-debug-toolbar/django-debug-toolbar/issues/706 - this will be fixed for us once they make a new release, and we upgrade, which should be before Django 1.9 comes out.

**Comment by Bjwebb** [comment]
I no longer see this warning, presumably because we've upgraded django-debug-toolbar
