### ISSUE TITLE
Investigate why Recipient and Funding orgs aren't required

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#360]

**Comment by robredpath** [comment]
I've emailed @timgdavies to ask this question

**Comment by timgdavies** [comment]
This looks to me like a schema bug. 

The fields within ```recipientOrganisation``` and ```fundingOrganisation``` for ```name``` and ```id``` are marked as required, but not the objects themselves. 

This means that in the [flattened tables](http://www.threesixtygiving.org/standard/reference/#toc-grants-sheet that: 

* Recipient Org:Name
* Recipient Org:Identifier
* Funding Org:Name
* Funding Org:Identifier

are showing as required, but when validating as JSON they are not being required as their parents are not required.

I would suggest updating the schema to reflect the validation behaviour implied by the docs for the single table version.

**Comment by caprenter** [comment]
We think we can just go ahead and make this change to the schema without upsetting anyone, so we're going to do it.

@kindly will make a pull request on the schema change for this

**Comment by robredpath** [comment]
This is getting resolved in https://github.com/ThreeSixtyGiving/standard/pull/147
