### ISSUE TITLE
Propose a better audit / non-schema check / warnings mechanism

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#361]

**Comment by Bjwebb** [comment]
I'm going to write up a bit about what we did that was similar for IATI, and what the learnings from that were.

**Comment by robredpath** [comment]
I'm reviewing the reports that @stevieflow has made. Would it be possible to parse the errors into some kind of data structure so that we could do some helpful analysis on them before presenting them to the user? 

In particular, I'm looking at #369 , where we display an error for every field as a result of one non-unique ID

**Comment by Bjwebb** [comment]
The error reports in that case are due to Python warnings raised by flatten-tool. We raise these warnings ourselves, and the warnings are Python objects; so, we can add whatever extra data we want to those objects and aggregate it how we want in Cove.

**Comment by robredpath** [comment]
Yeah, I've confounded the issue here. Sorry! Ignore my comment, that's actually a different thing to think about entirely.

**Comment by robredpath** [comment]
Yeah, to clarify: this is for things like the org ID regex checks that aren't covered by the schema but are important for us to consider data to be good quality.

**Comment by Bjwebb** [comment]
I've written some words in https://docs.google.com/document/d/1xb4-n5kc-H5GEI_vAlPibtInl5wBnjRqNjeRl7DbT6g/edit#
Will discuss with @robredpath and @kindly tomorrow.

**Comment by Bjwebb** [comment]
This will be taken forward in https://github.com/OpenDataServices/cove/issues/507
