### ISSUE TITLE
Gather error messages that cause users particular pain

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#362]

**Comment by stevieflow** [comment]
Started through some tickets - and an open doc: https://docs.google.com/document/d/1RYX2CmJ9ktQbgFMsFCK541z5CgQxFDfHoKq10n-15oE/edit?usp=sharing

**Comment by robredpath** [comment]
@stevieflow are you happy for this to be closed?

**Comment by stevieflow** [comment]
@robredpath I think so
