### ISSUE TITLE
URI testing (360) in validation - strip blank space at start and end of URL?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#366]
I'm looking at validation errors for a publisher: 

http://dev.cove.opendataservices.coop/360/data/94b23c3d-dc2c-416a-8683-f9481564cb24

I can see that in many cases the URI isnt valid, as it is badly formatted or contains two in one cell:

> 'http://eastsideprojects.org / extraspecialpeople.org' is not a 'uri'
> 'http://magdalenegroup.org and jigsawprogramme.org' is not a 'uri'

In other cases, I had to look closely , as it seemed that a trailing space is in the data, which is then judged as invalid:

> 'http://baobabsurvivors.org ' is not a 'uri'
> 'http://ae-sop.org ' is not a 'uri'

@Bjwebb @kindly is that a correct observation?  Would we want to do anything in these instances?

**Comment by robredpath** [comment]
This is probably a good candidate for inclusion in #367

**Comment by caprenter** [comment]
I would argue that people should get their data right.

It is possible in most languages to 'trim' strings to remove spaces from the front/end of strings, but this would 

- mask the problem
- mean that all other data users would have to take the same approach (when they are told they should be expecting a valid uri)

I think Rob is suggesting this could be a 'Common validation problem' that gets written up somewhere.

**Comment by robredpath** [comment]
I agree - a field with a trailing space isn't a valid URI and we shouldn't accept it as one, especially as that rule (which will probably be undocumented) would mean that every other application using that data would have to strip trailing spaces. 

@caprenter is right, I think this should be written up somewhere and linked to from the 'is not a uri' error message

**Comment by stevieflow** [comment]
Thanks

I hadn't thought of this, which helps confirm we should not fix:

> especially as that rule (which will probably be undocumented) would mean that every other application using that data would have to strip trailing spaces.

@caprenter perhaps in https://github.com/OpenDataServices/cove/issues/367 we might also want to explore what impact errors might have for data users (eg: your link wont be linkable)

What I am interested in with this specific issue is to how the trailing space is added by the publisher.  Is it from a system?  Is it added during typing (sometimes a trailing space helps people see that the link is  "active")?  Therefore @robredpath we can remove this from the list for this sprint, but somehow push it to a user research task?

**Comment by robredpath** [comment]
@stevieflow I've added #373 to the backlog for us to work in the future, and moved this to 'Done' as we've done all the work on it that we're going to.
