### ISSUE TITLE
As a CoVE user, I want validation errors to be meaningful to me and provide links to other pages to help me fix my data

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#367]
Is it feasible/possible in CoVE to link an error message to a page (or... even ..a .. tooltip) that can give some guidance ?

So:

>  is not a 'uri'

could link to some words about what a valid uri is, etc

Would be good to know this - as it may even negate any thoughts about "rewriting" error messages from the schema

Related to https://github.com/OpenDataServices/cove/issues/362

**Comment by caprenter** [comment]
We think it's possible to re-write the error messages.

However - deciding what to write or where to point to may be problematic - e.g info about what a URI is could be more confusing:

- https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
- https://tools.ietf.org/html/rfc3986

Also, where it is used in the 360Schema - for example, we describe what we expect in different ways already e.g.:

- Grant Programme:URL	A web link to more details of this grant programme.
- URL	A URL (Web Address) where further information about this grant can be found. This could point to the website of the recipient organisation, or might link to further details on the funders website.
- Recipient Org:Web Address	A web address for the OrganisationGrant Programme:URL	A web link to more details of this grant programme.

We can't currently link directly to an individual entry in a table on http://www.threesixtygiving.org/standard/reference/
but we can link directly the page, or to the top of a table - but one might be easier to do than the other

**Comment by robredpath** [comment]
Could we make the 'errors' section of the output have contextual help for each type of error? I'm not sure we'd want to get straight into the RFC definition of a URI

**Comment by stevieflow** [comment]
In discussion with @caprenter we think a "Common Errors" page on CoVE could help - we can link to parts of this page and then describe and define each error.

I think @caprenter can clarify more - but that seems to be the approach - which I agree with

**Comment by robredpath** [comment]
Just to note from our conversation in #366 - we should ensure that we explain something of why it's important (eg two URLs can't be displayed by systems that are expecting one) and solutions (eg put extra URLs in an extra field) where appropriate
