### ISSUE TITLE
Key Facts - provide a name for the schema link?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#368]
Minor observation

The key facts box includes:

> This file failed validation against https://raw.githubusercontent.com/ThreeSixtyGiving/standard/master/schema/360-giving-package-schema.json.

Can we elaborate on this link, using descriptive text?  And - could we also point to the documentation describing the schema?

Additionally: we may want to also provide some text to describe what it means to fail schema validation, although no biggie

(linked to https://github.com/OpenDataServices/cove/issues/358)

**Comment by robredpath** [comment]
I think this falls under what @caprenter was volunteering to do this morning, assigning to him and adding to Next Sprint

**Comment by Bjwebb** [comment]
I think this was done in https://github.com/OpenDataServices/cove/commit/60f9a898a53f7de31442e02f4117fdbfee24a8db
