### ISSUE TITLE
Key Facts - "Data downloaded from ... "

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#370]
In Key Facts - the link to the source data is not a link.  Should it be?

http://dev.cove.opendataservices.coop/360/data/6087f628-5c70-4d37-8653-6cf11571c633

> Data downloaded from http://www.greenham-common-trust.co.uk/sites/default/files/pdf/360Data_GCT_Reactive_Grants_Nov_2015_Final.xlsx on May 24, 2016, 4:27 p.m.

**Comment by stevieflow** [comment]
(NB: it is linked in the above snippet, but not in CoVE)

https://github.com/OpenDataServices/cove/issues/362

**Comment by stevieflow** [comment]
Also/however - I havent tested this when data is added via copy and paste and/or upload.

**Comment by robredpath** [comment]
That's an interesting question. There's a download link at the top of the page for the source data. I think this needs to feed into our conversation about how we lay out the output and how we expose more of what we're doing. I can kinda see a future where we get the app to report as it goes: 

... downloading data from <url> ..
... converting ... 
... no errors on conversion, validating ...
... data is invalid, here's the errors, links, key facts ...


...in which case it would make less sense to make it a link.

**Comment by stevieflow** [comment]
Thanks @robredpath - I think my reporting this issue was just the mental process of " that *looks* like a link,,, why can't I click it?!"....

**Comment by robredpath** [comment]
Yeah, definitely - I think once we've rearranged the page we should revisit this and see if it still looks like it should be clickable

**Comment by caprenter** [comment]
This is how the output looks if you upload a file:
http://dev.cove.opendataservices.coop/360/data/7de7953c-01af-4ae0-a4c1-00c58b583c13

and if you pasted it:
http://dev.cove.opendataservices.coop/360/data/d72e2d1d-7a71-4925-af42-7329bc6f7272

**Comment by stevieflow** [comment]
thanks @caprenter for the extra URLs

Is the entry route for data "captured" during the process - enough to tailor the message:

- Data added by link (URL) on X date
- Data pasted on X date
- Date uploaded on X date

**Comment by caprenter** [comment]
See also: http://dev.cove.opendataservices.coop/360/stats

**Comment by stevieflow** [comment]
I dont think this is an issue anymore - in 360 (new) CoVE ? @robredpath

**Comment by robredpath** [comment]
Correct @stevieflow , the URL is now a link
