### ISSUE TITLE
Error message when an .xlsx doesnt have a "grants" sheet

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#377]
( I had thought this wasnt an issue anymore, but this isnt the focus of this issue):

> We think you tried to supply a spreadsheet, but we failed to convert it to JSON.

> Error message: ValueError('Main sheet "grants" not found in workbook.',)

> If you think this is a bug, you can file an issue publicly on GitHub or get in touch via email, referencing this error as 0e586c7073094513b5db3bc9ccbd4153.

This error message / feedback can be understood - but I wonder if there is scope to improve it

But first of all, I'd like to check my assumption: this message is generic, and shown whenever a file is uploaded with a main sheet not entitled 'grants' ?

**Comment by Bjwebb** [comment]
https://github.com/OpenDataServices/flatten-tool/issues/96 is the underlying issue here, which I think we should be looking to fix soon.

**Comment by Bjwebb** [comment]
The fix for this is now deployed http://dev.cove.opendataservices.coop/360/
