### ISSUE TITLE
Prioritise/group 'required property' errors?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#378]
Ive been working on a file from a publisher, pre-publication.  This has many grants in - and lots of errors.   I've made a anon sample (attached) from this data to take a look at something:

http://dev.cove.opendataservices.coop/360/data/ca0eb226-2512-4b32-9281-5320555a1cbd

The errors are:

> 'awardDate' is a required property
> 'id' is a required property
> 'name' is a required property
> '18/04/2016' is not a 'date-time'
> 'currency' is a required property
> 'description' is a required property

Im not sure where / how the order of these messages is determined (I guess the schema?).  As a user, I think I'd like to understand / see 'required property' initially - https://github.com/OpenDataServices/cove/issues/367 - could there be a chance to group together these (in a box) messages, and provide some generic text with them.  

NB: I understand that 'required property' is just as "severe" as 'not a 'date'time' in terms of schema validation - but think an attempt to group similar messages could be worth investigation.

The example I cant illustrate is with the actual data, whereby lots and lots of date issues are presented separately - meaning that it is very difficult to actually see the required property messages - but think issues such as https://github.com/OpenDataServices/cove/issues/358 are looking into better representation of the messages

[test.xlsx](https://github.com/OpenDataServices/cove/files/282771/test.xlsx)

**Comment by robredpath** [comment]
We do this now, in 360Giving CoVE.
