### ISSUE TITLE
Other version of the OCDS?

### ISSUE THREAD

**Issue by gabelula** [OpenDataServices/cove#381]
Hi, 

Is there any way to run cove with other version of OCDS (other than http://standard.open-contracting.org/schema/1__0__1/release-package-schema.json) ?

**Comment by caprenter** [comment]
if you deploy your own version the schema details used can be altered in the config file:
https://github.com/OpenDataServices/cove/blob/master/cove/settings.py#L74
and
https://github.com/OpenDataServices/cove/blob/master/cove/settings.py#L79

e.g. you could substitue in: http://standard.open-contracting.org/1.0-dev/en/release-schema.json (from http://standard.open-contracting.org/1.0-dev/en/schema/release/)

but we don't currently have anything deployed that uses anything other than those versions. I think tho, that as upgrades and such happen that it's likely that we would be deploying versions to check the changes. It might be worth a chat to see what you are after.

**Comment by gabelula** [comment]
I'm validating the CDMX's contracts and they are still working on 1.0 version of OCDS. I will deploy it locally. Thanks.

**Comment by Bjwebb** [comment]
Part of the reason that our deployed copy of Cove only validates against 1.0.1 is we think that releases that validate against 1.0.0 should also validate against 1.0.1. If you've found that this isn't the case, then please let us know what's different, as it may be a bug.
