### ISSUE TITLE
Share these results

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#39]
Once a file has been successfully accepted and converted, the 'explore' page has a unique URL, allowing for that page to be shared with others.

We could make this a feature of the 'explore' page.

Note also that the page may cease to exists (e.g. if and when a file is deleted)
See: https://github.com/OpenDataServices/cove/issues/38

**Comment by Bjwebb** [comment]
@caprenter Is this issue fixed now, or is there a further task of improving the UI of this? e.g. to include a text box with the URL of the current page, possibly with a copy button.

**Comment by caprenter** [comment]
I think this is still a feature request. Your 'e.g.' sounds about right to me.

**Comment by kindly** [comment]
Can not find a way to do a copy button without flash.  Looked around quite a bit and there are suggestions that it is possible sometimes without flash, but can not find a drop in library for this.
The best flash using library appears to be http://zeroclipboard.org/.

Personally do not think its worth added this as dependency.  A box which has a copy of the url in it should be sufficient as most people can copy and paste.

**Comment by Bjwebb** [comment]
Thanks for looking into this. I'm not quite sure whether to got the zeroclipboard route, or to avoid it as you suggest. There is a cdn for it at http://zeroclipboard.org/ , but that still leaves the overhead on the client side.

I think it's certainly the case that  simply having a box to manually copy and paste would be a good next step, and from there we can decide whether a copy button makes sense.
