### ISSUE TITLE
From CoVE results it is not clear how I navigate back from Common Errors

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#390]
When I click in the link for "Invalid 'uri' found" in my results, I go to:

http://dev.cove.opendataservices.coop/360/common_errors#uri

From this page, it is not clear how I go back to my results, save for clicking the back button.  The back button works, but it feels risky to do so (I wonder if my results have been lost)....

**Comment by kindly** [comment]
I was wondering if we should just open common errors in a new tab when they are clicked on?  I was going to do that but forgot.

**Comment by caprenter** [comment]
Big believer in let users decide if they want a new tab or not (don't break the back button)

The back button works for everyone. 

Did the trepidation of clicking the back button give you a thrill when you found that what you back to was still there - what lovely expected behaviour!

**Comment by robredpath** [comment]
I had assumed that it would open in a tab - it feels pretty scary to see my results disappear when I click on a link, not knowing if I'm going to have to go back to the start and re-upload my file. Moving to a new page makes sense for a more linear user journey, but in this case we can pretty much guarantee that users will want to refer to their search results AND the documentation repeatedly, which is generally the argument for opening a new tab. 

How about a warning that it opens a new tab? Would that satisfy @caprenter's principles?

**Comment by caprenter** [comment]
Moving to a new tab does not make sense make for many users. All accessibility guidance is "let the user decide". The back button works. Results are still there. 

What if I want it to open in the same tab or don't know what a new tab is?

**Comment by stevieflow** [comment]
Sorry - by new "tab" I meant tab within the application (as with the IATI validator) rather than browser tab.  Sorry - should have clarified

**Comment by robredpath** [comment]
Closing - in general we're moving towards inline/contextual help and we have separate publisher guidance now as well
