### ISSUE TITLE
Conversion warnings for JSON > spreadsheet

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#394]
From this

http://dev.cove.opendataservices.coop/360/data/4231d325-0099-4782-9659-40ae97a77556

I have an "invalid" file, bu some JSON:

http://dev.cove.opendataservices.coop/media/4231d325-0099-4782-9659-40ae97a77556//unflattened.json

From the above link I just select all > copy > New file > paste - and get:

http://dev.cove.opendataservices.coop/360/data/fc3f1d4a-83d2-4c08-bc3d-a5a37df0ad80

This also includes a "Convert to spreadsheet" button - which I click

This is all great

On getting to the conversion I am then presented with some " Conversion Warnings (titles)" :

> In order to validate your data we need to convert it. During that conversion we found the following issues:
> 
>    Field applicationTransaction does not have a title, skipping it and all its children.
>    Field commitmentTransaction does not have a title, skipping it and all its children.
>    Field disbursementTransaction does not have a title, skipping it and all its children.

I'm sure these warnings are logic within the schema and the actions I've taken, but I wanted to ask where they come from - I have two files that are now converted from JSON:

> Excel Spreadsheet (.xlsx) (Converted from Original) 567.2 KB
> Excel Spreadsheet (.xlsx) with titles (Converted from Original) 567.8 KB 

Are the above warnings particular to one of these conversions?

Interesting stuff - / not urgent

**Comment by Bjwebb** [comment]
These are warnings about how we handle the 360Giving  schema for flattening. You'll get these warnings when flattening any 360Giving file. The best fix here is to update the 360Giving schema, but I think we're not clear on how we want transactions to work going forward, see https://github.com/ThreeSixtyGiving/standard/issues/123 for some context.

**Comment by stevieflow** [comment]
@bjwebb thanks.  Maybe I'm wrong in my understanding, but I didnt see these conversion warnings in the initial file/report (xlsx > JSON):

http://dev.cove.opendataservices.coop/360/data/4231d325-0099-4782-9659-40ae97a77556

> You'll get these warnings when flattening any 360Giving file.

Should I have seen these warnings initially?

**Comment by Bjwebb** [comment]
No. Sorry for being a bit unclear, by flattening I mean specifically JSON to CSV.

**Comment by Bjwebb** [comment]
These warnings are no longer displayed to users.
