### ISSUE TITLE
There are 2 duplicate grant IDs in this package.

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#398]
This message does not necessarily tell you why this might be a problem.

It is seen in the 'At a glance section' of Headlines box.

It could link through to the common errors.

I think it is only seen on JSON files, not spreadsheets
There are 2 duplicate grant IDs in this package.

Recreate with this fixture file: https://github.com/OpenDataServices/cove/blob/master/cove/fixtures/WellcomeTrust-grants_fixed_2_grants.json

**Comment by stevieflow** [comment]
Is this still relevant @Bjwebb @robredpath ?

**Comment by Bjwebb** [comment]
No, this text doesn't appear any more.
