### ISSUE TITLE
Handle _language field missing warnings as special cases

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#402]

**Comment by Bjwebb** [comment]
I've merged https://github.com/OpenDataServices/cove/pull/452 because I think it moves us forward from where we are now.

However, I am concerned about that if someone mispells e.g. `title_es` as `tile_es` that we won't flag this anywhere.

**Comment by Bjwebb** [comment]
Bumping backwards to "Next Quarter" as this may be important to do, or may become less relevant depending on what's in the upgrade wrt. to language (particularly if we have breaking changes).

**Comment by Bjwebb** [comment]
We're not changing language approach in 1.1, so we should look at this issue again.

**Comment by jpmckinney** [comment]
Add "bug" tag?

**Comment by robredpath** [comment]
@jpmckinney I'm not sure that this is clearly a bug (although it's obviously behaviour that we want to change). 

There could be some additional functionality to build here that's far easier now that we're a couple of years further on. I'll add it to the list.

**Comment by jpmckinney** [comment]
I think it's a bug in that it fails to warn about fields it should warn about. I give an example in https://github.com/OpenDataServices/cove/issues/679#issuecomment-338310525

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Detect and warn about additional fields with _ in them](https://trello.com/c/t05nSWx7/47-detect-and-warn-about-additional-fields-with-in-them)

**Comment by robredpath** [comment]
Moved to https://github.com/open-contracting/cove-ocds/issues/74
