### ISSUE TITLE
Ttpo: "This file uses 1 additional fieldot used in the standard."

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#412]
When a file uses additional fields the Headlines box states:

> This file uses 1 additional fieldot used in the standard.

Typo / spacing @caprenter ?

**Comment by caprenter** [comment]
There is a fix for this in this pull request: https://github.com/OpenDataServices/cove/pull/410/files#diff-8cab40b772deabc59e6641c7b21b2af3R67
