### ISSUE TITLE
Provide a link to the 360 Common Errors page

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#414]
Linked to, but not about https://github.com/OpenDataServices/cove/issues/390

At http://dev.cove.opendataservices.coop/360/ I cant access a link to the common errors page.  Could one be added?

**Comment by caprenter** [comment]
There is a fix in https://github.com/OpenDataServices/cove/commit/26a31dad71b4051eb425f7ccae9ee08bfefdca3d
it's not deployed yet tho

**Comment by Bjwebb** [comment]
This is now deployed http://dev.cove.opendataservices.coop/360/
