### ISSUE TITLE
Split out Key field info and org id info - two boxes

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#423]
I really appreciate the insight into org ids that CoVE now gives me (which is also linked from the Headlines box)

![keyfieldinfo](https://cloud.githubusercontent.com/assets/1209944/16009579/46b11906-3175-11e6-97f0-ff2185760a48.png)

I would to propose that we can segment this info into two boxes:

Key field info - first two columns

Organisation ID info - last column

We can provide contextual (static) intro text too - I can draft this if we go ahead

I think this change will help provide clearer information and context to users

**Comment by Bjwebb** [comment]
This has been superseded by our work this sprint https://github.com/OpenDataServices/cove/issues/507 https://github.com/OpenDataServices/cove/issues/516
