### ISSUE TITLE
Merge strategies - validation and explanation

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#434]
http://standard.open-contracting.org/latest/en/schema/merging/

**Comment by robredpath** [comment]
Internal - https://docs.google.com/document/d/1KQ-j4q0rC5lkhIHGk9bCC_TA50PGP5KSvTZaKUuuaaQ/edit#bookmark=id.cxbjjyozv0ai

During research, merge strategies emerged as something that people found hard to check their own work on. CoVE could help with this. See #950 for user/persona considerations. 

Prep required is deciding what the scope of this functionality should be

**Comment by robredpath** [comment]
Reviewing the previous conversation on this, I think that it makes sense to initially limit this to the "developer trying to test and understanding merging" use case, and therefore we can:
- restrict to embedded releases
- present a relatively unfriendly diff as a second step - so, initially just indicate that there is an issue, and offer to display (download?) the diff if required. 

We should mitigate the unfriendliness with some helpful copy in the UI and/or docs. 

Does that sound useful, @jpmckinney @julijahansen @timgdavies ?
Does that sound reasonably-sized, @Bjwebb @kindly ?

**Comment by jpmckinney** [comment]
Seems like these are prerequisites to anything more substantial, so sounds good to me as a first iteration.

**Comment by timgdavies** [comment]
To help me follow the scope of this issue, I've taken the following from the document linked above.

## Merge strategies validation + explanation

We want to check whether the record(s) in the supplied data are the product correctly merged releases

Would want to limit to embedded releases, at least initially, to avoid performance and network issues.

* I.e. where we have a record package, which contains both **releases**, and a **compiledRelease**, we can check if the compiledRelease == merge(releases)

We would use a similar UI to additional fields / missing fields

In the document @jpmckinney noted that before going the extra step and working on a clean, useful diff to present to users, we should: 

* (1) identify the publishers using records; 
* (2) check if any of their records produce this error; 
* (3) get a sense of why that might be – in order to design an appropriate solution in the validator

**Comment by timgdavies** [comment]
I agree that we focus on embedded releases only here - as we can always have scripts to pre-process linked releases into embedded releases for validation at this level. 

We should anticipate the kinds of errors occurring as:

* One of the source releases for the compiled release is missing;
* The merge algorithm has been incorrectly applied.

These may be tricky to distinguish from a diff.

**Comment by robredpath** [comment]
@timgdavies thanks for looking at this. 

The proposed first step here is to alert the user to the fact that there is a problem with merging - the display of the diff was suggested as a way to give some more information that requires no additional processing as it's a byproduct of the checking process. Perhaps a good mitigation would be to link to the docs on merging, and/or prompt Helpdesk contact in the UI?

**Comment by robredpath** [comment]
Reviewed this issue today. We're starting to check this as part of Kingfisher, so it's probably less urgent to address in CoVE, and we'll likely work through a lot of the technical and presentation difficulty there. So, not putting forward for CoVE development now, but a candidate for the future, for sure.

**Comment by jpmckinney** [comment]
Agreed on priority, and that it's still relevant in future, as giving people early feedback on merging errors increases the likelihood that they'll be fixed (whereas by the time we share feedback reports using data collected by Kingfisher, it's sometimes toward the end of their project).

**Comment by jpmckinney** [comment]
✅ From OCP's perspective, this issue can be closed / 'OCDS' tag can be removed.

The appropriate way for publishers to test their implementations of the merge routine is to use the [test cases provided by OCDS Merge](https://github.com/open-contracting/ocds-merge#test-cases), which are comprehensive and cover cases that are less likely to occur in data samples provided to the Data Review Tool.

A new issue can be created to add a note to the Headlines like: "This file contains compiled releases [and versioned releases]. If you created these merged releases, we encourage you to test your implementation of the [merge routine](https://standard.open-contracting.org/latest/en/schema/merging/) using the [OCDS Merge test cases](https://github.com/open-contracting/ocds-merge#reference-implementation). For assistance, please contact the [OCDS Helpdesk](mailto:data@open-contracting.org)."

**Comment by robredpath** [comment]
Closing, but pinging @duncandewhurst in case he disagrees
