### ISSUE TITLE
If an issue occurs on ALL records, I'd like CoVE to tell me

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#438]
In 360, we can highlight issues and also provide the total count 

In some cases, the total count equals the total number of grants (records) found in the data

![26](https://cloud.githubusercontent.com/assets/1209944/16275071/589edaea-38a0-11e6-9493-41b45b74608a.png)

As a user, I'd be interested to know if an error is for ALL records, or just for some.  I'd like to know if CoVE could indicate this for me - perhaps through presenting "all" issues in a different box to "some".

I can appreciate that in some cases the issue is for all records, as that column may be present, but blank - whereas in other instances (eg dates) it could be populated, but wrong.  That seems like a different issue from this however

**Comment by robredpath** [comment]
Closing - we've improved the interface in several ways around this
