### ISSUE TITLE
"Discarded range with reserved name" conversion warning

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#444]
Does this error message contribute anything? I've been asked if it is an issue and it doesn't appear to be a problem. See http://cove.opendataservices.coop/360/data/e5a606f0-06c2-4a43-8e25-1af27779b4df

**Comment by Bjwebb** [comment]
This is a warning message from the spreadsheet library we're using, because it doesn't properly support some feature of Excel. I agree this doesn't appear to be a problem in this case, but I'm not sure that we can in general determine that.

**Comment by caprenter** [comment]
@kindly and I looked into this the other day. 

I think we concluded that the issue was with the way the spreadsheet library was trying to handle a 'named range' in the sheet. (I think that had been introduced by the people fixing up the sheet)

@kindly (I think) was ruminating on what if anything to do.

Further, in this case, it's interesting that this is reported as a **error**, when it is actually a **warning** - and maybe we could be making better distinction about that.

**Comment by Bjwebb** [comment]
> Further, in this case, it's interesting that this is reported as a error

Is it reported as an error? It's in a box labelled "Conversion Warnings", although that box does also contain the text "we found the following issues"

OFC, error vs warning is a tricky one in this context. In Python only fatal problems are errors, everything else is warnings. However, we might use Python warnings to pass information about stuff that we know is erroneous in the data.

**Comment by caprenter** [comment]
Sorry - I mean in this issue it was reported as an error by the user "Does this error message contribute..." - although the application reports it as a warning.

**Comment by Bjwebb** [comment]
We've had several queries about this particular message, so I think we should look into hiding it.

**Comment by Bjwebb** [comment]
We hope to fix this issue during the current sprint, as part of https://github.com/OpenDataServices/cove/issues/511

An example of a spreadsheet that has this error is http://www.nesta.org.uk/sites/default/files/grants_data.xlsx

**Comment by robredpath** [comment]
@Bjwebb What happened with this during the sprint? I thought we were squashing it, but during internal user testing we've received reports that it's still being seen

**Comment by Bjwebb** [comment]
This should be fixed by https://github.com/OpenDataServices/cove/issues/511, which wasn't completed.

**Comment by Bjwebb** [comment]
We now have a deployed dev branch for the work around this, see https://github.com/OpenDataServices/cove/issues/511#issuecomment-278421675

**Comment by Bjwebb** [comment]
This is now deployed to https://dataquality.threesixtygiving.org/
