### ISSUE TITLE
Double slash in download URL for JSON 

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#453]
To replicate:

Upload a spreadsheet to CoVE
The download to get the converted JSON will end in //unflatten.json

**Comment by Bjwebb** [comment]
Fixed now on dev e.g. http://release-201709.cove-360-dev.default.threesixtygiving.uk0.bigv.io/data/6bd0c8ea-1323-4a63-9d19-ecb70cd3b05e
