### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#455]
https://app.getsentry.com/open-data-services/cove/issues/141208458/

```
TypeError: unsupported operand type(s) for +: 'int' and 'str'
  File "cove/views.py", line 35, in wrapper
    return func(request, *args, **kwargs)
  File "cove/views.py", line 151, in explore
    validation_errors = common.get_schema_validation_errors(json_data, schema_url, schema_name, request.current_app, cell_source_map, heading_source_map) if schema_url else None
  File "cove/lib/common.py", line 213, in get_schema_validation_errors
    field_name = e.path[-2] + ":" + e.message

TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

I can reproduce this with this JSON:
```
{
    "releases": [
        {
            "tender": {
            }
        }
    ]
}
```

**Comment by Bjwebb** [comment]
Problem is at https://github.com/OpenDataServices/cove/blob/master/cove/lib/common.py#L218

For my example the value of `e.path` is `deque(['releases', 0, 'tender'])`

Looks like the code is assuming that there is a trailing 0 (the problem happens within an array), so picks the -2th item, when in this case it should pick the -1th item. Instead it gets 0 which it can't append to the message string.

I also note we're displaying fields with colons here, which we probably don't want to do for OCDS JSON files.

@kindly I think this is mostly your code, so you might have the best idea of how to fix this.

**Comment by kindly** [comment]
This is a copy of #469
