### ISSUE TITLE
Error when generating validation messages for sub objects.

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/cove#469]
This effects only when a sub object (not a sub list of objects) has a required field and has a validation error. The error occurs as it adds an int to a string.  Also make sure validation errors are clear for this case.

Also delete rougue print statement.

**Comment by Bjwebb** [comment]
@kindly Could you check if this is the same issue as https://github.com/OpenDataServices/cove/issues/455 ?

**Comment by kindly** [comment]
This is fixed in  6a895ba
