### ISSUE TITLE
We specify an invalid PNG as the favicon

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#47]
(because it is just an empty file)

**Comment by caprenter** [comment]
we probably need something when the OCDS validator goes live or soon after

**Comment by robredpath** [comment]
Unless we can decide on what favicon to provide, we should provide no favicon at all.

**Comment by robredpath** [comment]
Or, provide appropriate favicons for the different validators

**Comment by Bjwebb** [comment]
Closing this issue as the invalid favicon is gone. New issues can be opened if/when having favicons becomes an issue.
