### ISSUE TITLE
CoVE does not recognise files with uppercase extensions

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#482]
Uploading a file with the extension XLSX fails with this message:

> Sorry we can't process that data
> 
> We did not recognise the file type.
> 
> We can only process json, csv and xlsx files.

See http://dev.cove.opendataservices.coop/360/data/059bcf0f-9f12-43e1-b19f-fe6f3ca14116

File added to the **Bad Data** folder on Google Drive

**Comment by Bjwebb** [comment]
This is fixed in master now, and on the dev site http://dev.cove.opendataservices.coop/
