### ISSUE TITLE
Sentry doesn't get OCDS Cove IP addresses properly

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#489]
Because there is a reverse proxy in the way.

Sentry doesn't trust X-Forwarded-For because people could spoof it.

http://httpd.apache.org/docs/trunk/mod/mod_remoteip.html could be a good way to address this.

**Comment by Bjwebb** [comment]
mod_remoteip didn't do quite what I thought it did.
mod_rpaf does do more of what I want. It changes the IP address that appears in the access logs, but the REMOTE_ADDR that Python (and therefore Sentry) gets is not updated.

**Comment by Bjwebb** [comment]
Actually, it looks like mod_remoteip did what I think, I was just failing to set it up by looking at the wrong cove instance!

**Comment by idlemoor** [comment]
w00t! you're a megastar, thanks for that! ok, I feel like getting creative in salt this afternoon :)
