### ISSUE TITLE
As a Cove user I would like to work with flattened representations in my own language

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#493]
Using flatten-tool's titles support + the appropriate schema with translated titles (e.g. http://standard.open-contracting.org/1.0/es/release-schema.json)

Blockers:
* Currently titles spreadsheet is not outputted for OCDS
* Not all fields defined in the schema have titles (this should be fixed in 1.0.2)
* There are no patch specific URIs (ie. Cove currently uses 1.0.1 schema explicitly, there's no URI for spanish 1.0.1 schema specifically)
* There are flatten-tool bugs with OCDS + titles - https://github.com/OpenDataServices/flatten-tool/issues/84

**Comment by timgdavies** [comment]
Just thinking aloud about other ways to possibly approach the requirement - if it was possible to output data according to a pre-defined template **and** for the column heading row to be given in row n, rather than the first row, then we could create Excel templates for each language, and the user could chose which template they exported to. 

This would then allow titles to be arbitrary across languages.

**Comment by Bjwebb** [comment]
Relevant flatten-tool issues:
* Flatten data into templates - https://github.com/OpenDataServices/flatten-tool/issues/131
* Pick up column titles from the nth line - https://github.com/OpenDataServices/flatten-tool/issues/130

**Comment by jpmckinney** [comment]
✅ From OCP's perspective, this issue can be closed / 'OCDS' tag can be removed.

As the Data Review Tool is presently publisher-oriented and review-oriented, the use case is to review data *as published*, to correct for errors in implementation.

For a user-oriented and use-oriented solution, users should be pointed to flattening tools (Flatten Tool CLI, [Toucan web UI](https://toucan.open-contracting.org), etc.). They should not be pointed to the DRT.

**Comment by robredpath** [comment]
@jpmckinney are you happy that there are no political issues around the presentation of English-language headers when converted data is presented to people outside of the immediate developer environment? In Mexico, this was a contentious issue and the provision of data with multilingual headings was, I thought, part of the solution

cc @juanpane

**Comment by jpmckinney** [comment]
Yes, we will continue to work on translated versions of data (the use case in the issue title) in flattening tools, OCDS Kit, Toucan, etc.

As a tool that is primarily used to review implementation, it's desirable for column headings to match JSON paths. An implementer might download the Excel file to investigate errors, but will ultimately have to make changes to a JSON publication. If the Excel headers were translated, they'd have to somehow determine which JSON path that relates to when performing a fix…

Related issues have been opened on Flatten Tool and OCDS Kit (which more directly support use of translated data), so we don't need another issue here (in addition to earlier reasons).
