### ISSUE TITLE
Create flow charts for common user journeys through the software

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#506]

**Comment by caprenter** [comment]
Some flow charts as a starter for 10 here:
https://docs.google.com/drawings/d/1pVbEu6dJaVk8t3NctjYuE5irsqltc9Th0gVQ_zeJyFA/edit
https://docs.google.com/drawings/d/1wFH4lZlBZWso7Tj_g7CyTF3YaFfnly59sVufpztmEg8/edit

These are set as public documents. I would expect them to change over time.

**Comment by Bjwebb** [comment]
These are now linked to from the README.
