### ISSUE TITLE
Create new 'potential issues' section, add 10-15 tests, improve code + docs to make it easier for us to add tests

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#507]
Previous issue on this topic https://github.com/OpenDataServices/cove/issues/361

**Comment by Bjwebb** [comment]
An issue with an existing example: checking the lenghts of titles https://github.com/OpenDataServices/cove/issues/201

**Comment by robredpath** [comment]
It occurs to me that there are two types of checks that we want to do here - one type relating to the data - eg, 'these 5 rows have zero-value grants, are you sure you want that', and one relating to the metadata - eg 'you have 10 funder IDs and 20 grants, are you sure that this file really contains data from 10 different funding orgs'?

**Comment by robredpath** [comment]
Next job is for me to write 10-15 things that I want see tests for

**Comment by robredpath** [comment]
https://docs.google.com/document/d/18S7OfvSxhGg7lqf-HT6fct8iEQvt81tqz15Pz4bnYHE/edit is where I've written some ideas on the tests I'd like to see

**Comment by Bjwebb** [comment]
@robredpath I've littered it with specific comments, but on the whole that looks good, thanks.

**Comment by robredpath** [comment]
This is done, we called it Additional Checks in the interface for 360
