### ISSUE TITLE
Move hosting & change the URL

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#509]
**As a user, I want the Data Quality tool to look and feel like a 360Giving tool so that I have trust in it**

We'll put the new site on the new server at the new address, then update links.

We'll do this with 16.04, unless there are major issues. We'll use Let's Encrypt by default; same proviso.

**Comment by caprenter** [comment]
Some links that will need updating:
http://www.threesixtygiving.org/support/resources/
http://www.threesixtygiving.org/data/publish-data/

**Comment by Bjwebb** [comment]
We have a dev server set up, under the 360Giving's bytemark account, and using Ubuntu 16.04 -   http://cove.cove-360-dev.default.threesixtygiving.uk0.bigv.io/

Remaining tasks:
- [ ] Removing OCDS from this deploy
- [ ] Setting up certbot (Let's encrypt client) - @idlemoor is currently looking into this on another server, but we can then deploy the same salt config on the 360 cove servers
- [ ] Set up a live server (should be quick, using the salt config we've written for dev)
- [ ] Point core 360 cove subdomain at live server (@robredpath is asking what this should be)

**Comment by Bjwebb** [comment]
Functional tests run successfully against the dev server with `BROWSER=PhantomJS CUSTOM_SERVER_URL=http://cove.cove-360-dev.default.threesixtygiving.uk0.bigv.io PREFIX_360=/ py.test fts` once I fixed a couple of bugs with them https://github.com/OpenDataServices/cove/commit/9e0cb6442e116f607231d691453bde70c977c27c

**Comment by Bjwebb** [comment]
We have https: https://cove.cove-360-dev.default.threesixtygiving.uk0.bigv.io/

Automatic renewal is currently broken though, I need to fix some interaction between `.well-known` and `ProxyPass`

**Comment by Bjwebb** [comment]
Dev server is now at https://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io/ for more consistency in naming.
Live server is mostly set up, still need to point the subdomain at it though.

**Comment by robredpath** [comment]
360 have approved  dataquality.threesixtygiving.org with a 301 redirect from the old URL, then a review using analytics to see if there are any links that need updating / when it's safe to switch off

**Comment by Bjwebb** [comment]
https://dataquality.threesixtygiving.org/ is set up now.
