### ISSUE TITLE
"Conversion errors" not "Conversion warnings"

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#511]
Split out of https://github.com/OpenDataServices/cove/issues/468:

Broadly this is:
* Rename the box to "Conversion Errors", and possibly change the styling.
* Suppress warnings that aren't known data issues (e.g. the schema related warnings https://github.com/OpenDataServices/cove/issues/394, or "Discarded range with reserved name" #444). We may want to log these to sentry instead, so our devs are alerted if anything odd is happening (or that maybe should be reported to users).

Step by step:
- [x] Replace all warnings with we deliberately raise in the flatten tool with a custom class
- [x] In cove display only this class in the user facing box
- [x] Do something useful with other warnings (e.g. Sentry)
- [x] Improve the tests
- [x] Rename the box and style it differently

**Comment by Bjwebb** [comment]
We have at least one warning that is a "potential issue" rather than an "error", as far as Cove users are concerned https://github.com/OpenDataServices/flatten-tool/blob/fc074cd0a4a25b925a05fc0dda0488f17d1c28d5/flattentool/input.py#L109

**Comment by robredpath** [comment]
@Bjwebb Do you have a sense for how much work is left on this?

**Comment by Bjwebb** [comment]
It's a day or two's work.

**Comment by robredpath** [comment]
Thanks @Bjwebb

**Comment by Bjwebb** [comment]
Dev deploy for this branch: http://511-conversion-errors.dev.cove.opendataservices.coop/360/
Some example data with "discarded range" message currently: http://www.greenham-common-trust.co.uk/sites/default/files/pdf/360Data_GCT_Reactive_Grants_Nov_2015_Final_0.xlsx
Some example data that legitimately causes a data error: [cause_data_errors.xlsx](https://github.com/OpenDataServices/cove/files/761608/cause_data_errors.xlsx) 

Remaining work to do on this is around tests.

**Comment by Bjwebb** [comment]
- [ ] Check that warnings are reported to sentry appropriately https://sentry.io/open-data-services/cove-dev/issues/215706893/events/

**Comment by Bjwebb** [comment]
- [ ] OCDS tool should not say Warnings either
- [ ] Test an actual bad XLSX (probably duplicate IDs)

**Comment by Bjwebb** [comment]
I've checked that warnings we don't show are going to Sentry, and importantly that different message texts are reported separately, which is useful to pick up new library warnings that might not be harmless.
