### ISSUE TITLE
BadZipFile error message is confusing

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#514]
`BadZipFile('File is not a zip file',)`
https://app.getsentry.com/open-data-services/cove-dev/issues/135489050/
https://app.getsentry.com/open-data-services/cove/issues/137994903/

This happens when trying to open a bad XLSX files. XLSX files are secretly zip files under the hood, so if it's not a zip file, it's a bad XLSX file. However, most users don't know they're zip files, so will probably interpret the error message to mean they should create a zip.

**Comment by Bjwebb** [comment]
https://sentry.io/open-data-services/cove/issues/321615261/

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BadZipFile error message is confusing](https://trello.com/c/UYvGZIZ7/27-badzipfile-error-message-is-confusing)

**Comment by Bjwebb** [comment]
We should fix this in flatten-tool, so that the updated message is seen by all users of flatten-tool, including commandline CoVEs, toucan etc.

We probably want to catch this [when we load the workbook with openpyxl](https://github.com/OpenDataServices/flatten-tool/blob/511cc6d1ee83d77aa7a1efe965eb3dd7e4940c1b/flattentool/input.py#L558), and raise a new error with a more useful message.

**Comment by robredpath** [comment]
Copy time!

How do people feel about "The supplied file has extension .xlsx but isn't a XSLX file." for when we catch it in flatten-tool?

And then, can we catch *that* in CoVE and provide more helpful feedback to a user, or is that much more complicated? @Bjwebb

**Comment by Bjwebb** [comment]
@robredpath Sounds good. Catching it again is straightfoward.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Provide a nicer error message if someone supplies a bad XSLX file](https://trello.com/c/WHubF3TI/65-provide-a-nicer-error-message-if-someone-supplies-a-bad-xslx-file)

**Comment by michaelwood** [comment]
This was implemented in flatten-tool with the above copy. https://github.com/OpenDataServices/flatten-tool/commit/019d33aecb9c4129d04132b8698aa95b58a3a482#diff-da34eb2b3d0a6bd6f7ca5fd1d20817f8R571 available in flatten-tool >= v0.10
