### ISSUE TITLE
How should cove fetch/store schemas?

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#52]
Currently schemas are fetched from external urls each time they are needed. This has overhead each time they are used, and will cause the application to break if GitHub or the OCDS standard website go down.

I think the alternatives are:
* Have the application fetch the schemas from remote urls, but cache them. The tricky bit here is knowing if/when the schemas need updating.
* Include the schemas in the GitHub repository. This is messy, but may be the easiest option, and the most obvious way to ensure that the application will work offline.

Whichever mechanism we choose should also be used by the tests, see https://github.com/OpenDataServices/cove/issues/16

**Comment by robredpath** [comment]
@Bjwebb My inclination is to close this, unless we've had any reports of those external sources being unreliable?
