### ISSUE TITLE
Support multiple versions of the schema

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#526]
**As a user, I want the validator to support multiple MAJOR.MINOR versions of the schema so that I can test my data against the latest version of the schema during upgrades**

Allow use of 1.1 including before 1.1 is officially launched 
Autodetection of version, but we should expose UI to override if it’s wrong CoVE #494
We always use latest PATCH for each version
Version in the schema standard issue OCDS https://github.com/open-contracting/standard/issues/301

**Comment by robredpath** [comment]
UI is a dropdown and a button in the headlines box, as this is where we already specify which schema we've validated against.

**Comment by robredpath** [comment]
Dropdown options - auto-detect / 1.0 / 1.1

**Comment by robredpath** [comment]
@edugomez is there any WIP on this that you can share?

**Comment by edugomez** [comment]
@robredpath I will push the branch with the code I have in a bit. As for the interface, it will look like this:
![ocds_526](https://cloud.githubusercontent.com/assets/5618508/22549926/aa89d0a2-e945-11e6-994e-27ee13e6030e.png)

**Comment by edugomez** [comment]
@robredpath obviously feel free to comment/ ask to modify that ^^

**Comment by Bjwebb** [comment]
Here is a deploy of the work so far http://526-support-multiple-schema-versions.dev.cove.opendataservices.coop/ocds/

**Comment by robredpath** [comment]
It would be nice to have a more obvious version number in the headlines, as well as the link to the schema.

**Comment by timgdavies** [comment]
Great work all

Layout wise, I'm wondering if the 'Validate against other schema version' could become it's own box under 'Convert' as that would make a more balanced page? 

Suggest that the drop-down then also defaults to the currently selected schema version - to give additional visual indication of what was selected.

**Comment by edugomez** [comment]
> Layout wise, I'm wondering if the 'Validate against other schema version' could become it's own box under 'Convert' as that would make a more balanced page?
I was thinking exactly the same, my only doubt being that reference to the schema version is in the headlines box where the new select form is. I think we could add some heading to the new box under 'Convert'  with something like 'Your data has been checked using schema version <a>x.x.x</a>..' and  the new form underneath?

**Comment by timgdavies** [comment]
Will the schema selected affect the conversation as well? I believe it would.

In that case, would the schema select work well top-right, above the convert box?

**Comment by robredpath** [comment]
@edugomez can you post a screenshot of where this ended up?

**Comment by edugomez** [comment]
@robredpath yeah sure, I don't know why I emailed to you instead of posting here.
![version](https://cloud.githubusercontent.com/assets/5618508/22736533/7b87808c-edf6-11e6-9a10-6c49c96024ac.png)

**Comment by edugomez** [comment]
This is how it looks in the latest version  

![version](https://cloud.githubusercontent.com/assets/5618508/22780654/57ae8ff4-eeb7-11e6-82a4-ff40b239459a.png)

**Comment by robredpath** [comment]
That's much nicer @edugomez !

**Comment by Bjwebb** [comment]
I see some broken templating "JSON (Original) {original_file.size|filesizeformat }} "

**Comment by Bjwebb** [comment]
This is now merged into master, and deployed at http://dev.cove.opendataservices.coop/ocds/
