### ISSUE TITLE
Support deprecation warnings

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#527]
**As a user, I want to be warned when schema features that I’ve used are subject to deprecation warnings so that I can address them early.**

Deprecation is a 1.1 feature that still needs to be added to the schema. But, to support 1.1, we need to make CoVE pick up on deprecation warnings
Standard issue concerning how we deprecate fields: [OCDS #401](https://github.com/open-contracting/standard/issues/401)
Our belief is that it’s safe for us to go ahead and implement as per the issue; we recognise the risk that it may be different in the end

We're pretty certain that the way the schema is going to end up is as in the issue

**Comment by robredpath** [comment]
UI is to add another box with a table in it, providing first 3 examples

**Comment by robredpath** [comment]
Copy is programmatically pulled from the schema when it's ready

**Comment by robredpath** [comment]
@edugomez this is in review - please can you provide instructions for how I (or anyone else) can review it?

**Comment by edugomez** [comment]
@robredpath [PR 561](https://github.com/OpenDataServices/cove/pull/561) requires code review of the functions getting the deprecated fields in the schema and the uploaded data. The tests (unit tests, see comment in PR for frontend tests) pass with the given test schema and data, but it would nice to see if the functions may be missing some corner cases (or not so corner!). For example, @kindly noticed (personal communication) a problem with `patternProperties` that probably deserve a separate issue (unless `patternProperties` they go altogether, which would be nice then :) ).

Another useful thing would be to check that the test data and schema with deprecated fields are good and fit for the purpose. 

BTW, I think we really need a live server we all can ssh into and pull a version of the code to show others, although I understand prob this is not the best place to discuss that.

**Comment by Bjwebb** [comment]
Here's a copy of the code running on our server, that's set up to use the fixture schema: http://527-support-deprecation-warnings.dev.cove.opendataservices.coop/ocds/
The sample data link on that page is a good example.

**Comment by robredpath** [comment]
At show-and-tell we discussed how a user would know what 'deprecated' means in practice. We talked about how a tooltip could be useful, as well as a link out to more complete documentation.

**Comment by Bjwebb** [comment]
Usage Count: 0 ?

**Comment by Bjwebb** [comment]
I've fixed the Usage Count problem.
