### ISSUE TITLE
Minimal API

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#530]
**As the developer of a system outputting OCDS data I want to be able to access CoVE via an API, either posting JSON, or providing a URL, and getting the responses back as structured data, so that I can implement automated testing of my data**

Doable in a minimal way
Tricky bit is writing some words to explain status
Document + standardise to avoid us having to write client libs
OpenAPI

We already produce a load of JSON internally so we can just expose that

**Comment by jpmckinney** [comment]
Merge this issue back into #320?

**Comment by robredpath** [comment]
Yeah, I think we can just close this
