### ISSUE TITLE
Review of UI, language, usability

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#531]
This is a spike; 3-4h of research with the expected outcome being 0 or more issues added to the backlog which when worked will improve the UI, language or usability of OCDS CoVE in ways that can be described as "quick wins" - ie, no suggestions of major refactoring or redesign!

This should include reviewing the existing issues to see what previous work has been done on this. Possible ways of recording this review would be labelling issues or using GitHub comments to connect to this issue

**Comment by timgdavies** [comment]
Discussed with Eduardo yesterday and agreed this would be really useful to do.

**Comment by robredpath** [comment]
This also ties in a bit with my work around how we frame the tool and what stops people using it. Duncan's given me a list of names but I've not made any progress on that.

**Comment by jpmckinney** [comment]
Is this taken forward in #950 and can be closed, or is it distinct?

**Comment by robredpath** [comment]
This led to the big validator report I did last year. Closing.
