### ISSUE TITLE
Spike to explore options around validating extended spreadsheets

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#532]
Related to internal issue 7466

**Comment by Bjwebb** [comment]
https://opendataservices.plan.io/issues/8202#note-9

**Comment by Bjwebb** [comment]
@kindly has been doing some work on this in flatten-tool https://github.com/OpenDataServices/flatten-tool/pull/144

**Comment by Bjwebb** [comment]
We now have meta tab.
