### ISSUE TITLE
Add PPP support to OCDS Show

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#534]
@kindly to work with Duncan on this early in the sprint; meeting late Thursday in the first week to discuss details.

**Comment by duncandewhurst** [comment]
@kindly I've made a few updates to the [ppp schema](http://standard.open-contracting.org/ppp-extension/en/release-schema.json) so it should be good to go now.

I'll try and get the sample data built out tomorrow.

**Comment by robredpath** [comment]
See https://opendataservices.plan.io/issues/7350 for some useful info

**Comment by robredpath** [comment]
@kindly is there any WIP on this we can see?

**Comment by Bjwebb** [comment]
This is online at https://open-contracting.github.io/ocds-show-ppp/
I see there's some sample data to use against it at https://raw.githubusercontent.com/open-contracting/standard/ppp-extension/standard/docs/en/examples/ppp/full.json , but it dosen't quite work as expected. @kindly Is there some better example data to be using?
