### ISSUE TITLE
I-JSON Validation - rfc7493

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/cove#535]
In [this OCDS issue](https://github.com/open-contracting/standard/issues/323) we have agreed to required that OCDS JSON data should follow [I-JSON - RFC7943](https://tools.ietf.org/html/rfc7493) using UTF-8 encoding, and with a couple of other constraints.

It would be good if CoVE for OCDS validated against the I-JSON spec, and reported any violations of I-JSON requirements.

**Comment by timgdavies** [comment]
@robredpath Could you see if this is simple to add to next sprint?

**Comment by robredpath** [comment]
@timgdavies we're feeling the squeeze for this sprint already - is it ok if we push this back to a later sprint? We could do a copy change in the meantime, if that helps?

**Comment by timgdavies** [comment]
Sure. I don't think this is top priority for current sprint.

**Comment by jpmckinney** [comment]
Just noting that entering ISO-8859-1 encoded data has an error message like: `'utf-8' codec can't decode byte 0xd3 in position 589: invalid continuation byte`. So, CoVE would need to be able to detect / recover from encoding errors to fulfill this issue.

**Comment by jpmckinney** [comment]
Add "bug" tag re: above comment?

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make encoding errors actually tell you what to do](https://trello.com/c/NmSoxpcI/26-make-encoding-errors-actually-tell-you-what-to-do)

**Comment by jpmckinney** [comment]
Note that [“Objects in I-JSON messages MUST NOT have members with duplicate names”](https://tools.ietf.org/html/rfc7493#section-2.3). `object_pairs_hook` can be used to warn/raise if there are duplicate keys: https://stackoverflow.com/questions/14902299/json-loads-allows-duplicate-keys-in-a-dictionary-overwriting-the-first-value
