### ISSUE TITLE
Create an instance of CoVE for working with PPPs 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#540]
Set up a separate deploy pointing at the extended schema

We also need to fix flatten-tool to work for this https://github.com/OpenDataServices/cove/issues/544

[@Bjwebb - updated this issue to be about the deploy, and added a new issue for flatten-tool work]

**Comment by Bjwebb** [comment]
I've set this up at http://ppp.dev.cove.opendataservices.coop/
The salt files need a little bit more work to not break other deploys before this is Done.
