### ISSUE TITLE
Validate the Currency codelist in Cove

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#543]
[Updated by @Bjwebb]
This has been split out of #528, because Currency is a closed codelist without any enums, and without the codelist in the standard repo. Thus it requires more work than the other tasks in that issue.

Part of issue is likely to be updating the standard docs to pull in the Currency codelist from ISO

**Comment by robredpath** [comment]
For #528

**Comment by timgdavies** [comment]
I've added a note to the 1.1 upgrade list to get the currency codelist into the standard docs.

**Comment by jpmckinney** [comment]
This issue can be closed. Currency now has an enum.
