### ISSUE TITLE
The new 360 CoVE preview table is missing panation, sort and serch

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#545]
Before:

![before](https://cloud.githubusercontent.com/assets/1209944/22379153/0cc2e820-e4b0-11e6-9422-6d6380459c50.png)

After:

![after](https://cloud.githubusercontent.com/assets/1209944/22379185/2ec18788-e4b0-11e6-84bd-4d71696e1432.png)

**Comment by edugomez** [comment]
I can see this happening here https://dataquality.threesixtygiving.org after uploading a file but not when I run a local server at master branch, in which case it is working. ??

**Comment by Bjwebb** [comment]
@edugomez Could well be a deploy issue then. I'll take a look tomorrow morning.

**Comment by Bjwebb** [comment]
Looks like this is because some JS resources can't be loaded because they're requested over HTTP, not HTTPS.

**Comment by Bjwebb** [comment]
@stevieflow This is now fixed on https://dataquality.threesixtygiving.org/

**Comment by stevieflow** [comment]
Great, thanks - tested and can see this is back in
