### ISSUE TITLE
Losing usage stats when changing URL

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#546]
We should be minded that the data via http://cove.opendataservices.coop/360/stats would not be accessible via any new URL.  This is valuable data to the project

**Comment by robredpath** [comment]
Is https://dataquality.threesixtygiving.org/stats not the same thing? @stevieflow

**Comment by stevieflow** [comment]
@robredpath yes / no

The stats at http://cove.opendataservices.coop/360/stats reflect the time period that http://cove.opendataservices.coop/360/ has been in use.  These are useful to 360

https://dataquality.threesixtygiving.org/stats have the same format, correct - but do not include the stats at http://cove.opendataservices.coop/360/stats

I dont think there is a chance to combine the numbers, so flagging that a potential loss of http://cove.opendataservices.coop/360/stats would be damaging to the project.  We will need to be clear during any switchover, particularly if http://cove.opendataservices.coop/360/stats becomes inaccessible

**Comment by Bjwebb** [comment]
My proposed approach to this would be:
1) copy/paste the numbers at http://cove.opendataservices.coop/360/stats into a google doc
2) backup/archive the sqlite database that these numbers are generated from

**Comment by stevieflow** [comment]
@Bjwebb would that then mean the numbers from http://cove.opendataservices.coop/360/stats would be added to the numbers at https://dataquality.threesixtygiving.org/stats ?

No worries if not, so long as they are accessible I think

**Comment by Bjwebb** [comment]
@stevieflow No, they wouldn't be added. That's possible to do, but a bit more effort (combining the databases correctly), which I don't think is worth it.

Bear in mind that all these numbers are somewhat dubious anyway - e.g. when I run some automated testing against the site they get bumped up considerably.

**Comment by stevieflow** [comment]
No problem.  The purpose of this ticket was to flag that we didnt lose sight of the existing tickets - so I am happy with the proposed way forward.  Thanks

**Comment by robredpath** [comment]
I can't see any action here. http://cove.opendataservices.coop/360/stats was decommissioned a while ago.
