### ISSUE TITLE
Additional Checks section usability tweaks

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#549]

**Comment by robredpath** [comment]
Add headings to each additional check to aid usability
Add icons? 
Make numbers more obvious, clickable to see all instances

**Comment by robredpath** [comment]
Internal ticket #7929

**Comment by robredpath** [comment]
@kindly how hard is the 'clickable to see all instances' bit of this?

**Comment by stevieflow** [comment]
> Add headings to each additional check to aid usability

I would advocate for this, and even label as release-blocker - even if it is just a sentence summary for each check, that we present in **bold**.  In showing people the additional checks today they were very engaged in it, but it's just difficult to comprehend

**Comment by robredpath** [comment]
@kindly, can you reply to my question above please? 

@stevieflow I'm hoping that this is actually pretty easy to do and therefore can easily be done before release. I don't think that this is a blocker for the same reasons I gave in https://github.com/OpenDataServices/cove/issues/566#issuecomment-293490633

However, do note that #575 is just the headings part of this and is labelled Bitesize so we're planning to do it before release.

**Comment by edugomez** [comment]
Move part of this issue ( (ie. icons, clickable and see all instances as they require some more thought) to new issue https://github.com/OpenDataServices/cove/issues/655
