### ISSUE TITLE
It's possible to view 360 data within the ocds template

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#55]
(and vice-versa)

I think we should probably disable this, and possibly redirect to the correct URL (and template).

**Comment by Bjwebb** [comment]
Adding to separate out 360 and OCDS milestone, as this problem will go away if we always deploy them seperately.

**Comment by robredpath** [comment]
I'm not sure what this issue means - can someone give me an example?

**Comment by Bjwebb** [comment]
Submit some data and get a URL http://dev.cove.opendataservices.coop/360/data/{UUID} it's possible to then visit http://dev.cove.opendataservices.coop/ocds/data/{UUID} and get some mixed up results.

This isn't something people are likely to do accidentally, so I'm not sure whether we actually need to do anything about this, but it does feel like something that could lead to security issues and/or confusion down the line.

**Comment by robredpath** [comment]
Ah, ok, I see. 

Yeah, I can't imagine anyone ever doing that unless they were trying, and I think it'll probably get fixed unintentionally at some point as we continue to separate out the apps, especially if/when we add another validator to CoVE. 

I don't *think* we're likely to have a security issue here, as I'm not sure what a user would be able to do that we'd consider a violation of security, other than making the website make untrue (but nonsensical) statements about the data.

Closing, and we can re-open if we become aware of a problem that this causes.
