### ISSUE TITLE
Restore piwik opt out 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#552]
The Piwik opt-out is broken on new 360 CoVE - https://dataquality.threesixtygiving.org/terms

Compare:  http://cove.opendataservices.coop/360/terms

**Comment by robredpath** [comment]
@edugomez - a fun 360 distraction for when you need a break from OCDS!

**Comment by Bjwebb** [comment]
Yet another HTTPS one I'm afraid.

**Comment by Bjwebb** [comment]
This is now fixed on dev https://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io/terms
