### ISSUE TITLE
More Information is blank in FF

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#553]
@caprenter I wasn't able to replicate this, can you post a screenshot please?

**Comment by caprenter** [comment]
Did you try it on https://dataquality.threesixtygiving.org/common_errors ?

I can see it using Chrome and Firefox

**Comment by robredpath** [comment]
Ah, I see. Replicated, thanks!

**Comment by edugomez** [comment]
It is the same on live http://cove.opendataservices.coop/360/common_errors. What do you expect to see there?

**Comment by caprenter** [comment]
The same as on the front page:
http://cove.opendataservices.coop/360/
(I believe it also 'works' on pages that report back on data.

This is an expandable box that sits in most of the templates.

**Comment by edugomez** [comment]
@caprenter OK, will add that

**Comment by robredpath** [comment]
@caprenter I'm not sure that the text is really relevant to that page; would it make more sense to just remove the box?

**Comment by caprenter** [comment]
I don't think I'm the arbiter of that.

The issue is that there is a box that says click here for more info and it doesn't give you any.

**Comment by robredpath** [comment]
This looks like it's a case of a template pulling in a box that shouldn't be there rather than a box having lost its content, especially as it's the same on old CoVE - http://cove.opendataservices.coop/360/common_errors. @edugomez , let's just remove that box!

**Comment by edugomez** [comment]
@robredpath  OK, will do

**Comment by Bjwebb** [comment]
This is now in master, and on the dev deploy https://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io/
