### ISSUE TITLE
Review navigation around 360 DQ tool 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#554]
The 360Giving DQ tool is a discrete piece of software from the main website, and therefore shouldn't have integrated navigation. However, its look-and-feel is now more 360-ey and so users may expect at least a link back to the 360 site from CoVE. 

We also refer users to documentation - the DQ tool plays a certain role as a central place to start approaching validation / usefulness questions. We should make sure that any developments along this path are properly considered. 

We should also review how people flow through the software - info on what to expect and how to use the tool is between a couple of different places

**Comment by caprenter** [comment]
For Info. There are links back to the main 360Giving website in the Links section on the footer of each page.

**Comment by robredpath** [comment]
We did a UX review, and we're starting to treat all of the 360 web properties in a more joined-up way. Nothing else to do here!
