### ISSUE TITLE
Data Supplied box - "to" is in bold (between dates) 

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#559]
https://dataquality.threesixtygiving.org/data/398cdb32-bb27-40e7-8a28-c5cdef523caa

> 2013-07-07T00:00:00+00:00 to 2016-11-08T00:00:00+00:00.

In the above, the "to" is in bold.  It may be better to remove the bold.

**Comment by caprenter** [comment]
I'm seeing this type of sentence:

    This file contains 69 grants from 1 funder to 67 recipients awarded from 2015-11-30T00:00:00+00:00 to 2016-02-06T00:00:00+00:00. 

Gooder Inglish would use 'between' and 'and' instead of from and to - IMHO

    This file contains 69 grants from 1 funder to 67 recipients awarded between 2015-11-30T00:00:00+00:00 and 2016-02-06T00:00:00+00:00.

**Comment by stevieflow** [comment]
@caprenter good point - I'd support that.  And not in bold

**Comment by edugomez** [comment]
@caprenter I will change that
