### ISSUE TITLE
Link in alpha banner hard to read

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#565]
https://dataquality.threesixtygiving.org/
Orange link on an orange background.

One solution may be to remove the banner.

**Comment by robredpath** [comment]
+1 to removing the banner. I'd still like to see a clear route to GH Issues - but maybe through the footer instead?

**Comment by caprenter** [comment]
There has always been a route to GitHub issue vis the footer. However, this talks about CoVE, so the job may be some rewording.

**Comment by Bjwebb** [comment]
See https://github.com/OpenDataServices/cove/issues/778

**Comment by stevieflow** [comment]
Just get rid of it
