### ISSUE TITLE
'here' isn't a good link text

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#566]
Check your data is accurate. Read about common data errors and how to check for them _here_.
Check the data against your own open data policy. Read more about open data _here_.

Instead we should be using descriptive links (something like):
Check your data is accurate. Read about _common data errors and how to check for them._
Check the data against your own open data policy. Read more about _open data._

**Comment by robredpath** [comment]
Internal ticket #7929

**Comment by stevieflow** [comment]
I think @caprenter would want this as release-blocker.

I would agree.  And - it strikes me that this is textual changes that can easily be crafted - not heavy development work

**Comment by robredpath** [comment]
@stevieflow that's why it's labelled Bitesize and scheduled to be fixed before release.

However, I disagree that this is a blocker to release; it's not severe enough IMO. It doesn't stop the app, cause a crash, cause an error message, cause an unintuitive response to a query, it won't cause data loss, it isn't a security issue, it isn't license problem, it won't get us in legal trouble. It's just something that we want to be better.

Unless there's something I've missed - what happens if we release with this issue unresolved?

**Comment by stevieflow** [comment]
@robredpath 

> It doesn't stop the app, cause a crash, cause an error message, cause an unintuitive response to a query, it won't cause data loss, it isn't a security issue, it isn't license problem, it won't get us in legal trouble. It's just something that we want to be better.

OK, fair enough - I hadn't see that list before!

**Comment by robredpath** [comment]
I should point out that the list isn't any sort of agreed policy, it's just what I think should block a release. And I'm very aware that I marked a simple typo as release-blocking in #583 on the grounds that it's 'something thats wrong' rather than 'something that could be better', which isn't on the list. So there's lots of my pragmatism behind my opinion on this! 

Definitely something to put into the writing/thinking I'm doing atm on how we get software released. Lots of open-source projects have very clear definitions of these things that could make for some useful reading.

**Comment by caprenter** [comment]
For me this is blocked by the standards I think we should be applying to our work, because I think 'descriptive links' are a basic usability and accessibility standard. It is a very low bar to clear. It should be second nature to us all.

**Comment by robredpath** [comment]
@edugomez this issue is now closed but it's still in the non-sprint backlog in plan.io and in the 360Giving CoVE Snagging GitHub project. 

What's the current status of this?

**Comment by edugomez** [comment]
Sorry, it is merged ([PR #664](https://github.com/OpenDataServices/cove/pull/644)) , should've updated those

**Comment by edugomez** [comment]
@robredpath can't see it in plan.io non-sprint backlog

**Comment by robredpath** [comment]
@edugomez it's #7929
