### ISSUE TITLE
Zero-value grant check is incorrect

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#567]

**Comment by Bjwebb** [comment]
Actually, I think this is unrelated to grant IDs - the check message is displayed if there are non-zero grants, not if there are zero grants!

e.g.
`{"grants": [{"amountAwarded": 3}]}` displays the message, but
`{"grants": [{"amountAwarded": 0}]}` does not

This should be the opposite way round.

**Comment by Bjwebb** [comment]
Deployed to dev now - https://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io/
