### ISSUE TITLE
Additional Checks should check for all recommended fields

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#568]
Recipient Org:Charity Number
Recipient Org:Company Number
Beneficiary Location:Name
Beneficiary Location:Geographic Code
Beneficiary Location:Geographic Code Type
Last modified
Data Source
Recipient Org:Postal Code
Recipient Org:Location:Geographic Code
Recipient Org:Location:Geographic Code Type
Classifications:Title

**Comment by kindly** [comment]
Can we have some copy for this?

**Comment by kindly** [comment]
The worry I have for this is that it will mean for a lot of cases there will be a lot of additional check failures, which may look odd.  Maybe we should roll this into one additional check somehow?

**Comment by robredpath** [comment]
Would it make sense to roll them into groups? eg Beneficiary Location - 1 or more fields missing?

**Comment by robredpath** [comment]
Internal ticket #7931

**Comment by kindly** [comment]
It would be good to get some copy on this, especially if we roll them up into groups.  The copy will determine how it will be implemented.

**Comment by robredpath** [comment]
@ekoner I've added a section at the bottom of https://docs.google.com/document/d/18S7OfvSxhGg7lqf-HT6fct8iEQvt81tqz15Pz4bnYHE/edit# with proposed copy - could you review? 

@kindly there will undoubtedly be wording changes but the implied algorithm won't change (I hope!)

**Comment by ekoner** [comment]
@robredpath I've scheduled a review for tomorrow morning 10.03.2017. Let me know if you need feedback sooner.
