### ISSUE TITLE
What do we need deployed at the end of the sprint?

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#571]

**Comment by Bjwebb** [comment]
Most of the work for this sprint is not yet useful for the live version of OCDS Cove - e.g. supporting version switching, but we still only have one live version, and deprecation warnings, but those aren't in a live schema.

We also have another OCDS Cove sprint coming up soon. I'm wondering if it would be better use of our time to leave the live deploy until then, and have the outcome of this sprint be the dev deploy (of the master branch) at http://dev.cove.opendataservices.coop/

@robredpath What do you think?

**Comment by timgdavies** [comment]
I can envisage wanting to share ability to validate data against 1.1-dev with a few people before the next sprint - so if we had a dev instance running with schema switching (including the dev branch) and deprecation warnings live that would be great.

Nothing needs to be on the live OCDS validator until after the next sprint.

**Comment by Bjwebb** [comment]
Everything in the Done column on https://github.com/OpenDataServices/cove/projects/3 is no merged into master, and deployed onto our main dev deploy http://dev.cove.opendataservices.coop/ocds/
