### ISSUE TITLE
Convert breaks on deliveryLocation extension

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#572]
When the deliveryLocation extension is used in an OCDS file, the file won't convert to spreadsheets. 

https://github.com/open-contracting/standard/blob/c06ee6bee3ab10be5fa07198c22f0b029ceb857d/standard/docs/en/extensions/location.md

Error: af1b9bf5ae5a4c03b3f416cb383e6d13

**Comment by Bjwebb** [comment]
This is due to a fairly simple bug in flatten-tool, so we should hopefully be able to fix as part of our work on making Cove work for the PPP schema https://github.com/OpenDataServices/cove/issues/544

Sentry link: https://sentry.io/open-data-services/cove/issues/138001304/

**Comment by Bjwebb** [comment]
This is fixed in this flatten-tool commit https://github.com/OpenDataServices/flatten-tool/commit/720a35afd228dab51f1b5dea50a74a71c505dddb
Here's a deployed copy: http://572-number-array.dev.cove.opendataservices.coop/ocds/

**Comment by Bjwebb** [comment]
This is now fixed on the master branch: http://dev.cove.opendataservices.coop/ocds/
