### ISSUE TITLE
Additional Checks inconsistency with counts and plurals

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#574]
Using this data: http://www.greenham-common-trust.co.uk/sites/default/files/pdf/360Data_GCT_Reactive_Grants_Nov_2015_Final_0.xlsx

Under Additional Checks I can see the following types of feedback:

1. One or more of your grants have a value of £0. 
2. 1 grant(s) have a value 
3. 15 grant(s) have a value provided
4. 69 grants have a title

I'm thinking we could do a consistency check here. 

- It should not be hard to display 1 grant has, 15 grants have, etc
- I'm not sure if the 'One or More' is because it is too hard to offer a count
- I'm not sure if 69 grants would show 1 grants or has been 'pluralised'

**Comment by robredpath** [comment]
Internal issue #7929

**Comment by edugomez** [comment]
Issue dealt with in branch [575-additional-checks-headline-highlight](https://github.com/OpenDataServices/cove/tree/575-additional-checks-headline-highlight)

**Comment by Bjwebb** [comment]
This is now fixed https://dataquality.threesixtygiving.org/data/016d9af5-5ca1-4a91-8332-28229b31ebaa
