### ISSUE TITLE
Additional Checks - highlight the headline

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#575]
The additional checks description, seems to be a headline + further information, but as formatted, just looks to me like a big block of text.

I think 
1) Bold the headline
2) Put the description on a new line
to make this more readable, and easier to scan (i.e. when there are say 6 blocks of info, I can get the headlines easily - once I've used the tool a few times I don't always need the explanation)

**Comment by stevieflow** [comment]
@timgdavies also suggested an icon for each check - just adding that here, but appreciate that might be a future iteration

**Comment by stevieflow** [comment]
Does this text need writing /  preparing? If so, how best to do it?

**Comment by caprenter** [comment]
My original suggestion was to bold the headline, and move the explanatory text to a new line. This is simple to do and does not require any new text. It needs 1) agreement to be done, 2) someone to do it and create a pull request

Adding icons requires someone to chose and allocate icons which is new work. I would suggest that is a different task and if required is broken out of this ticket, as otherwise it could hold up the other clearly defined task.

**Comment by stevieflow** [comment]
> My original suggestion was to bold the headline, and move the explanatory text to a new line. This is simple to do and does not require any new text. It needs 1) agreement to be done, 2) someone to do it and create a pull request

I agree with that.  Let me know if I can help in any way

**Comment by caprenter** [comment]
From conversation with @kindly -The best way to do this would probably be to give each response its own template - which is a bit of a pain but would be safe and the most flexible. It would be pretty easy to do actually you would return render_to_string('your_template.html', {'some_key':'some_value'}) as described here http://stackoverflow.com/questions/37562363/why-does-django-need-a-request-object-in-rendering-a-template
Use {{message|safe}} and put that in the template

**Comment by Bjwebb** [comment]
Deployed to https://dataquality.threesixtygiving.org/

Screenshot:
![additional_checks](https://cloud.githubusercontent.com/assets/5618508/25435775/1715cd78-2a89-11e7-9ce7-32bc6fa148c9.png)
