### ISSUE TITLE
Review memory usage of recent changes

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#579]
In particular for depreaction, where I think we're making a new full representation of the data in memory: https://github.com/OpenDataServices/cove/pull/561#discussion_r99875902

**Comment by edugomez** [comment]
@Bjwebb Is this urgent, as we have no control over the amount of data uploaded by user?

**Comment by Bjwebb** [comment]
@edugomez I think it's a task for the next sprint.

**Comment by kindly** [comment]
I have written a doc analysing the memory usage of COVE currently.

https://docs.google.com/document/d/1DwFGVLjqTD3yfWg-7zKGsl4X5L2B2R7yAJkGCyoBLUA/edit?usp=sharing

It can also be used as a guide to how we can do memory usage testing in future.

**Comment by robredpath** [comment]
That's very interesting, thanks @kindly  - and thanks in particular for documenting your process so thoroughly, so we can investigate a bit more widely in the future.

**Comment by jpmckinney** [comment]
Key conclusion:

> Deprecated fields take up around ~150MB of the ~500MB usage for this file so is a candidate for memory reduction.  However as just loading the JSON into memory takes ~240MB it will not save us anywhere near an order of magnitude to improve its memory usage.  We will have to careful not adding many more of these functions in future.

I think this issue can be closed, as there is no recommended action, besides continuing to consider memory usage in future.
