### ISSUE TITLE
Add more documentation for our custom ref classes

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#581]
e.g. docstrings

https://github.com/OpenDataServices/cove/blob/master/cove/lib/common.py#L101
https://github.com/OpenDataServices/cove/blob/master/cove/lib/common.py#L149

**Comment by robredpath** [comment]
@Bjwebb is this still relevant? I'm looking for things we've recorded in ODSC repos to move over to OCDS

**Comment by Bjwebb** [comment]
We now have some docstrings https://github.com/OpenDataServices/lib-cove/blob/master/libcove/lib/common.py#L320 https://github.com/OpenDataServices/lib-cove/blob/master/libcove/lib/common.py#L926
