### ISSUE TITLE
that is has

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#583]
Spelling/grammar error "that is has" in:
https://github.com/OpenDataServices/cove/blob/master/cove/lib/threesixtygiving.py#L213
and
https://github.com/OpenDataServices/cove/blob/master/cove/lib/threesixtygiving.py#L198

These messages could probably be reviewed for grammar throughout.

**Comment by Bjwebb** [comment]
The specific issue is fixed now, and deployed to https://dataquality.threesixtygiving.org/

I'm not sure whether anyone's reviewed the grammar of the rest of the messages.
