### ISSUE TITLE
CoVE does not check for badly formed Identifiers

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#586]
The [360Giving data quality tool](http://cove.opendataservices.coop/360/) does not check for badly formed Identifiers (this may be by design.)

When provided with an Identifier, it does not detect spaces between the prefix e.g. GB-CHC- and the rest of the Identifier. It also doesn't account for trailing spaces.

Expect:
GB-CHC-123456789 - to pass
GB-CHC- 123456789 - to fail or flag up a warning (space between prefix and rest of identifier)
GB-CHC-123456789  - to fail or flag up a warning (trailing space)

**Comment by robredpath** [comment]
AFAIK this isn't by design so much as just not a feature (yet!)

I assume this would need to be an additional check, @ekoner ? As the standard only calls for it to be a string?

**Comment by ekoner** [comment]
Could it be part of the additional checks that test the prefix?
