### ISSUE TITLE
App Separation for IATI

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#601]

**Comment by edugomez** [comment]
- Keep a single repo and break current `cove` into `cove` (core), `cove360`, `coveOCDS`, `coveIATI`.  
- Apps will have their own **_settings.py_**. In principle, setting files won't extend a base one,  so they will have some level of repetition, although they should be more simply (ie. we can ge rid of `COVE_CONFIG_BY_NAMESPACE`).  
- Apps will have its own template folder. Templates should live inside another folder with name of the app, making easy to refer to either own or `cove` core templates with same names (ie. _base.html_).  
- At the repo root level three _"manage.py"_ files: **_manage360.py_**, **_manageOCDS.py_** and **_manageIATI.py_**.  
- `urls` and `tests` to be distributed among new independent apps. No need for _urls_multi.py_ and the use of `PREFIX`.  
- Decide the distribution of `views`, management `commands`, `templatetags`, etc... between core `cove` and other dependant apps.

**Comment by edugomez** [comment]
### The refactoring so far:
- The current structure: 4 apps,  `cove` (core), `cove_360`, `cove_ocds` and `cove_iati` (all depending on `cove`). 
- Each app has a _settings.py_ file. All apps inherit and extend  the settings in `cove`. 
- There is a single _manage.py_ at the root of the project that needs to be run with _--settings_ option: e.g. `python manage.py runserver --settings=cove_ocds.settings`.  
- Existing tests are distributed among the apps, and like _manage.py__,  _pytest_ needs to be passed the _--ds_ option to find the right settings: e.g. `py.test cove_360/ --ds=cove_360.settings` to run the tests in `cove_360`.This means that tests need to be run separately for each app, which can be useful for development, but we may also need some shell script to run all the test in the repo in one go when needed. 
- _cove-resource-project_ is gone. The only thing left is a _dataload_ folder in `cove` without models and with a migration file to run and delete the tables in the database. Once that migration is run on any existing instance of CoVE the whole folder can be deleted. 
- App-specific sass files are within the apps and depend on the bootstrap files in `cove` ( although still writing generated css files to _static_ in `cove`)

### TODO
- Get rid of _dataload_ in`cove`
- Separate  _fts_ tests among the appropriate apps
- hypothesis tests still in `cove` and not refactored according to the new project structure
- home page (input page now) for OCDS missing 'Using the Validator'
- Travis needs to be able to run the tests in all the apps
- _docs_ may need some review/changes
 
@kindly @Bjwebb

**Comment by Bjwebb** [comment]
Note that some of these changes mean we'll have to change our deploy set up for a bit (on the whole to be simpler, so that's good) - I've added a new issue for that https://github.com/OpenDataServices/cove/issues/608
