### ISSUE TITLE
Update merging conflict message

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#611]
https://opendataservices.titanpad.com/640

https://github.com/OpenDataServices/flatten-tool/blob/58c8422977068bb75d614ba28c9972420509e2aa/flattentool/input.py#L123

Current Message:

> Conflict when merging field "{}" for {} in  sheet {}: "{}" != "{}". If you were not expecting merging you may have a duplicate ID.

Suggested new Message:

> You may have a duplicate Identifier: We couldn't merge these rows with the Identifier "{}": field "{}" for {} in  sheet {}: "{}" != "{}"

**Comment by Bjwebb** [comment]
@stevieflow I got the impression last week that the `!=` in the message wasn't clear to you, is that correct? We can replace is with some less cryptic text.

**Comment by stevieflow** [comment]
Yes please!

**Comment by Bjwebb** [comment]
Old error message: 
![image](https://user-images.githubusercontent.com/634/30708774-eb06a566-9ef7-11e7-86ab-ef1d95ab2bb1.png)

New error message:
![image](https://user-images.githubusercontent.com/634/30708808-fe8ffd58-9ef7-11e7-9962-1ca4b4221df1.png)

@stevieflow What do you think to that?

**Comment by robredpath** [comment]
In case anyone else makes the same (incorrect) assumption that I did - this affects all instances of CoVE, not just IATI.

**Comment by robredpath** [comment]
@stevieflow what do you think to the new wording @Bjwebb has suggested? It'll apply to 360 as well - so should we get Rachel to review it?

**Comment by stevieflow** [comment]
Seems great, thanks - please go ahead

**Comment by Bjwebb** [comment]
This is now deployed to the dev sites: http://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io/ http://iati.cove.opendataservices.coop/ and http://dev.cove.opendataservices.coop/validator/
