### ISSUE TITLE
flatten_dict assumes that all lists are lists of dicts

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#613]
Internal Server Error

Something went wrong with your request. This could be due to a bug in the application and/or the data you supplied.

This error has been automatically reported to our development team. If you get in touch, please reference this error as 19265c9235f8444cb905c00ddd755795.

Same file passes on: http://cove.opendataservices.coop/360/data/8ff6a19c-84df-4f18-bac1-790f3c8e22e9

**Comment by robredpath** [comment]
Replicated. @Bjwebb - this doesn't seem to have shown up in Sentry!

**Comment by Bjwebb** [comment]
https://github.com/OpenDataServices/cove/blob/54607ad/cove_360/lib/threesixtygiving.py#L449

**Comment by Bjwebb** [comment]
@ekoner This should be fixed now.
