### ISSUE TITLE
Cove home page

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#615]
We have a sort of "home page" for Cove at http://cove.opendataservices.coop/ signposting people to the OCDS and 360 versions.

As part of our recent app separation work, Cove no longer hosts this page. http://dev.cove.opendataservices.coop/ now redirects to the OCDS dev copy of Cove, because the 360Giving dev copy is on a different server at http://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io
I think this is okay for the dev site, but we probably don't want to do that for the live site.

I think we have two choices:
1) Create a simple static site with the current "home page" in it, and continue to host it at http://cove.opendataservices.coop
2) Create a better/updated landing or home page for Cove. ~~This could be the GitHub README, or an improved docs homepage https://cove.readthedocs.io/en/latest/, or a page on the http://opendataservices.coop/ website.~~ A page on the http://opendataservices.coop/ website is probably the best way to do this.  It could also be good to include some info about our IATI work.

The live cove home page is hosted on the old live 360Giving copy, so this needs doing before that's turned off (hopefully May).

**Comment by robredpath** [comment]
As it stands, we don't really do much with CoVE as a product in its own right - when we carry out work on it for someone, or provide a hosted version for someone, it's usually as part of a wider piece of work that we're doing that's come out of our relationship with them. 

I'd be in favour of us showcasing it on our website.
