### ISSUE TITLE
Deploy latest version & keep up-to-date

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#618]
It's much easier for people to try things out and give feedback if they can go to a website and use it. We should make that happen!

**Comment by Bjwebb** [comment]
http://602-convert-upload.dev.cove.opendataservices.coop/
WARNING: this is a very early dev deploy that may say ridiculously untrue things, e.g. that all data is valid.

**Comment by Bjwebb** [comment]
http://619-initial-style-iati.dev.cove.opendataservices.coop/
