### ISSUE TITLE
Initial styling

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#619]
Some basic styling to make this look clean and professional, and not like any of the standards that we work with - this isn't a product of the IATI Secretariat and so can't carry the IATI logo or branding.

**Comment by edugomez** [comment]
Bootswatch's Sandstone theme

![cove_iati_bootswatch_sandstone_theme](https://cloud.githubusercontent.com/assets/5618508/24718908/b0d437d4-1a2f-11e7-89fa-db86b0848d2c.png)

**Comment by robredpath** [comment]
That looks pleasantly un-like anything else we have, and is nice and clean. I like it!

**Comment by Bjwebb** [comment]
http://619-initial-style-iati.dev.cove.opendataservices.coop/
