### ISSUE TITLE
Data Quality Tool: Email check is only looking for @ not emails

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#626]
I've noticed that the DQT flags any rows that have an @ sign. This means checking in files for emails only to find none. Please can it check for actual emails?

**Comment by robredpath** [comment]
Thanks for reporting this, @ekoner . The decision to just match on '@' was a trade-off between performance, code complexity and accuracy - we assumed that an @ in certain fields would rarely happen if it wasn't an email address. The fact that this has come up so early means that we got that trade-off wrong, so I've categorised it as release-blocking.

**Comment by Bjwebb** [comment]
We're now matching on a "word" with an `@` and a `.` in it.
