### ISSUE TITLE
Add conversion to CSV support

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#63]
We need to think about whether it's possible to offer a single CSV download sometime, or whether this should always be multiple downloads, or a zip of CSVs etc.

**Comment by timgdavies** [comment]
A single CSV (based on the default Roll Up settings in the Schema) would be a very desirable output format. 

I believe this would make it quite easy to then, for example, embed recline.js into a CoVE page as a means of exploring a summary of the data which has been entered, which could be a nice feature.

**Comment by robredpath** [comment]
Closing - it's likely that we'll want similar functionality pretty soon, but we can address that when it comes up.
