### ISSUE TITLE
'Did you mean X?' - suggesting alternatives for additional fields

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/cove#637]
At the moment we report additional fields to users.

Often these are typos of fields we already have in the schema.

It would be useful to test, and explore the value of a feature, which would run a sounds-like algorithm - to suggest to people whether we already have a relevant additional field...

**Comment by edugomez** [comment]
@Bjwebb I added this issue to ODS non-sprint board. Any reason for reopening here?

**Comment by Bjwebb** [comment]
Useful to also have an issue that's visible to the public.

**Comment by edugomez** [comment]
Ah, OK.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Try to identify mis-spelled additional fields](https://trello.com/c/1VsIpKX7/33-try-to-identify-mis-spelled-additional-fields)
