### ISSUE TITLE
360: Open / close all drop downs

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#640]
It seems cumbersome to open/close each drop down individually

Is there a "open all" "close all" function that can be added?

**Comment by Bjwebb** [comment]
I'm looking at this as part of https://github.com/OpenDataServices/cove/issues/638

**Comment by stevieflow** [comment]
This is done now? Can be closed @Bjwebb ?

**Comment by edugomez** [comment]
@stevieflow yes indeed
