### ISSUE TITLE
360 Additional Checks: "One or more of your grants..."

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#645]
Looking at https://dataquality.threesixtygiving.org/data/7814a6c6-78a8-4b92-b0a3-d8e392a793d2

eg: 

> One or more of your grants have a Recipient Org:Identifier that is has a prefix of '360G'.

Do we count these though?  It would be more helpful to give the exact number of instances we found

I spotted we provide a count on 

> 1693 of the grants do not contain any beneficiary location fields. 

But Im unclear if this is because it is ALL records

**Comment by edugomez** [comment]
Issue dealt with in this [PR#654](https://github.com/OpenDataServices/cove/pull/654) (which at the time of writing this comment fails to pass build tests for reasons unrelated to the code in the PR)
