### ISSUE TITLE
State on the explore page when a file is going to be deleted

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#65]
From https://github.com/OpenDataServices/cove/issues/38

We need to put a message on the 'explore' page showing when a file will be deleted (and that that URL/page will be come a 404 once the file is deleted) ( we might also show 'time until deletion', but this is not necessary.

**Comment by caprenter** [comment]
There is a message now
"
Save or Share these results
These results will be available for 7 days from the day the data was first uploaded. You can revisit these results until then.

After 7 days all uploaded data is deleted from our servers, and the results will no longer be available. Anyone using the link to this page after that will be show a message that tells them the file has been removed."

It would be nice to have a date and time - but we know this is not exact.

Perhaps 'this file was uploaded on...', and then 'files are kept for 7 days..... might be ok
