### ISSUE TITLE
Additional Checks section:  make counts clickable to see all instances

### ISSUE THREAD

**Issue by edugomez** [OpenDataServices/cove#655]
Derived from now close https://github.com/OpenDataServices/cove/issues/549

**Comment by stevieflow** [comment]
#360 looks specifically at the counts clickable

**Comment by stevieflow** [comment]
(as in issue #360 , not the 360 in general!)

**Comment by Bjwebb** [comment]
This is now on dev: http://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io/
