### ISSUE TITLE
Invalid whitespace in uris is not communicated well

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#657]
Uploading a spreadsheet with extensions specified in the ```Meta``` tab results in a validation error listing the extension.json urls ([example](http://dev.cove.opendataservices.coop/validator/data/1b1d063a-94f8-4dc8-aa00-8fd8ed837c91))

![image](https://cloud.githubusercontent.com/assets/19265814/25476967/cf71e5f0-2b33-11e7-8f5d-8ddb44d545b5.png)

**Comment by duncandewhurst** [comment]
@edugomez fyi

**Comment by Bjwebb** [comment]
The problem here is actually the spaces in front of the urls. If you remove the spaces after `;`, then it should validate.

**Comment by jpmckinney** [comment]
Based on @Bjwebb's comment, Is this issue invalid?

**Comment by robredpath** [comment]
I feel that whitespace around URLs is an error that 'Invalid uri found' doesn't really communicate very well - as the URI looks fine when presented back to the user. This could tie into a further iteration of #951 . 

We could rename this issue to be about whitespace around URIs?

**Comment by yolile** [comment]
I agree in that the problem is not communicate very well, another example here: http://standard.open-contracting.org/validator/data/118cc67d-841c-48e5-bf6b-6a25fca1b7a7

**Comment by jpmckinney** [comment]
This could be a candidate for the Apr-May 2019 sprint.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Invalid whitespace in uris is not communicated well](https://trello.com/c/8LELhi7h/45-invalid-whitespace-in-uris-is-not-communicated-well)

**Comment by rhiaro** [comment]
We could add additional text to the message so it says "Invalid 'uri' found (should not contain spaces)". We could either do this universally (so it shows regardless of the cause of the error) or conditionally on the detection of whitespace in the URI.

Text for this validation error currently lives in [lib-cove/lib/common.py](https://github.com/OpenDataServices/lib-cove/blob/master/libcove/lib/common.py) and we could add the whitespace check in [here](https://github.com/OpenDataServices/lib-cove/blob/master/libcove/lib/common.py#L694) somewhere if we do that. 

This would affect all CoVEs, not just OCDS.

**Comment by jpmckinney** [comment]
Yes, I agree (as @rhiaro mentioned on Trello) that simply wrapping the URL in quotes won't make the extra space(s) obvious to users.

Regarding the error message: does the error occur if there are spaces *anywhere* in the URL? If so, then it's fine. The example in the issue description had spaces only before/after, so I wasn't sure.

**Comment by robredpath** [comment]
> Regarding the error message: does the error occur if there are spaces anywhere in the URL? If so, then it's fine. The example in the issue description had spaces only before/after, so I wasn't sure.

Yes, I've just given this a quick test and spaces do cause the 'uri' type check to fail even in the middle of an entry

It's fine for this to apply to all CoVEs

I like the idea of specific whitespace detection. Could we make it so that leading/trailing whitespace is detected separately, so that we can guide people closer to the particular issue that they've had? I think that an error message talking about spaces when it's not clear in the interface that spaces have been detected is better than what we have now, but still not amazingly helpful.

**Comment by robredpath** [comment]
Moved to https://github.com/open-contracting/cove-ocds/issues/93
