### ISSUE TITLE
Additional Checks mixing up multiple funders and multiple recipients

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#666]
> There are 8 funding organisation IDs listed
If you are expecting to be publishing data for multiple funders then this notice can be ignored, however if you are only publishing for a single funder then you should review your Funder ID column to see where multiple IDs have occurred. 

> Review your data.
The table below shows your data after it has been processed .

    Grant identifiers:  10
    Funder organisation identifiers:  1
    Recipient organisation identifiers:  8

- There were 8 recipient organisations not 8 funding organisations. 
- The "First 3 Locations" is blank.

**Comment by edugomez** [comment]
@ekoner Can you send me a link with the data you have used to get those results?

**Comment by robredpath** [comment]
@edugomez see internal issue #9367

**Comment by edugomez** [comment]
This is fixed in PR https://github.com/OpenDataServices/cove/pull/665
