### ISSUE TITLE
360 : Addition checks - First 3 Locations ;;;;

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#671]
As per https://dataquality.threesixtygiving.org/data/01b2c880-9379-4f2e-a3c5-d75a4954b581 we list the first three locations for any additional checks, which is helpful

Do we store / have access to all the locations, however?

If so, it might be useful to provide access to a full list, somehow

**Comment by robredpath** [comment]
I'm creating an internal ticket to schedule some time in the next couple of months to attend to this.

**Comment by Bjwebb** [comment]
I think this has been taken forward in https://github.com/OpenDataServices/cove/pull/813
