### ISSUE TITLE
360 : Intro blurb for Additional checks

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#672]
We should insert some static text above the Additional Checks table, to introduce them, stress that they are not schema errors, and (pending on #643) link to a list of all checks

**Comment by robredpath** [comment]
"After validation, we have performed some additional checks on the data to identify potential issues that may affect how useful the data is, or that might indicate an issue with the source data. These are not errors, and can be ignored if they're not relevant" 

How's that for copy, @stevieflow ?

**Comment by KDuerden** [comment]
Additional checks have been made on the data. Some checks highlight areas where the source data may be incorrect or require further attention. Some checks suggest ways to increase the usefulness of the data. 
These checks do not indicate Validation errors, and can be ignored if they are not relevant. 

Tweaked, but please feel free to further refine.
