### ISSUE TITLE
360 CoVE: 0 value grants not showing in data summary

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#673]
I think this applies to both versions of 360 CoVE

Wolfson have some grants that have a value of £0

In new CovE, we dont declare this:

https://dataquality.threesixtygiving.org/data/705a0514-7f33-455f-9093-1da397e51135

> ranging from £5,000 (lowest) to £3,000,000 (highest).

Same in old CoVE:

http://cove.opendataservices.coop/360/data/f3362ce2-36a8-4cfa-b081-8c283be7c5d2

> Highest Award Amount: 3000000 
> Lowest Award Amount: 5000 

Would there be a reason for this?

**Comment by Bjwebb** [comment]
This is happening here: https://github.com/OpenDataServices/cove/blob/master/cove_360/lib/threesixtygiving.py#L58

I suspect we thought these would be the more useful numbers, and that zero value awards aren't really awards. Zero value grants are reported separately in an additional check:
> **114 grants have a value of £0**
> It’s worth taking a look at these grants and deciding if they should be published. It’s unusual to have grants of £0, but there may be a reasonable explanation. Additional information on why these grants are £0 might be useful to anyone using the data, so consider adding an explanation to the description of the grant.

**Comment by KDuerden** [comment]
Thanks Ben - it is useful to have this background.
I agree it is more useful to have numbers than zeros in the summary text, so happy with the choice you made.
