### ISSUE TITLE
OCDS: Check ocid prefixes

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/cove#675]
We should have introduce an ```ocid``` prefix check during validation of OCDS data.

**Comment by duncandewhurst** [comment]
+1 to this - feedback from OCP is that it doesn't make sense for a file to validate when no ocid prefix is used

**Comment by robredpath** [comment]
Is the ask here for a check against the register of ocids or a check that the ocid is of a valid form? @timgdavies @duncandewhurst ?

**Comment by duncandewhurst** [comment]
Both please, so a check first that it is of valid form and a check second against the ocid prefix google sheet (checking against the CSV version so that in future a different CSV could be substituted if we move to a different registration method)

**Comment by robredpath** [comment]
Thanks @duncandewhurst . Is it still useful with just a format check? Talking to an external (hosted) list is a new step that needs quite a bit of thinking about to do well (eg what do we do if it's down? slow? misformatted? do we cache? ) . We can do it, but it'll push something else back, so trying to gauge priority

**Comment by timgdavies** [comment]
This could definitely be split into two parts, with a format check, and then later on a list check.

**Comment by robredpath** [comment]
Prep required is to get agreement that a format check is a sufficient first step

**Comment by robredpath** [comment]
We're thinking of starting a warnings box (probably not called that), in which this would be a useful first entry.

**Comment by robredpath** [comment]
We still need to decide on the name of the box. In #947 I suggested 'Quality Factors', but I'm not sure.

**Comment by edugomez** [comment]
What about 'Quality Warnings', which will have 4 headers:

_Field - Value - Warning - Path to field_

For ocds prefixes it will be e.g:

_ocid, ocds-bad-123456, The Open Contracting ID contains a malformed OCDS prefix, releases/0/ocid_

**Comment by robredpath** [comment]
@edugomez let's give it a try and see what people think! If you could post some screenshots we can get a couple of friendly users to take a look and see what they think

**Comment by edugomez** [comment]
```id```s in objects in the standard can use the ```ocid``` as its value, so if the prefix in ```ocid``` is wrong  it will wrong in the ```id``` too. Do we need to check for ```id```s prefixes too?

**Comment by Bjwebb** [comment]
I would think just checking the `ocid` for now should be fine.

**Comment by timgdavies** [comment]
I'm working on a language review across the validator, but I *think* we would want to put these under a conformance heading, rather than quality.

I'm also thinking that, in the **majority of cases**, if one `ocid` is wrong, all will be, so our presentation might want to hide the table of individual errors and their paths unless the user expands this. 

In the mock-up below I've tried just putting the schema definition of `ocid` in, to see if including these within the validator is enough to give the user actionable information about what to do next. If we do use this, we should pull it from the schema as SSOT. 

| Conformance (rules) | 
|--------------------------------------------------------------------------------|
| *Fixing the following issues will improve the interoperability of your data.* |
| [ 27 ] of your `ocid` fields have a problem: there is no prefix or the prefix format is not recognised. |
| > **What is the `ocid` field?** A globally unique identifier for this Open Contracting Process. Composed of a publisher prefix and an identifier for the contracting process. For more information see the [Open Contracting Identifier guidance](http://standard.open-contracting.org/latest/en/schema/identifiers/). |
| [ + ] View all errors |

**Comment by edugomez** [comment]
![ocid-close](https://user-images.githubusercontent.com/5618508/35929426-6277cc00-0c27-11e8-8d6b-ff3fa2173a6e.png)

**Comment by edugomez** [comment]
![ocid-open](https://user-images.githubusercontent.com/5618508/35929494-8707e8e8-0c27-11e8-9eb0-addaef738592.png)

**Comment by timgdavies** [comment]
Great :) I will give some thought to the box heading, but I like the layout and interaction.

**Comment by jpmckinney** [comment]
I can't tell if this issue is closed given the commits, but it could be a good candidate for the Apr-May 2019 sprint.

**Comment by robredpath** [comment]
Closing, as this issue is long. Format checking currently happens. A list check could be a good next step,  so I'll create an issue for that.
