### ISSUE TITLE
Typo in procuring entities modal in OCDS Validator

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#680]
There is a typo in the modal which appears when you click ```Procuring Entities``` in the ```Key Fields``` section of the OCDS Validator results:

![image](https://cloud.githubusercontent.com/assets/19265814/26144856/65afc0f6-3ae2-11e7-8f52-2184e195605e.png)

**Comment by robredpath** [comment]
This was fixed in #689 and will be on the live CoVE on the next deploy.
