### ISSUE TITLE
1% of your grants have a Funding Org:Identifier that doesn’t draw from an external identification body

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#681]
https://dataquality.threesixtygiving.org/data/31f133fc-5a91-4b3d-9cd7-cc8aa7206cab

I'm not sure the percentage calculation is intended?  Is that a typo @edugomez ?

**Comment by stevieflow** [comment]
NB: the additional check is correct - but it's only one record has a Funding Org:Identifier in this format

**Comment by edugomez** [comment]
I just looked at the code and the intention was to give a percentage, but **rounded** (ie 1 grant out of 70 grants c. 1.43% -- > 1% rounded), but I understand it is misleading. Would you like any changes on this?  It would be easy to change.

**Comment by stevieflow** [comment]
Thanks @edugomez 

I think absolute count, in line with other tests, would be more easy to comprehend for people - so would welcome any change

**Comment by edugomez** [comment]
@stevieflow that sounds good

**Comment by robredpath** [comment]
Worth noting that there are a few checks that are %s - I was inconsistent when writing the specs for these based on my ideas at the time of what would be more useful but I now think that we should use absolute count in all cases. My intention with %s was to give some idea of the scale of an issue (is 10 grants with bad identifiers a big issue? depends on how many grants you have!)  but I now don't think that's a good way of communicating that.

**Comment by stevieflow** [comment]
> what would be more useful but I now think that we should use absolute count in all cases. My intention with %s was to give some idea of the scale of an issue

I do think this is also a great idea btw @robredpath 

Maybe we have scope for both in a single additional check.  eg:

> 7 of you grants have this thing.  This is 3% of all your grants
> Here's a longer description
