### ISSUE TITLE
Metatab round trip

### ISSUE THREAD

**Issue by rory09** [OpenDataServices/cove#683]
I chatted to Rob yesterday and he mentioned that the metatab is currently implemented from flat to unflat, but not vice versa. This presumably means that the data aren't completely 'round tripable' i.e. if I converted an excel file and specified that it should be in version x, then converted it back, there wouldn't be a metatab with the version in it.

Is this correct? If so, is there a plan to add this functionality at some point? Thanks

**Comment by edugomez** [comment]
@rory09 That is correct.

> If so, is there a plan to add this functionality at some point?
 
I don't think that specific feature is in the pipeline yet.

**Comment by rory09** [comment]
Thanks @edugomez - would you like it put in a particular place i.e. non-sprint issues?

**Comment by edugomez** [comment]
@rory09 I think as an issue here is fine. Although I don't think this is as needed as the current 'one way' excel > json, the lack of symmetry seems kind of wrong.

**Comment by Bjwebb** [comment]
Corresponding flatten-tool issue: https://github.com/OpenDataServices/flatten-tool/issues/176

**Comment by jpmckinney** [comment]
✅ From OCP's perspective, this issue can be closed / 'OCDS' tag can be removed, because this is a flatten-tool issue, not a CoVE issue.
