### ISSUE TITLE
Repeated <iati-activity> elements in multi-sheet unflatten

### ISSUE THREAD

**Issue by rory09** [OpenDataServices/cove#686]
I've deployed an instance of IATI cove via the openag docker package (by following [these instructions](https://github.com/neontribe/AG/blob/develop/INSTALL.md) - requires manual install of docker.io). 

It appears to be running exactly as our deployed branch which went down recently.

When I try to convert a simple dummy file, I'm getting lots of unwanted `<iati-activity>` parent elements.

I'm fairly sure I've set up the spreadsheet correctly, but I might not have. 

This issue happens in both multi-sheet and single sheet inputs:

|       Type       |                                                                       Input File                                                                        |            Output             |
|------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------|
| Multi-sheet      | [this downloaded as xlsx](https://docs.google.com/a/opendataservices.coop/spreadsheets/d/1zNTJkuj3etkCYaxV69bS_izstGzJEqVI-6v4PDOFY6U/edit?usp=sharing) | https://pastebin.com/NBpzQpaT |
| CSV Single Sheet | [this downloaded as csv](https://docs.google.com/a/opendataservices.coop/spreadsheets/d/1UxFkRvTMffMZBR00rZs1Bc--aSaQNSkYYDAN4uqZJe8/edit?usp=sharing)  | https://pastebin.com/sN3NxsZe |

**Comment by rory09** [comment]
Just tested this again with the following results:

Using http://635-sort-xml.dev.cove.opendataservices.coop: 

|       Type       |                                                                       Input File                                                                        |            Output             |
|------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------|
| Multi-sheet      | [this downloaded as xlsx](https://docs.google.com/a/opendataservices.coop/spreadsheets/d/1zNTJkuj3etkCYaxV69bS_izstGzJEqVI-6v4PDOFY6U/edit?usp=sharing) | http://635-sort-xml.dev.cove.opendataservices.coop/data/1e863fff-156d-43ce-98b4-702b451d85aa |
| CSV Single Sheet | [this downloaded as csv](https://docs.google.com/a/opendataservices.coop/spreadsheets/d/1UxFkRvTMffMZBR00rZs1Bc--aSaQNSkYYDAN4uqZJe8/edit?usp=sharing)  | http://635-sort-xml.dev.cove.opendataservices.coop/data/0c1911e0-9d7e-40f2-86fe-9bbd59d56a39 |

These are still not producing correct output, I'm afraid. Please let me know if you need any further information or are having trouble replicating the error.

**Comment by kindly** [comment]
Sorry, the fix was never put on the live branch. 

It is done now i.e:

http://635-sort-xml.dev.cove.opendataservices.coop/media/16fe7e2f-ec1e-4b93-afcb-6234bab1b831//unflattened.xml
