### ISSUE TITLE
Contents of file appearing in box heading / bad file can break Explore table

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#690]
Contents of file seem able to appear in headings in some kind of broken files: 

![screen shot 2017-05-25 at 13 18 00](https://cloud.githubusercontent.com/assets/641009/26449876/9e636fc2-414c-11e7-8182-31b5aa5b377d.png)

This is on the live validator, running version 1b04e60 , using https://github.com/OpenDataServices/cove/blob/master/cove_ocds/fixtures/full_record.json

**Comment by Bjwebb** [comment]
I've fixed that heading in https://github.com/OpenDataServices/cove/pull/752

I don't think the explore table is actually broken - this is the record explore page, which looks different to the release explore page.

**Comment by Bjwebb** [comment]
The heading issue is fixed on dev now: http://dev.cove.opendataservices.coop/validator/data/8ad7467b-969c-4c01-925d-c64d4b88b2bd
