### ISSUE TITLE
Add call to action in the Validator example errors column

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#692]
Copied over from https://github.com/open-contracting/standard/issues/458 :

"When there are errors in the validation, the error count column shows the errors for the row.
However, the number does not look like a link.
Perhaps a call to action is needed or format the number to look like a link"

There are also some comments where useful suggestions are made. 

cc: @juanpane @edugomez @yolile

**Comment by jpmckinney** [comment]
Under what condition does a link appear? The proposals in the original issue were to add an icon (the icon commonly used on Wikipedia and elsewhere for 'external link' or 'new window') or to add the text "(see all)".
