### ISSUE TITLE
OCDS Validator: Typo in 'Additional Codelist Values' box

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#697]
When validating against OCDS V1.1 there is a typo in the following paragraph ("your" should read "you")

> Make sure **your** list the definition of any additional codelist values you include within your publication policy, and if you believe they should be added as recommended values in the open codelist, please suggest this via the OCDS issue tracker.

**Comment by robredpath** [comment]
This is fixed in #699
