### ISSUE TITLE
OCDS Validator: Internal server error when null specified in extensions array

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#714]
The OCDS Validator returns an [internal server error](http://standard.open-contracting.org/validator/data/f14cebb7-86be-43bb-971b-2ec05dab7f86) when trying to validate [this file](https://gist.githubusercontent.com/duncandewhurst/004c8c5e3da3425f7a19d9f11ba2d5c7/raw/85eabf99b002d491fdb6a5b4bc096893b2eb6723/nsw_fixed_version.json) which includes the following extensions array:

```json
"extensions": [null, "https://tenders.nsw.gov.au/public_data/API/NSW-eTendering-API-release-schema.json"],
```

The error doesn't occur when ```null``` is removed from the extensions array.

Could we provide a more informative error message?

**Comment by edugomez** [comment]
@duncandewhurst There's already an issue for this https://github.com/OpenDataServices/cove/issues/713, so I'm closing this one
