### ISSUE TITLE
Add a test for pulling data from extension and displaying to user

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#720]

**Comment by jpmckinney** [comment]
What is this issue about?

**Comment by Bjwebb** [comment]
I think this is about testing e.g. the description of the extension is pulled out and displayed properly. This is now tested https://github.com/OpenDataServices/cove/blob/6d64b45a4b5c3610565e1d189d2a9416ef56bcf6/cove_ocds/tests_functional.py#L195
