### ISSUE TITLE
IATI CoVE doesn't put a version attribute into converted XML

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#721]
@stevieflow tells me that he's converted some data, and it failed validation because of version issues.

**Comment by robredpath** [comment]
ping @rory09

**Comment by Bjwebb** [comment]
You can supply a the version attribute in a Meta tab.

ie. a tab called "Meta" with the following contents:

![image](https://user-images.githubusercontent.com/634/27681258-8dca06f0-5cb6-11e7-8f97-cacf918f9cfe.png)

There's no CoVE user facing documentation for this atm, which is a problem. There is some [flattentool metatab](https://flatten-tool.readthedocs.io/en/latest/unflatten/?highlight=meta#metadata-tab) docs though.

**Comment by stevieflow** [comment]
I think we know how to do this now, so can close the issue.  
There's a wider an issue in terms of documentation, but should be in new issues
