### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#737]
On https://dataquality.threesixtygiving.org/ the links to Excel (2 of them) and CSV and are broken:

> Formats

> The application accepts data in some of the formats given in the 360Giving Data Standard guidance.
Acceptable files are:

>    Summary Spreadsheet - Excel, CSV (UTF-8, Windows-1252 and ISO-8859-1 encodings supported)
>    JSON built to the 360Giving JSON schema (UTF-8 encoding supported)
>    Multi-table data package - Excel"

This is because of the change over at the standard repo for 360: https://github.com/ThreeSixtyGiving/standard/pull/179

**Comment by caprenter** [comment]
Is this a case of re-pointing to the legacy branch @Bjwebb or is there a better place to point now?

**Comment by Bjwebb** [comment]
There's a better place now:
Excel: https://threesixtygiving-standard.readthedocs.io/en/latest/_static/summary-table/360-giving-schema-titles.xlsx
CSV: https://threesixtygiving-standard.readthedocs.io/en/latest/templates-csv

**Comment by caprenter** [comment]
And if we fixed that now, then we might also need to change again later as those URLs are likely to change in the coming months?

**Comment by Bjwebb** [comment]
I think those urls are likely to continue to work, but we'd prefer the new ones under a threesixtygiving.org subdomain

**Comment by Bjwebb** [comment]
This is now deployed on the live site https://dataquality.threesixtygiving.org/
