### ISSUE TITLE
Update pages to be ready to be put live

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#75]
To get a version live for 360 use:
(1) Add alpha banner - with link to GitHub issues
(2) Update explanatory text (some links need updating) and add 360 logo to explanation
(3) Replace front page a / with logos of OCDS and 360Giving logos

**Comment by Bjwebb** [comment]
Now that https://github.com/OpenDataServices/cove/pull/76 is merged and live ( http://cove.opendataservices.coop/ ), 1) and 3) have been done.

@timgdavies is 2) also complete, or is this still updating. (I'm not sure what links needed updating, and where the 360 logo should be, besides the front page).

**Comment by caprenter** [comment]
I think we can close this now as the alpha site is out there, and links are being worked on in #82 and #83
