### ISSUE TITLE
Cant get document-date to work

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#754]
Have this column:

`document-link/0/document-date/@iso-date`

This throws CoVE: http://iati.cove.opendataservices.coop/data/f6475205-7848-40ba-b746-e01b3f44aa19

If I remove the column, all is fine http://iati.cove.opendataservices.coop/data/d526050a-a337-4ca2-9c0f-e83986f65373

**Comment by Bjwebb** [comment]
Merged in to https://github.com/OpenDataServices/cove/issues/755
