### ISSUE TITLE
We always use the 2.01 schema

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#755]
I have these columns: 

### `budget/@status`

My metadata is set to 2.02

AFAIK, this attribute is allowed in 2.02: http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/budget/#iati-activities-iati-activity-budget-status

On uploading, I get a validity error: http://iati.cove.opendataservices.coop/data/47ec6840-5c86-45a2-bfb9-8824c946c360

> 
> 'budget', attribute 'status': The attribute 'status' is not allowed.	1	
> ement
> iati-activity/0/budget/@status
> Sheet: Basics Row: 2 Column: budget/@status
> 

If I remove this column, all is fine: http://iati.cove.opendataservices.coop/data/09e3c27c-68b1-4497-b1d3-bc7ce13e58c6

### `document-link/0/document-date/@iso-date`

This throws CoVE: http://iati.cove.opendataservices.coop/data/f6475205-7848-40ba-b746-e01b3f44aa19

If I remove the column, all is fine http://iati.cove.opendataservices.coop/data/d526050a-a337-4ca2-9c0f-e83986f65373

**Comment by stevieflow** [comment]
If I remove this column, all is fine: http://iati.cove.opendataservices.coop/data/09e3c27c-68b1-4497-b1d3-bc7ce13e58c6

**Comment by Bjwebb** [comment]
This is happening because all conversion/validation is using the 2.01 schema at the moment.

A first step would be to switch to 2.02.

A further step would be to autodetect correctly.

**Comment by stevieflow** [comment]
> A further step would be to autodetect correctly.

#727

**Comment by stevieflow** [comment]
@Bjwebb are we at 2.02 now?  Can this be closed?
