### ISSUE TITLE
Add db field to store "version" value in OCDS original data. 

### ISSUE THREAD

**Issue by edugomez** [OpenDataServices/cove#759]
At the moment, we only store the last schema version applied to the stored data as `schema_version`, which is the version we use to re-validate the data when accessing the data URL in cove.

**Comment by robredpath** [comment]
Sorry, @edugomez , I don't understand what the issue is! Could you expand a bit, or given an example of how this causes the wrong behaviour?

**Comment by edugomez** [comment]
@robredpath sure. Imagine I upload this file:
```
...
"version": "1.1"
"releases" : [...
"
The file gets validated. Then I change the version in the interface to "1.0" and the file gets validated against  that version. Now, I send you the URL. When you go to that URL you are going to see a validation against "1.0" not "1.1", even though "version" in the data says "1.1"! Probably, the suggestion in this issue is the easiest way to solve this.

Also, it would allow us to store the "version" field value people are using in their data without having to open the stored file (which anyway will disappear in 7 days, therefore not a possibility thinking of future analysis)

**Comment by edugomez** [comment]
This issue gets a bit complex when taking into account conversions, e.g. I can upload json with ```"version": "1.1"``` in it, switch to version "1.0", convert to spreadsheet and then send the link to a friend. I wonder if that ever would happen, but it is possible in principle.

I think the best thing here is to keep the current behaviour (i.e. any changes of version in Cove -- affecting the corresponding conversion -- will be reproduced when visiting the URL) adding an explanation of what that behaviour is.

Closing this one and opening new issue #921
