### ISSUE TITLE
OCDS Validator: Sample data link broken on "Sorry we can't process that data" page

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#765]
The following link on the OCDS Validator is relative, so it breaks when clicked on the "Sorry we can't process that data" page ([example](http://standard.open-contracting.org/validator/data/af449fbb-f88c-49d9-84c7-abcdb40cefe5)):

> To preview how the validator works, try **loading some sample data.** 

I *think* [this PR](https://github.com/OpenDataServices/cove/pull/764) should fix it.

**Comment by Bjwebb** [comment]
This should now be fixed on the dev site, e.g. http://dev.cove.opendataservices.coop/validator/data/b4d7ff4c-2b30-4319-9dde-05dd92cb3cdc
