### ISSUE TITLE
Rulesets - First Iteration 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#774]
- Use Gherkin
- Use @andylolz IATI ruleset implementation 
- Just IATI standard rulesets
- Display results to user in a vaguely friendly way

**Comment by robredpath** [comment]
https://github.com/pwyf/bdd-tester/tree/master/features/iati_standard_ruleset

**Comment by robredpath** [comment]
https://github.com/pwyf/bdd-tester/tree/master/sample_features/iati_standard_ruleset

**Comment by edugomez** [comment]
Related to https://github.com/OpenDataServices/cove/issues/702
