### ISSUE TITLE
360 CoVE - header for navigation

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#779]
We should consider / implement a header that can link users back from 360 CoVE to the documentation and main site

@morchickit - take a look at OCDS example: http://standard.open-contracting.org/validator/

linked to https://github.com/OpenDataServices/cove/issues/778

**Comment by morchickit** [comment]
Sure, sounds good and should be easy to implement, no?

**Comment by stevieflow** [comment]
@morchickit the devil is in the detail!

So - thinking of a 360 "header"

- what style does this take?
- we have no language support , so that would be out?
- do we include the link to "Standard Documentation" in the same way as OCDS?  If not, how? What do we call it?  
- OCDS, it seems - call this Validator a beta.  Is that the case for 360?

Ideal, I would imagine - would be a mock up of this header.

**Comment by stevieflow** [comment]
ping @morchickit

**Comment by morchickit** [comment]
Sorry!
To the issue - I just realised that the 360Giving logo on the current COVE site leads to nowhere. 

So my thoughts:
- We need to get rid of the Alpha header. Why do OCDS call it beta? You guys are to coders, can you tell me why it says Alpha? We use it for quite a while now so calling it beta seems odd. 
- Add the logo which will lead to 360Giving homepage
- We dont need a language button like in Open Contracting, instead we can add the word Standard and link to the documentation?

**Comment by stevieflow** [comment]
> We need to get rid of the Alpha header. Why do OCDS call it beta? You guys are to coders, can you tell me why it says Alpha? We use it for quite a while now so calling it beta seems odd.

https://github.com/OpenDataServices/cove/issues/778

@morchickit in terms of the link, then the text for "360Giving" data leads back?

So - potentially - the *only* aspect to sort here is the link to the documentation?

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Logo to link to homepage](https://trello.com/c/LfVjKcsr/115-logo-to-link-to-homepage)

**Comment by BibianaC** [comment]
@morchickit would the link go to the main [page](https://www.threesixtygiving.org/)?

**Comment by morchickit** [comment]
Indeed!

**Comment by morchickit** [comment]
but @KDuerden - can you confirm?

**Comment by KDuerden** [comment]
Yes, that sounds great. thank you!

**Comment by BibianaC** [comment]
@KDuerden @morchickit @stevieflow this has been done and deployed.
