### ISSUE TITLE
Sample data does not validate

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#78]
Sample data in:
https://github.com/open-contracting/sample-data
e.g. https://raw.githubusercontent.com/open-contracting/sample-data/master/fictional-example/ocds-213czf-000-00001-04-award.json

gets reported as not valid against the schema.

It's unclear where the problem lies at the moment:

**Comment by timgdavies** [comment]
Some of the problem is certainly with that file. Just checked against http://ocds.open-contracting.org/validator/validate/ and it seems I've used strings where there should be numbers, and have missed some required properties in hand-coding up those examples.

**Comment by caprenter** [comment]
See also: https://github.com/OpenDataServices/cove/issues/46

**Comment by Bjwebb** [comment]
I'm working on this now at https://github.com/open-contracting/sample-data/pull/3

**Comment by Bjwebb** [comment]
The sample data now validates. The sample-data repository now tests for this using jsonschema on travis: https://github.com/open-contracting/sample-data/pull/3#issue-106520463
