### ISSUE TITLE
Update error messages that may show on IATI CoVE not to say JSON

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#780]
E.g. internal issue 10389

**Comment by robredpath** [comment]
Related: the README assumes JSON, and our `UnrecognisedFileType` exception message lists supported filetypes as "json, csv and xlsx". 

For the "failed to convert..." message, just making it generic makes sense. For supported filetypes, it seems a bit harder. Is it worth separating out the exceptions a bit more? That doesn't seem like an overly difficult thing, but I'm open to correction....
