### ISSUE TITLE
Duplicate release ID

### ISSUE THREAD

**Issue by julijahansen** [OpenDataServices/cove#782]
When passing a JSON file through the validator (results here: http://standard.open-contracting.org/validator/data/9aa25c8f-6cd1-4783-bcff-4298d2cdd458) we noticed that the error count for duplicate release IDs is displaying incorrectly.

![image](https://user-images.githubusercontent.com/30236091/28617111-f96ba9f4-71f6-11e7-940c-5a11838821ee.png)

The problem is that in the JSON file there are 3 release IDs (1, DDC/BKT/CR/073/74/21, 7/073/074), each of which appears multiple times, however in the validator results it shows as Error Count =1 with only one entry for all 3 release IDs. Ideally we would want Error Count to be 3, as there are 3 release IDs that are repeated multiple times, and for all 3 IDs to be shown under First 3 Examples.

**Comment by odscjames** [comment]
With the changes in the new lib, this now looks like:

![screen shot 2018-11-07 at 17 21 56](https://user-images.githubusercontent.com/37832009/48148466-b515e580-e2b1-11e8-9c29-baadd3aad2fb.png)

However, this will eventually affect all client so do we need to check anything there?

**Comment by robredpath** [comment]
@odscjames I think this is the correct behaviour for all our CoVEs. Can you also stick an issue in to write better copy for this validation error?

**Comment by jpmckinney** [comment]
This issue is closed by https://github.com/open-contracting/lib-cove-ocds/pull/1 and a new issue https://github.com/open-contracting/cove-ocds/issues/111 was created.
