### ISSUE TITLE
UTF-16 and UTF-32 JSON support

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#79]
Currently these encodings are not supported, but are valid according to the spec https://tools.ietf.org/html/rfc7159#section-8.1

However, UTF-8 is the default encoding, and the spec  explicitly says that more implementations are likely to support that, and I've only seen UTF-8 so far, so I'm considering UTF-16 and UTF-32 support to be low priority.

**Comment by Bjwebb** [comment]
We can detect UTF-16 and UTF-32 files using this method: https://tools.ietf.org/html/rfc4627#section-3

**Comment by robredpath** [comment]
Closing as we're not going to attend to this in the near future and we communicate that we don't currently support these encodings. If anyone in the community requires UTF-16 or UTF-32 support, please re-open this issue so that we can revisit this!
