### ISSUE TITLE
Expand All / Collapse All in IATI/360 cove does not change arrow up/arrow down in headings   

### ISSUE THREAD

**Issue by edugomez** [OpenDataServices/cove#790]

**Comment by Bjwebb** [comment]
Also affects 360 cove.

**Comment by Bjwebb** [comment]
Fixed now on dev, e.g. http://release-201709.cove-360-dev.default.threesixtygiving.uk0.bigv.io/data/6bd0c8ea-1323-4a63-9d19-ecb70cd3b05e
