### ISSUE TITLE
360Giving CoVE should switch to using the org-id.guide list instead of the IATI register.

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#796]
See https://github.com/ThreeSixtyGiving/standard/issues/210#issuecomment-319090718

We should switch to using the org-id.guide list instead of the IATI register.

**Comment by stevieflow** [comment]
Is this a bit more wider than GB-LAE?  It doesnt recognise http://org-id.guide/list/GB-MPR either.  Is the task to actually get 360 CoVE pulling in the org-id list?

cc/ @KDuerden

**Comment by robredpath** [comment]
@stevieflow yup, that's exactly right. Hence: 

> We should switch to using the org-id.guide list instead of the IATI register.

**Comment by stevieflow** [comment]
Should be noted that this includes both the ``Recipient Org: Identifier`` field and also the ``Funding Org: Identifier`` field

Example of a dataset that uses GB-LAE- for the latter, but gets a warning: https://dataquality.threesixtygiving.org/data/a6ab35cd-62df-41b8-8120-7f23f3987b9f

**Comment by robredpath** [comment]
I've added this to non-sprint so it'll get done in due course
