### ISSUE TITLE
360 CoVE: Additional check for Classifications: Title is wrong?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#800]
We seem to be checking for ``Classification: Title`` whereas the schema has ``Classifications: Title``

This JSON file does have classification in, but CoVE states null: https://dataquality.threesixtygiving.org/data/60485984-1b96-434f-9fc2-2722f15841da

cc/ @KDuerden

**Comment by stevieflow** [comment]
NB: I was trying to establish whether this was a JSON specific issue or more widespread. @KDuerden - know of an spreadsheet example that includes classifications?

@Bjwebb any reason why it should be JSON specific

**Comment by KDuerden** [comment]
Quixote: https://dataquality.threesixtygiving.org/data/ae5bbf1e-3a7c-4762-9f25-02a46423ce56
http://grantnav.threesixtygiving.org/grant/360G-quixote-0063300000kufN9AAI
I first spotted this error when demoing with test data spreadsheet that included the Classifications:Title field (and postcode).

**Comment by Bjwebb** [comment]
This should be fixed on http://release-201707.cove-360-dev.default.threesixtygiving.uk0.bigv.io/. If that now works as expected we can deploy the fix to the live site.

**Comment by stevieflow** [comment]
I do not see that test in the same JSON anymore, so think it's good: 

http://release-201707.cove-360-dev.default.threesixtygiving.uk0.bigv.io/data/3a3c3fc4-db9a-4a6c-816f-38069e590244
