### ISSUE TITLE
360 CoVE aditional check : Incomplete recipient location data - wrong?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#801]
(also linked to observations in https://github.com/OpenDataServices/cove/issues/800 )

This additional check:

> rants have incomplete recipient organisation information
> Your data is missing Recipient Org: Postal Code, Recipient Org: Location:Geographic Code or Recipient Org: Location: Geographic Code Type. Knowing the geographic location of recipient organisations allows users of your data to understand your data and combine it with other data sets to form a broader picture of grant-making.

Present in this test of JSON data, which includes postalCode for recipient orgs: https://dataquality.threesixtygiving.org/data/60485984-1b96-434f-9fc2-2722f15841da

Present in this test of spreadsheet data, which include Recipient Org:Postal Code: 
https://dataquality.threesixtygiving.org/data/28934e3b-3ea0-46cf-a7d0-f6f13383794d

cc/ @KDuerden

**Comment by KDuerden** [comment]
I was curious to see message for data with the geocode & code type but no postcode so tried to load BBC CiN data. I'm getting validation error that means the additional aren't running, but the data does pass validation: https://dataquality.threesixtygiving.org/data/c843d643-fc2e-4449-8f9c-3daeef1bf66e

**Comment by stevieflow** [comment]
@KDuerden I saw that too.  I'll create a new ticket for that, as it's not related to this specific issue.  Thanks

**Comment by Bjwebb** [comment]
Currently the check is that all three of the fields must exist:
* Recipient Org:Postal Code
* Recipient Org:Location:Geographic Code
* Recipient Org:Location:Geographic Code Type

Is this correct?

**Comment by KDuerden** [comment]
My understanding is this is supposed to highlight useful recipient org data
about location, so either Postcode OR Geocode + code type would provide
that. Suggesting an issue if both types of location data are not present
seems like overkill.

**Comment by stevieflow** [comment]
Testing Esmee JSON data

https://esmeefairbairn.org.uk/userfiles/Documents/JSON%20grants%20list/Esmee_Grants_Since_2008.json

2907 grants

This contains a postalCode for a recipientOrganization

However, the CoVE test - http://release-201707.cove-360-dev.default.threesixtygiving.uk0.bigv.io/data/3a3c3fc4-db9a-4a6c-816f-38069e590244 -  still suggests:

> 2907 grants have incomplete recipient organisation information

**Comment by edugomez** [comment]
@stevieflow Sorry, I think there has been some miscommunication here. This issue has been fixed and merged in this PR https://github.com/OpenDataServices/cove/pull/811 but HASN'T been deployed anywhere yet. 

> 2907 grants have incomplete recipient organisation information

That doesn't appear when running the code at the tip of master (e.g. in my local server)

This other PR https://github.com/OpenDataServices/cove/pull/813 also improves 360 Cove by adding a pop up showing all additional check error locations (when they are more than 3, as in the validation section).That hasn't been merged into master yet.

So closing again :)

**Comment by Bjwebb** [comment]
This should be fixed on http://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io/

I'm not planning on including this as part of a bug fix deploy.
