### ISSUE TITLE
360 CoVE: additional checks dont load for one publisher

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#802]
CiN - data loads, passes and converts, but not any additional checks:

https://dataquality.threesixtygiving.org/data/8697ec8f-6373-4387-8472-ce9d8b3a55bd

**Comment by Bjwebb** [comment]
This should be fixed on http://release-201707.cove-360-dev.default.threesixtygiving.uk0.bigv.io/. If that now works as expected we can deploy the fix to the live site.

**Comment by stevieflow** [comment]
Yep  - I got it to work too: http://release-201707.cove-360-dev.default.threesixtygiving.uk0.bigv.io/data/38923dfe-7ca0-45d1-af62-12f46d0c9789
