### ISSUE TITLE
Getting codelists from GitHub fails silently

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#805]
https://github.com/OpenDataServices/cove/blob/master/cove/lib/common.py#L539

Also if one codelist fails, all codelists are ignored.

**Comment by odscjames** [comment]
I've just gone through the repo history and this is probably the line @Bjwebb was originally pointing to: https://github.com/OpenDataServices/cove/blob/501a7a901b7f5818519eb293449f307525771bd0/cove/lib/common.py#L539

**Comment by odscjames** [comment]
This function _load_codelists doesn't exist any more. Instead, load_codelist seems to be doing the actual request, and it does not catch and swallow the error.  https://github.com/OpenDataServices/cove/blob/master/cove/lib/common.py#L732

So not sure what needs doing here now - maybe nothing?

**Comment by odscjames** [comment]
ps. That said, this looks harsh:
```

    reader = csv.DictReader(line.decode("utf8") for line in response.iter_lines())
    for record in reader:
        code = record.get('Code') or record.get('code')
        title = record.get('Title') or record.get('Title_en')
        if not code:
            return {}
        codelist_map[code] = title

```
So if there is any blank line, the whole list is discarded! Wouldn't it be better to just discard the line?

```

    reader = csv.DictReader(line.decode("utf8") for line in response.iter_lines())
    for record in reader:
        code = record.get('Code') or record.get('code')
        title = record.get('Title') or record.get('Title_en')
        if code:
            codelist_map[code] = title

```

**Comment by robredpath** [comment]
@odscjames a blank line in a codelist is ambiguous - is it a mistake? an attempt to allow 'blank' as a value? Failing noisily is, I think, appropriate (and what I think happens here). 

Looks like there's nothing to do on the original issue, so closing.
