### ISSUE TITLE
Validating extension against 1.0 displays "Internal Server Error"

### ISSUE THREAD

**Issue by julijahansen** [OpenDataServices/cove#809]
When you try to validate a file with extensions in the validator tool against 1.0 it gives the following error instead of a warning message:
![image](https://user-images.githubusercontent.com/30236091/29070233-55f1f144-7c36-11e7-8d17-a050fd4d18e4.png)

Could we fix it so it gives e.g. a warning mesage instead of showing Internal Server Error?

When you try to vaidate the same file against 1.1 it does work:
![image](https://user-images.githubusercontent.com/30236091/29070264-78e06eec-7c36-11e7-8a28-4cc16de36c3b.png)

Validator results are [here](http://standard.open-contracting.org/validator/data/58538b01-5ef8-472a-8c79-8148992c3c40 )
And sample JSON file is attached.
[sample_ext.txt](https://github.com/OpenDataServices/cove/files/1207860/sample_ext.txt)

**Comment by Bjwebb** [comment]
The underlying error is:
```
jsonref.JsonRefError: ("Unresolvable JSON pointer: '/definitions/OrganizationReference'", OrderedDict([('$ref', '#/definitions/OrganizationReference'), ('title', 'Related tenderer'), ('description', 'Where this requirement response relates to a tenderer and is provided by the buyer or procuring entity this field should be used to reference the entry in the parties section for the tenderer the response relates to.')]))
```
This is because the extension references `#/definitions/OrganizationReference` which exists in the 1.1 schema, but not the 1.0 schema. Other extensions that don't do this should work fine.

But yes, CoVE should handle this kind of failure more gracefully.

**Comment by Bjwebb** [comment]
This should be fixed on dev: http://dev.cove.opendataservices.coop/validator/
