### ISSUE TITLE
360Giving JSON -> spreadsheet doesn't work as expected

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#818]
* Titles aren't used, instead field names are appended after titles from template
* rollup fields don't appear in the main sheet

**Comment by Bjwebb** [comment]
The underlying flatten-tool issues are fixed in https://github.com/OpenDataServices/flatten-tool/pull/169
Remaining tasks are to pull that into CoVE, and enable rollup.

**Comment by BibianaC** [comment]
@Bjwebb I guess this is done?

**Comment by Bjwebb** [comment]
Yes
