### ISSUE TITLE
360: Acceptable file formats - update guidance

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#83]
Cited:

> Acceptable files are:

>    Summary Spreadsheet - Excel
>    JSON built to the 360Giving Data Standard JSON schema
>    Multi-table data package - Excel

However, a CSV file seems to work well (I havent got other formats to work well just yet).  

Not sure what the solution is - but the current guidance seems inaccurate

**Comment by Bjwebb** [comment]
Yes, single (but not multiple) CSV is an option for input (but not output), see https://github.com/OpenDataServices/cove/issues/62, so the guidance definitely needs updating for that.
