### ISSUE TITLE
Ensure that we can validate data using tag extension

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#835]
http://openagfunding.opendataservices.coop/en/latest/extensions/

Rory's written an extension for 2.02 which allows the use of a tag element, before such an element is introduced into 2.03

We should ensure that we can validate it

**Comment by robredpath** [comment]
Current behaviour is to ignore namespaces for validation. 

We're going to test for the presence and format of tag elements using an additional check

**Comment by robredpath** [comment]
It could be useful for us to consider what could be done with schema, to help demonstrate how IATI extensions could should?) be implemented

**Comment by robredpath** [comment]
@rory09 can you confirm exactly what is and isn't required for the tag extension to be used validly? Are your 'should's meant to mean that it's optional? Do we need to check that codes exist in the vocabulary (we really hope not!)

**Comment by Bjwebb** [comment]
Here's a full example that validates:

```xml
<iati-activities version="2.02" xmlns:openag="http://openagfunding.readthedocs.io/en/latest/extensions/">
 <iati-activity xml:lang="en" default-currency="USD" >
  <iati-identifier>AA-AAA-123456789-ABC123</iati-identifier>
  <reporting-org ref="AA-AAA-123456789" type="40">
   <narrative>Organisation name</narrative>
  </reporting-org>
  <title>
   <narrative>Activity title</narrative>
  </title>
  <description type="1">
   <narrative>General activity description text.  Long description of the activity with no particular structure.</narrative>
  </description>
  <participating-org ref="BB-BBB-123456789" role="1" type="40" activity-id="BB-BBB-123456789-1234">
   <narrative>Name of Agency B</narrative>
  </participating-org>
  <activity-date iso-date="2012-04-15" type="1"/>
  <activity-status code="2" />
  <recipient-country code="AF" />
  <sector vocabulary="2" code="111" />
  <openag:tag vocabulary="99" vocabulary-uri="http://aims.fao.org/aos/agrovoc/" code="c_4397">
      <narrative xml:lang="en">Livestock</narrative>
  </openag:tag>
 </iati-activity>
</iati-activities>
```

**Comment by Bjwebb** [comment]
Here's what an xsd schema for the tag extension could look like:
https://github.com/OpenDataServices/cove/blob/78f7d45ae18da0d67479046e303defb08e1b926f/cove_iati/iati_schemas/2.02/openag.xsd

If we want to validate this by default, then we can just merge this edit to our copy of our schema - https://github.com/OpenDataServices/cove/commit/78f7d45ae18da0d67479046e303defb08e1b926f - no further cleverness required.

A couple of questions about the schema, for @rory09:
* Due to some oddness of namespaces, we can't have an xsd:any for elements, as we would for the standard proper. Is this okay? (I doubt anyone will run into this).
* I've based the schema, and what's required on `sector`. However, that does not require a vocabulary as it defaults to DAC. Do we want to require a vocabulary for tag?

**Comment by robredpath** [comment]
@rory09 - @Bjwebb 's comment above is relevant to your interests in Rome, I think. It'd be useful for us to be able to get this closed off sooner rather than later.

**Comment by rory09** [comment]
> @Bjwebb> 
> * Due to some oddness of namespaces, we can't have an xsd:any for elements, as we would for the standard proper. Is this okay? (I doubt anyone will run into this).
> * I've based the schema, and what's required on sector. However, that does not require a vocabulary as it defaults to DAC. Do we want to require a vocabulary for tag?

First point: I don't think I've ever seen xsd:any used, and given that this is a temporary patch before v2.03 is relesed, I don't see it as a big problem

Second point: I don't think we do want to require a vocabulary, as one of the use cases for the tag element is actually free text tagging. When we're doing additional checks / rulesets for OpenAg data, we could alert the publisher to the fact that free-text tags are not that and they should use a vocabulary, but I don't think we want to require it.

**Comment by Bjwebb** [comment]
Validation of openag:tag is now deployed to http://iati.cove.opendataservices.coop/
