### ISSUE TITLE
Feature Request: CoVE instances - supply sample file?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#84]
For 360 and OCDS it would be useful to include a sample data file for people to "click thru"...

**Comment by Bjwebb** [comment]
Yes. Might also be useful to link to a larger set of data.

For OCDS we have sample-data - https://github.com/open-contracting/sample-data

For 360Giving we have http://data.threesixtygiving.org/ , but not sure what the best specific sample file is. @stevieflow Do you have any thoughts?

**Comment by caprenter** [comment]
We do have sample data used in our tests:
https://github.com/OpenDataServices/cove/tree/master/cove/fixtures

**Comment by Bjwebb** [comment]
I think the considerations here might be a bit different than our unit tests. eg. It might be better to have a link to data that's kept up to date, and has more than two records.

I'm also not sure what the considerations are about pointing to a particular publishers data in the user interface.

**Comment by Bjwebb** [comment]
I suggest that for OCDS we link to http://standard.open-contracting.org/validator/?source_url=https://raw.githubusercontent.com/open-contracting/sample-data/master/fictional-example/ocds-213czf-000-00001-02-tender.json for now (although I suspect we can improve on this).

For 360 I don't think we have appropriate issue yet, so I've opened a separate issue for that https://github.com/ThreeSixtyGiving/standard/issues/119

**Comment by Bjwebb** [comment]
Pull request for the OCDS link https://github.com/OpenDataServices/cove/pull/271

**Comment by robredpath** [comment]
@ekoner is working on some 360 sample data in https://github.com/ThreeSixtyGiving/standard/issues/119, so once that's ready we can add a link to the 360 validator

**Comment by stevieflow** [comment]
I added some sample 360 files I used on a recent demo: https://github.com/ThreeSixtyGiving/standard/issues/119#issuecomment-265805900

**Comment by Bjwebb** [comment]
@stevieflow Is that sample data suitable for linking to from 360 Cove? Should it be hosted somewhere more authoritative than attached to a GitHub issue?

**Comment by stevieflow** [comment]
@Bjwebb yes please - I just added it to the ticket for reference.  Agree it should be somewhere more authoritative

**Comment by caprenter** [comment]
Candidate for #531

**Comment by Bjwebb** [comment]
@caprenter BTW OCDS has a "try loading some sample data." link now, the remaining task on this issue is for 360Giving.

**Comment by Bjwebb** [comment]
Sample data is now hosted in a 360Giving repo, so we can link to that https://github.com/threesixtygiving/sample-data

**Comment by stevieflow** [comment]
Flagging that we should move to use the 360 sample data in https://github.com/OpenDataServices/cove/issues/84#issuecomment-288158912

**Comment by Bjwebb** [comment]
Sample data link on the dev site now http://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io/

**Comment by robredpath** [comment]
@KDuerden can you review ^^ and see what you think! New features are sample data and you can see the new More Info in action

**Comment by stevieflow** [comment]
My only observation is that the link works and gives me results, but I cant actually / easily "see" the data it is testing.  Is it possible to give a link to the data, alongside the test results?

**Comment by edugomez** [comment]
@stevieflow You can see the data downloading it in the Download section. But I understand it may be a bit hidden.

**Comment by KDuerden** [comment]
Great stuff. 
I would like to update the sample file, so there are a few more examples, and they look a bit more like the average dataset. Bob uploaded a few more samples I created in the repository [.](https://github.com/ThreeSixtyGiving/sample-data/tree/cove-duplicate-id-checks)

_To preview how this tool works, try loading some sample data_ works better at bottom of _How to use the 360Giving Data Quality Tool_, rather than _Formats_

The More Information section functionality is great. I think the styling of the headers/font size needs a bit of tweaking - the size go down a bit for the three questions headers?

**Comment by stevieflow** [comment]
Re: "7 days".  I always understood it should be written "seven days"?

**Comment by edugomez** [comment]
> Re:  "7 days". I always understood it should be written "seven days"?

Will change

> the size go down a bit for the three questions headers?

I think you are right, they are too big.

**Comment by edugomez** [comment]
@KDuerden for this:

> I would like to update the sample file, so there are a few more examples, and they look a bit more like the average dataset

What would you like to see?:

1 - A different example referenced by the existing example data link (and if so, which want?)
2 - Some more additional links with sample data to tests
3 - A link to all the sample files in GitHub

**Comment by KDuerden** [comment]
Option 1. I'm happy to update the current correct sample file so it can continue to point there.

**Comment by edugomez** [comment]
@KDuerden Thanks, that sounds good and means I don't need to do anything else to it.  I've done the other small changes suggested, will push them shortly.

**Comment by KDuerden** [comment]
@edugomez I've updated the sample file, see attached. Can you add to repository so it gets picked up in the live deployment?
[ExampleTrust-grants-fixed.xlsx](https://github.com/OpenDataServices/cove/files/1642712/ExampleTrust-grants-fixed.xlsx)

**Comment by edugomez** [comment]
@KDuerden Yes, I will submit a pull request with the new file.

**Comment by edugomez** [comment]
@KDuerden The xlsx file has been updated in the ThreeSixtyGiving repo https://github.com/ThreeSixtyGiving/sample-data/blob/master/ExampleTrust-grants-fixed.xlsx. 

You can check the sample data load here http://master.cove-360-dev.default.threesixtygiving.uk0.bigv.io/
