### ISSUE TITLE
OCDS: Make the headlines box red when validation fails

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#845]
Suggestion from @ColinMaudry

Because the OCDS theme is green users might think that their file has validated when it hasn't. Applying the same red style used for the 'Validation errors' section of the results page to the 'Headlines' box would make it clearer that validation has failed.

![image](https://user-images.githubusercontent.com/19265814/30695508-b1397c4c-9ed8-11e7-930a-4e3a54e0d406.png)

**Comment by ColinMaudry** [comment]
Hi,

I suggest the following result:

![screenshot from 2017-09-21 17-21-29](https://user-images.githubusercontent.com/3747136/30697860-5b251fbe-9ef1-11e7-851b-79e6644e2d4b.png)

I added a 3px red border and a red background on the first `.panel-heading` and  `panel-primary`.

**Comment by jpmckinney** [comment]
This could be a candidate for the Apr-May 2019 sprint.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make the headlines box red when validation fails](https://trello.com/c/9lWhYItc/34-make-the-headlines-box-red-when-validation-fails)

**Comment by rhiaro** [comment]
From colours already in the theme, any preference for light red or dark red?

![lightred](https://user-images.githubusercontent.com/466229/71724753-84dcbf00-2e42-11ea-88cc-2d3050a1ffcf.png)

or

![darkred](https://user-images.githubusercontent.com/466229/71724754-84dcbf00-2e42-11ea-99c5-a9c487afc95d.png)

**Comment by ColinMaudry** [comment]
Dark, since it also has light text and consequently matches the green.

**Comment by ColinMaudry** [comment]
Actually, I would also update the color of the heading for "Structural Errors - Format" and use dark red too.

**Comment by robredpath** [comment]
+1 to the darker colour, in both cases if possible.

**Comment by Bjwebb** [comment]
![Screenshot from 2020-06-03 14-49-48](https://user-images.githubusercontent.com/634/83644744-82c18c80-a5a9-11ea-9527-28a91f04374a.png)

I've made these changes on the cove-845-red-box branch ([PR](https://github.com/open-contracting/cove-ocds/pull/40)). There's a dev deploy at http://cove.dev1.cove.opencontracting.uk0.bigv.io/review/. @ColinMaudry @duncandewhurst Could you check this looks like what you'd expect?

Note that:
* The top box is red for structural checks failing (JSON schema + closed codelists) and broken extensions, but is green if there are just conversion warnings. This corresponds to when crosses appear in the box currently.
* All instances of the light red colour have been replaced with the darker red. This includes some boxes within the panels. (e.g. inside the Schema box in the above screenshot).

**Comment by ColinMaudry** [comment]
Looks good! http://cove.dev1.cove.opencontracting.uk0.bigv.io/review/data/1065e7f0-667a-4ef4-a7a8-6615e253e424

**Comment by duncandewhurst** [comment]
Looks good to me to!

**Comment by Bjwebb** [comment]
This was deployed.

**Comment by ColinMaudry** [comment]
https://media.giphy.com/media/MGYY2FIs8VrfW/giphy.gif
