### ISSUE TITLE
OCDS: Fix mismatching greens

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#846]
I just noticed there are three different greens used for the boxes on the validator results page.

I think they should all be the same as the green used for the headlines box.

![image](https://user-images.githubusercontent.com/19265814/30695778-afc4ee4a-9ed9-11e7-8b15-f26b3c0098f1.png)

**Comment by andylolz** [comment]
So:
 * Headlines, Documents and Key Field Information all use `panel-primary`
 * Schema uses `panel-warning`
 * Convert uses `panel-success`

IATI and 360 use `panel-default` everywhere, which I suppose is preferable (for default stuff, that isn’t an error or a warning).
