### ISSUE TITLE
activity-status causing an issue in IATI?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#848]
Attached is some sample data.  I've copied the headers from other projects, that work

For some reason (I cant fathom) ``activity-status`` causes a validation issue here

> 'activity-status': This element is not expected. Expected is one of ( description, participating-org.

I just cant see why.  Another set of eyes would be appreciated -- > @Bjwebb @edugomez @rory09 

http://iati.cove.opendataservices.coop/data/dab22d07-e02f-4392-bdcd-736c5105f86a

[CoVE-IATI-example.xlsx](https://github.com/OpenDataServices/cove/files/1332940/CoVE-IATI-example.xlsx)

**Comment by edugomez** [comment]
@stevieflow the error says that it is expecting:

1- description (schema:  minOccurs="1" maxOccurs="unbounded"), i.e. it is expecting another description element (as there's already one)
OR 
2 - participating-org (schema: minOccurs="1" maxOccurs="unbounded"), i.e. the next mandatory element after description

So basically you are missing participating-org before activity status.

**Comment by stevieflow** [comment]
Do'h!  Thanks @edugomez - Ill try that.  Wood for trees

Will close if successful

**Comment by stevieflow** [comment]
SUCCESS!

http://iati.cove.opendataservices.coop/data/f259350a-210e-4ebd-b689-fbadff1d1eb9

[CoVE-IATI-example.xlsx](https://github.com/OpenDataServices/cove/files/1333296/CoVE-IATI-example.xlsx)

Thanks @edugomez

**Comment by edugomez** [comment]
@stevieflow :+1:
