### ISSUE TITLE
Add ability to comment out columns and tabs in workbook

### ISSUE THREAD

**Issue by rory09** [OpenDataServices/cove#857]
There are two bits of functionality which I think would be really useful for IATI CoVE:

1. commenting out a column
2. commenting out a sheet

My hope is that both could be done by including a specific character at the start of the column/sheet name. 

My initial impulse is to go for '#' but I'm aware that this might conflict with HXL, and my second would be a dollar sign or something similar, but it's very plausible that people would want to name columns or sheets as, say '$ expenditure', so this might be confusing. 

Given this, possibly '^'?

**Comment by Bjwebb** [comment]
Implementing this for xlsx (using #, enabled by a hashcomments command) was done as this flatten-tool issue: https://github.com/OpenDataServices/flatten-tool/issues/174. We may also want to do it for CSV.

Work so far is deployed  to http://iati.cove.opendataservices.coop/ 

For an example of how to use the feature, see https://github.com/OpenDataServices/flatten-tool/blob/master/flattentool/tests/fixtures/xlsx/commands_hashcomments.xlsx

**Comment by robredpath** [comment]
We think this is done. It requires testing, and documenting.

**Comment by robredpath** [comment]
We talked a bit about where to document this. We're going to do a Google Doc for now, shared with the people who we know use CoVE for IATI, and then look at where a good home for it is. We have a Sphinx site that contains CoVE docs that may be The Place for it.

**Comment by kindly** [comment]
@robredpath Just decided to go for putting it in the Cove docs as I wanted to write them in something that sphinx can read (as they will end up there at some point hopefully).

Added docs on metatab and other flattentool commands too, to give this some context in the docs.
