### ISSUE TITLE
OCDS: Estimate time needed to implement recommendations from validator research report

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#860]
In the [Thursday helpdesk call](https://docs.google.com/document/d/1ilExOtuyMb09kEyeuTeXzNeU0oHT6XYUw1bk69Q1iB0/edit#bookmark=id.e5f8btugt84b), we reviewed the [OCDS validator research report](https://docs.google.com/document/d/1M2Y-aK3-RzbzziXEOEInYDaCjWqV-Ak7mZEOm9Ut34E/edit), and made an initial prioritization of the report's recommendations. However, to properly prioritize these, we should have at least a rough estimate of the time investment for each. 

I'd also note that some (not all) issues reported against `standard` and tagged as [Focus - Validation](https://github.com/open-contracting/standard/labels/Focus%20-%20Validation) are relevant to CoVE.

**Comment by jpmckinney** [comment]
Please add OCDS tag.

**Comment by robredpath** [comment]
I think this is done, isn't it @jpmckinney ?
