### ISSUE TITLE
recipient-country|recipient-region percentage sum check missing

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#871]
https://github.com/IATI/IATI-Rulesets/blob/version-2.02/rulesets/standard.json#L23-L28

**Comment by Bjwebb** [comment]
This check is also missing from @andylolz's code https://github.com/pwyf/data-quality-tester/tree/develop/test_definitions/iati_standard_ruleset

It's not listed on the iatistandard website http://iatistandard.org/202/rulesets/standard-ruleset/#non-machine-readable-rules (I've reported an issue at https://github.com/IATI/IATI-Rulesets/issues/46)

Also, the check as implemented in the IATI-Rulesets repo is inconsistent with what happens in the example XML (http://iatistandard.org/202/activity-standard/example-xml/) - the check is about the sum of all recipient-country and recipient-region, whereas the example XML treats different vocabularies differently.

**Comment by andylolz** [comment]
> This check is also missing from @andylolz's code https://github.com/pwyf/data-quality-tester/tree/develop/test_definitions/iati_standard_ruleset

It’s true – looks like I missed these ones.

tbh I’m happy to remove these tests completely, given [you have your own copy](https://github.com/OpenDataServices/cove/tree/master/cove_iati/rulesets/iati_standard_v2_ruleset)… They were only ever in the repo for demonstration purposes.

**Comment by Bjwebb** [comment]
@andylolz Yes, you can remove those tests if you want. A link over to this repo might also be useful for people.

**Comment by andylolz** [comment]
> A link over to this repo might also be useful for people.

I didn’t do this, because it wouldn’t be useful for anyone. These tests were in my code for demonstration purposes only. Pretty sure no-one relied on them, except maybe you guys.
