### ISSUE TITLE
Issue with CDMX bulk download validation

### ISSUE THREAD

**Issue by juanpane** [OpenDataServices/cove#883]
Hi there:
When trying to validate the bulk download data from CDMX for OCDS available here:
http://contratosabiertos.cdmx.gob.mx/api/contratos/array

selecting the URL option for the OCDS validator here: http://standard.open-contracting.org/validator/ 

The validator shows different errors, either saying that the data is not a valid json, or a page error saying that the data is too big

**Comment by edugomez** [comment]
> either saying that the data is not a valid json

![cove_error](https://user-images.githubusercontent.com/5618508/32321060-cb99c650-bfb7-11e7-94c6-84c20e6e49a5.png)

It is an encoding error. As documented here http://standard.open-contracting.org/latest/en/implementation/serialization/#json, JSON data must be utf-8 encoded. Also, the file is not a release package or a record package, so Cove won't accept it anyway.

>  or a page error saying that the data is too big

I haven't been able to reproduce this. When linking files from an URL, Cove can't guarantee the response from the third party server, the consistency of the networks, timing out of the request/response, etc...
