### ISSUE TITLE
The OCDS Validator needs to make it clear what validation is and isn't

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#884]
During the OS4D workshops we've been talking about how people sometimes misunderstand what validation is and isn't. We should add something to the UI for the OCDS validator that makes it clear that validation is about structure, but that doesn't mean your data is any good!

**Comment by jpmckinney** [comment]
I think the rename to "Data Review Tool" and other changes have satisfied this issue sufficiently?

**Comment by robredpath** [comment]
Yes, and the work to make the validation errors better-presented will help further.
