### ISSUE TITLE
Encoding error doesn't tell you what to do 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#887]
In https://github.com/OpenDataServices/cove/issues/883#issuecomment-341382595, the error in the screenshot is an encoding error, but you can only work it out from an educated guess that it might be encoding related. 

We should catch this error and make it friendlier.

**Comment by odscjames** [comment]
If you want to test this, download https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt and rename it to JSON and CoVE will say: 

     Error message: 'utf-8' codec can't decode byte 0xf8 in position 4461: invalid start byte

**Comment by odscjames** [comment]
There is now a pull request against Flattentool to raise a special exception. When that's in and merged, we can look at catching it here and showing a custom message.

**Comment by odscjames** [comment]
Ugh, I got this wrong. The JSON is converted in several places, and somehow I picked up on the wrong one earlier.

To do this issue, we only need to make changes in CoVE. For the OCDS Standard only, see: https://github.com/OpenDataServices/cove/compare/887-encoding-error 

So we just need to discuss; what should the copy message be? I just put 

> We think you tried to upload a JSON file, but it is not well formed JSON. It should be in UTF-8 encoding.

What do others think?

ps. We have commit https://github.com/OpenDataServices/flatten-tool/commit/9406b25d99e12a901f5a00e73bbb5d4fe64e6343 in flatten-tool that strictly speaking isn't needed; but given how backwards compatible it is and that I think having explicit errors is generally sensible, I'm happy to leave it. And if CoVE ever changes how it loads the JSON we might need it to accomplish this.

**Comment by jpmckinney** [comment]
Add "bug" tag? Related to #535.

**Comment by robredpath** [comment]
@jpmckinney I think this is a "not clearly a bug" - as it does work correctly, just not particularly helpfully. 

I would propose the text of:
> The file that you uploaded doesn't appear to be valid JSON. OCDS JSON follows the I-JSON format, which requires UTF-8 encoding. Ensure that your file uses UTF-8 encoding, then try uploading again. 

It would be good if we could provide some appropriate link, but that's probably the next step. Just communicating the error well would be a good start. Either my text or @odscjames gives people plenty to Google!

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make encoding errors actually tell you what to do](https://trello.com/c/NmSoxpcI/26-make-encoding-errors-actually-tell-you-what-to-do)

**Comment by Bjwebb** [comment]
I made a start on this as part of scoping this issue: https://github.com/OpenDataServices/cove/pull/1240

![Screenshot from 2019-10-31 13-16-12](https://user-images.githubusercontent.com/634/67949960-a6ba8b00-fbe0-11e9-8eb0-1815cbb30aa0.png)

I used @robredpath's wording, but with "well formed" instead of "valid".

Remaining tasks:
- [ ] Finalise wording
- [ ] Add tests
- [ ] Extend to OC4IDS?
- [ ] Extend to 360Giving?

**Comment by robredpath** [comment]
@jpmckinney are you happy with this copy ^^ ?

**Comment by jpmckinney** [comment]
Copy looks good, thanks!
