### ISSUE TITLE
explore_record: Reporting unique OCIDs of large files

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#896]
e.g. http://standard.open-contracting.org/validator/data/efa21228-0d98-4080-8c4f-ab63db58e1f6

"Unique OCIDs" and "Records Table:" are very long. We should collapse them and have a "See all" link or similar to display the rest.

**Comment by jpmckinney** [comment]
Since this content can be MBs of HTML, it might even be best to only deliver the HTML once the user clicks "see all" (in above proposal).

**Comment by jpmckinney** [comment]
See CRM issue 5858, where the very large table causes the user's browser to crash/freeze.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quick fixes for large files](https://trello.com/c/pZJldiNG/70-quick-fixes-for-large-files)

**Comment by Bjwebb** [comment]
I've done some work on the releases table in https://github.com/open-contracting/cove-ocds/pull/35, but that doesn't include the "Records Table".

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Truncate rows in Records table as well as Releases](https://trello.com/c/6QmZNE0w/78-limit-number-of-rows-in-records-table-as-well-as-releases)

**Comment by Bjwebb** [comment]
Changes to the "Records Table" in https://github.com/open-contracting/cove-ocds/pull/43 are now deployed to https://standard.open-contracting.org/review/

**Comment by jpmckinney** [comment]
From CRM-5858, the data URL (releases) is https://www.data.gouv.fr/fr/datasets/r/68bd2001-3420-4d94-bc49-c90878df322c Submitting that URL now generates a  HTML file. It takes mins to generate, but that's a separate issue.

For this issue, the records template still prints all `records_aggregates.unique_ocids`, so renaming the issue to address that last part.

**Comment by jpmckinney** [comment]
Moved
