### ISSUE TITLE
Accept large files

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#897]
I got an internal server error on a 629MB file. The reference is 5aef437312394ec0af095b031a11ae1d

291MB is too big: d8321da5d0274233aabe627a22f9b439

104MB is too big: f6d658d7276c4bc4b7a6b96b908a9ea5

47MB didn't present the same Internal Server Error page, but it displays "Sorry, something went wrong": http://standard.open-contracting.org/validator/data/90c3465d-9001-41ea-89a2-7ed90cbd1af2

21MB is too big: a23feafb7e9b4c1da620d7a5550412f5

15MB was fine! http://standard.open-contracting.org/validator/data/6be0886e-b38a-4d37-9c05-ba2ee4dd38b4

**Comment by Bjwebb** [comment]
We have per process memory limits, to avoid one process trashing the server. I think these might still be set too low - I'll take a look, thanks for the examples.

**Comment by Bjwebb** [comment]
We've updated the memory limits (https://github.com/OpenDataServices/opendataservices-deploy/pull/46), and those files should work now. However the 629MB one takes almost 15 mins, which may also be a problem.
