### ISSUE TITLE
KFI for data that uses Parties

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#900]
Back in June, when we were looking at tooling prep for 1.1, we identified that KFI might not be correct if the data used Parties. 

I can't see that we ever resolved that question, so we should investigate.

**Comment by jpmckinney** [comment]
What is KFI?

**Comment by robredpath** [comment]
Sorry, KFI is Key Field Information - the box with the summary data on the submitted data.

**Comment by jpmckinney** [comment]
I believe this is closed. Example: http://standard.open-contracting.org/review/?source_url=https://raw.githubusercontent.com/open-contracting/sample-data/master/fictional-example/1.1/ocds-213czf-000-00001-02-tender.json
