### ISSUE TITLE
MS Office based error?

### ISSUE THREAD

**Issue by rory09** [OpenDataServices/cove#906]
I have a mysterious error. A client has sent me an xlsx file for conversion that gives the following error: http://iati.cove.opendataservices.coop/data/aad097ad-518d-4b15-88a7-c6dbe15e8961

Here's the same file uploaded *after having been opened and saved in LibreOffice*: http://iati.cove.opendataservices.coop/data/7bda0ed5-44bd-437e-bf3a-46d85a8f45c6

The error message in CoVE reads: 
![image](https://user-images.githubusercontent.com/7805169/33440150-23105576-d5e7-11e7-9950-adad1eecc229.png)

Any thoughts?

**Comment by edugomez** [comment]
Do you have the original file _before_ the LibreOffice conversion?

**Comment by Bjwebb** [comment]
Here's the error on sentry: https://sentry.io/open-data-services/cove-dev/issues/406192967/

This is an error from in the middle of the library we use, `openpyxl`

Our copy of `openpyxl` is out of date, so it could be worth trying to open this with the latest version. You'll need to do this outside of our current code though, as it relies on internal details of the old version.

**Comment by rory09** [comment]
Thanks for the update. Should I take it from this that we're not planning to upgrade the version of openpyxl we're using in our main code? I don't really mind this error as I work on Ubuntu / Gdrive the whole time; it's mainly our clients who will be on MS Office...

I don't have an account on sentry, but it sounds useful - I'm not sure if we have an admin account which could invite me or there's some other way of signing up, but I can't see an obvious way of me getting things started from my end.

**Comment by Bjwebb** [comment]
No, we can upgrade openpyxl for the main code, it will just require a bit of work - that I'd rather avoid if we know that the new version doesn't actually fix the problem for us.

I've invited you to Sentry.

**Comment by kindly** [comment]
This issue is due to openpyxl support of Comments.  I think if there are any comments (or maybe comments of a certain type) in the file it will fall over.

We could advise, for now, that there should be no comments in the file.

The latest version openpyxl will fix this issue (although it will cause a few others) and I managed to get the file converted/loaded by hacking a copy of flattentool to use it. However, doing this properly and testing it will take a while (especially as they have changed their internal api quite a bit).

**Comment by Bjwebb** [comment]
I've seen this issue reported from 360 CoVE also: https://sentry.io/open-data-services/cove/issues/392837329/

**Comment by Bjwebb** [comment]
This should be fixed by https://github.com/OpenDataServices/cove/issues/954
