### ISSUE TITLE
Load CoVE as a library

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#908]
Follow-up to #207, I'd like to be able to use CoVE as a library. The reason is that for bulk validation of large datasets, I don't want to download all packages and then run each one through the command-line tool. (I suppose I could write a shell script that downloads one package at a time (maintaining state), and runs the command-line tool, but there is also a lot of overhead to setting up Django each time, and I want this process to be fast.)

Right now, it seems I need to put my script in the same working directory as CoVE in order to run, e.g.:

```
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "cove_ocds.settings")

from cove_ocds.lib.api import APIException, ocds_json_output
```

**Comment by jpmckinney** [comment]
Do we just need to add `cove_ocds` to the `packages` list in `setup.py`?

**Comment by robredpath** [comment]
Just talked to @edugomez - he'll comment here with some more info on how to do this in a Django-ey way in a way that might save some clock cycles as well.

**Comment by kindly** [comment]
@jpmckinney yes we should add cove_ocds, cove_iati and cove_360 to the packages list in setup.py and that should mean you can import cove_ocds from anywhere.

**Comment by edugomez** [comment]
@jpmckinney Just in case, I'm not sure if you know about Django's  [call_command](https://docs.djangoproject.com/en/1.11/ref/django-admin/#django.core.management.call_command). 

I _think_ you can even do something like:
```
from multiprocessing import Process
c = Process(target=call_command, args = (...))
c.start()
```
But I've never tried doing that before, so I'm not sure if that works well.

**Comment by jpmckinney** [comment]
@edugomez I'd rather be able to call `ocds_json_output` directly.

**Comment by jpmckinney** [comment]
Do recent changes fix / invalidate this issue? e.g. https://github.com/open-contracting/lib-cove-ocds

**Comment by robredpath** [comment]
@jpmckinney There's still work we'd like to do, but the core is done and any new issues can go against the relevant repos. Closing.
