### ISSUE TITLE
Add mercurial to the requirements for IATI localhost

### ISSUE THREAD

**Issue by rory09** [OpenDataServices/cove#915]
I've just been following the instructions to install IATI CoVE to run on localhost so that I can use the CLI, and I've hit an issue with a dependency on @Bjwebb's bitbucket account:

```
Collecting defusedxml==0.5.0 (from -r requirements_iati.txt (line 4))
  Downloading defusedxml-0.5.0-py2.py3-none-any.whl
Obtaining defusedexpat from hg+https://bitbucket.org/bjwebb/defusedexpat@11b0ba9f42a547607134f7b36a241382659aff24#egg=defusedexpat (from -r requirements_iati.txt (line 5))
  Cloning hg https://bitbucket.org/bjwebb/defusedexpat (to revision 11b0ba9f42a547607134f7b36a241382659aff24) to ./.ve/src/defusedexpat
  Error [Errno 2] No such file or directory: 'hg' while executing command hg clone --noupdate -q https://bitbucket.org/bjwebb/defusedexpat /home/rory/Code/cove/.ve/src/defusedexpat
Cannot find command 'hg'
```

I fixed this by installing mercurial. I'd recommend adding it to the installation guide assuming I didn't just miss something?

**Comment by Bjwebb** [comment]
You're quite right, it's just missing from the installation guide. Here's a PR to fix that - https://github.com/OpenDataServices/cove/pull/923

**Comment by andylolz** [comment]
Hmmmmm are you aware of this? https://github.com/tiran/defusedexpat/commit/f16cbaeee2595c0f30eeee1292b97f1557ddb43f

**Comment by Bjwebb** [comment]
We're using Python 3.5, so it's not a simple matter of just switching to that repo.  I will take a look at whether we can build on top of the github repo though.

**Comment by andylolz** [comment]
> We're using Python 3.5, so it's not a simple matter of just switching to that repo

Apologies! I looked at your bitbucket pull request (about python3.4) rather than your latest bitbucket commit. My mistake!

That said, the latest commit looks pretty trivial. So while it’s not a simple matter of just switching to that repo… I wonder if it is a marginally-less-simple-but-still-pretty-simple matter of switching to a github fork with one extra commit?

**Comment by Bjwebb** [comment]
@andylolz Thanks for the suggestion, we're building on top of the GitHub repo now.
