### ISSUE TITLE
Bad extension difficult to debug

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#928]
Normally my debugging process for CoVE goes like this:
* Error is reported to Sentry
* Sentry has a link to the data URL that causes the problem
* I click through to the data URL to reproduce the problem, and can use the data ID to download the problematic data from the server

This works because CoVE always makes it's own copy of a data file, so even if the publisher fixes it, I can still reproduce the original error.

However, I think we don't make a copy of extensions (in the `extensions` field). This means someone can hit an error, but I'm not able to reproduce it - because they've changed the extension in the meantime.

Here's a specific example for those with access to Sentry:
https://sentry.io/open-data-services/cove/issues/419009256/
(note that I'm also following up that specific issue in https://github.com/OpenDataServices/cove/issues/929)

**Comment by jpmckinney** [comment]
✅ From OCP's perspective, this issue can be closed / 'OCDS' tag can be removed.

If a user causes an error to occur, and then changes their extension such that the error no longer occurs, I think that's fine. If they don't (and we're then able to identify the issue with the extension that causes the error), then we can of course pursue a fix.
