### ISSUE TITLE
Data table adds a .0 to a number?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#93]
http://cove.opendataservices.coop/360/data/d82d9e56-0e36-4de0-8c5b-c1d3e63633f1

Data: https://gist.github.com/stevieflow/bbb25e5368eb34f8d6f1

In the data table, Im unsure where the addition of the .0 to the value comes from.  Is this in the CSV, or added by CoVE?

**Comment by Bjwebb** [comment]
This seems to be due to the behaviour of flattentool, so I'm moving this issue there https://github.com/OpenDataServices/flatten-tool/issues/72
