### ISSUE TITLE
360: Date modified not parsed?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#94]
http://cove.opendataservices.coop/360/data/d82d9e56-0e36-4de0-8c5b-c1d3e63633f1

Data: https://gist.github.com/stevieflow/bbb25e5368eb34f8d6f1

The source CSV does have a dateTime value, but this is not displayed in the table

**Comment by Bjwebb** [comment]
"Last Modified" is not being converted properly because flattentool is case sensitive - http://cove.opendataservices.coop/media/d82d9e56-0e36-4de0-8c5b-c1d3e63633f1//unflattened.json

**Comment by Bjwebb** [comment]
I suspect the solution to this is to either 1) be case insensitive when we're using titles, or 2) warn users when they have the case wrong (or possibly both!).

**Comment by timgdavies** [comment]
Both sounds like a good idea to me (with perhaps a strict option in the tool to only warn).

That way we build tools which are tolerant, but which also educate: particularly if we make error messages pedagogic.

**Comment by stevieflow** [comment]
Ah OK - I had posted this here: https://github.com/ThreeSixtyGiving/standard/issues/63

Is it worth considering this - in terms of consistency of the standard / field names - first of all?

**Comment by Bjwebb** [comment]
If we do have case insensitivity, it should include sheet names (including "grants" or "Grants"), see - https://github.com/ThreeSixtyGiving/standard/issues/64

**Comment by stevieflow** [comment]
+1 for Date Modified rather than Date modified

**Comment by stevieflow** [comment]
I've been looking at this again today

Sample data: https://gist.github.com/stevieflow/bbb25e5368eb34f8d6f1#file-test2-csv

As far as I can see, this data has "Date modified" as the column header, and a dateTime value.

But, this is not output in CoVE results: http://cove.opendataservices.coop/360/data/bbf65e34-719c-444b-8c19-ef2302fc0b36

**Comment by caprenter** [comment]
On investigation, the generated JSON does have a 'Date modified' field, but the template is looking for 'dateModified' (see: https://github.com/OpenDataServices/cove/blob/master/cove/templates/explore.html#L203 )

I'm unclear as what is expected here, but could be a quick fix.

**Comment by stevieflow** [comment]
If it helps ; my user expectation is that a correctly labelled ("Date modified") and populated ("2015-09-10T00:00:00Z") value is not presented to me in the results table, when I use 360 CoVE.

(it may be worth checking I have these two items as correct/valid)

**Comment by Bjwebb** [comment]
Cove uses the titles from the 360 schema. "Date modified" is not the title in the schema, rather it is "Last modified" - https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L69

**Comment by stevieflow** [comment]
Ah ha.  This could all have been one big misunderstanding.... (by me)

**Comment by caprenter** [comment]
The documentation is here:
http://www.threesixtygiving.org/standard/reference/#toc-spreadsheet-format

Is the documentation as we want it to be?

**Comment by stevieflow** [comment]
I can pinpoint https://github.com/OpenDataServices/cove/issues/94#issuecomment-141112559 as the time I diverted this thread onto the wrong path!

OK - can now confirm that "Last modified" works fine.  Whether that should be "Last Modified" is discussed in https://github.com/ThreeSixtyGiving/standard/issues/64

**Comment by stevieflow** [comment]
Documentation is all fine btw @caprenter

**Comment by Bjwebb** [comment]
@stevieflow There should probably also be an issue for the capitalisation against Cove, particularly since this issue is linked from that standard issue in that capacity! To avoid confusion I've opened a new one: https://github.com/OpenDataServices/cove/issues/148

**Comment by Bjwebb** [comment]
We still need an issue for case insensitivity in Cove, so I've created this: https://github.com/OpenDataServices/cove/issues/148
