### ISSUE TITLE
Empty heading row causes unhelpful conversion error

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#943]
![image](https://user-images.githubusercontent.com/634/34725921-5d34aca2-f54a-11e7-977a-398b721c4e30.png)

https://sentry.io/open-data-services/cove/issues/428429549/

```
IndexError: list index out of range
(1 additional frame(s) were not displayed)
...
  File "cove/lib/exceptions.py", line 53, in wrapper
    return func(request, *args, **kwargs)
  File "cove/lib/converters.py", line 92, in convert_spreadsheet
    **flattentool_options

list index out of range
```

Example file: https://gist.githubusercontent.com/Bjwebb/c6d05b9b76fcec35acdce4aeef85e435/raw/dd3b822e05bdf33bd69d935963c0c19e4a633ef4/empty_header.csv

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Empty heading row causes unhelpful conversion error](https://trello.com/c/yFFcBF81/29-empty-heading-row-causes-unhelpful-conversion-error)

**Comment by michaelwood** [comment]
Can't seem to recreate this issue. I tried with supplied example and also created a version of the 360 standard template xlsx and deleted some of the headings.

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["list index out of range" error](https://trello.com/c/6O8kenJg/46-list-index-out-of-range-error)

**Comment by robredpath** [comment]
Yeah, I've tried a few combinations and I can't recreate this either. 

@KDuerden could you let us know next time you come across this and send us the file (privately, if necessary)?

**Comment by robredpath** [comment]
Closing - re-open (or let us know via plan.io) if this happens again.
