### ISSUE TITLE
Add validator warning for missing 'id' values in objects in arrays. 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#947]
See https://github.com/open-contracting/standard/issues/650

**Comment by robredpath** [comment]
We'll try to group this with the deprecated fields, as they feel like the same kind of thing.

**Comment by robredpath** [comment]
This is a computationally quite expensive task, so is likely to result in a performance hit. We'll try to quantify it during development.

**Comment by rory09** [comment]
I've had some conversation with @edugomez about this, and I see two issues arising. One is to do with the presentation this:

## UX

Currently there are boxes for schema validations, additional fields, schema extensions, and possibly others, but it doesn’t seem that there’s a place for a hint such as this. The first question is where to put this kind of soft/speculative validation. My initial thoughts was to include a 'Hints' box to house this and any similar non-functional validation. A very rough version would look something like this: 

![image](https://user-images.githubusercontent.com/7805169/35519485-4a332260-050c-11e8-963f-3df778b97d66.png)

That said, Rob mentions above:

@robredpath 
> We'll try to group this with the deprecated fields, as they feel like the same kind of thing.

If this is the case I think we should consider at least changing the framing of this box to be more abstract, such as 'Hints' with sub-groupings around deprecation and possible future requirements. 

I think this warrants its own issue, as it's important but has no bearing on the technical task which I'll focus on below.

## Technical Approach

Overall, and without a deeper understanding of CoVE, I would opt for option 2 below, but this will require consideration and buy-in from the development team, given I'm new to this codebase.

### Option 1

Add a step in CoVE’s parse which inspects all organisation arrays and checks for the existence of an id, stores the results in memory and then displays any violations of the version 2.x requirement in the hint box above (or however).
### Option 2

**Comment by rory09** [comment]
I've had some conversation with @edugomez about this, and I see two issues arising. One is to do with the presentation, the other with the underlying technical solution.

## UX

Currently there are boxes for schema validations, additional fields, schema extensions, and possibly others (I'm still new to the code), but it doesn’t seem that there’s a place for a hint such as this. The first question is where to put this kind of soft/speculative validation. My initial thoughts was to include a 'Hints' box to house this and any similar non-functional validation. A very rough version would look something like this: 

![image](https://user-images.githubusercontent.com/7805169/35519485-4a332260-050c-11e8-963f-3df778b97d66.png)

That said, Rob mentions above:

> @robredpath: 
> We'll try to group this with the deprecated fields, as they feel like the same kind of thing.

If this is the case I think we should consider at least changing the framing of this box to be more abstract, such as 'Hints' with sub-groupings around deprecation and possible future requirements. 

I think this warrants its own issue, as it's important but has no bearing on the technical task which I'll focus on below.

## Technical Approach

Overall, I would opt for option 2 below, but this will require consideration and buy-in from the development team, given I'm new to this code-base.

### Option 1

Add a step in CoVE’s parse which inspects all organisation arrays and checks for the existence of an id, stores the results in memory and then displays any violations of the version 2.x requirement in the hint box above (or however).

Benefits: 
* quick,
* technically quite simple

Costs: 
* potential for sizeable impact on performance (having to parse and analyse very large files - @edugomez tells me that there's already a procedure doing this in CoVE which we could latch on to, however e.g. deprecated paths)
* could create technical debt by over-fitting this approach to the problem at hand (i.e. adapting to a similar problem could be time consuming) 

### Option 2

Create an set of schema requirements which are classed as hints or ‘future validation’ which could be [put into a patch](https://open-contracting.github.io/extension_creator/) such as this (demonstrating the addition of an id requirement in the organization element):

```json
{
  "definitions": {
    "Organization": {
      "required": [
        "id"
      ]
    }
  }
}
```

This could then be added to the jsonschema validation which already happens in the OCDS validator.

Benefits: 
* very low computational overhead 
* scalable, 
* modular
* future-proof: can easily handle similar requirements in the future -- solves the overfitting problem mentioned above.

Costs: 
* it’s unclear how hard to would be to distinguish these additional validation messages from the standard schema / extension validation messages (though @eduardo tells me that this might not be so difficult). 
* needs to be aware and store somehow/produce on the fly the patches needed (also highlighted by @eduardo)

Indirect considerations:

Looking around the OCDS Standard repository, it doesn't seem as though there's a dev version of the 2.x schema anywhere. This would mean that we would need to curate a list of backwardly incompatible changes which are *likely* to be included in the next integer upgrade, which could then be included in this category of test. There are a few key decisions required about this:

* Should users be told that these elements are *going* to be in the next version, or *likely* to be in it? My understanding is that until the governance procedure surrounding integer upgrades is complete, we couldn't be sure.
* Would this kind of check be implemented for *all* backwardly incompatible changes? And would our confidence that they will make it through the integer upgrade procedure differ between them all?
* Should we create a staging 'next integer' schema which includes only the backwardly incompatible changes which are in staging which can power this functionality?

Thoughts on all of the above are welcome @robredpath, @timgdavies, @Bjwebb, @kindly

**Comment by timgdavies** [comment]
@rory09 This is a great overview. 

Approach wise - can we consider how this would be done for **any** case of an array of objects, where the objects in the array are missing an `id` property? 

That would help make sure we also warn [in cases of extensions which have incorrectly omitted the `id` requirement](https://github.com/open-contracting/ocds-extensions/issues/53) or in cases where people have undocumented additional fields, but with a structure that would prevent full merging behaviours.

**Comment by edugomez** [comment]
> That would help make sure we also warn in cases of extensions which have incorrectly omitted the id requirement

That sounds more like an issue to be solved in the extensions themselves, e.g. guidance on that and/or providing a script to run against your newly created extension to check for missing ```id```s.

>  In cases where people have undocumented additional fields, but with a structure that would prevent full merging behaviours.

With those cases in mind, probably it does make sense to actually check all array of objects then, which in turns means that option 1 above would be the one to go with.

**Comment by kindly** [comment]
There are some (2 in fact)  lists of Objects that specify they do not require ids as they have a wholeListMerge property in the schema. I am not aware these are planed being removed in 2.0 nor that we plan to stop extensions using this property.

So we need to exclude anything with wholeListMerge from these warnings. 

The logic should be any Array of Objects without wholeListMerge and also do not already have a required id property should show up.

I think option 1 makes most sense as this logic would be easier implemented in a custom parse of the data.

**Comment by edugomez** [comment]
> I think option 1 makes most sense as this logic would be easier implemented in a custom parse of the data
I'll go ahead with this approach if nobody has major objections.

@rory09 should I start this, with us having a chat about the implementation later today (if that is of any help for you to get more familiar with CoVE)?

**Comment by robredpath** [comment]
Thanks, @rory09 @edugomez @kindly  - this is great! 

Re: the framing of the box, I agree that we should make it more generic. I feel like 'Hints' is too soft. Perhaps 'Quality Factors'? And maybe it should be amber?

**Comment by jpmckinney** [comment]
> There are some (2 in fact) lists of Objects that specify they do not require ids as they have a wholeListMerge property in the schema. I am not aware these are planed being removed in 2.0 nor that we plan to stop extensions using this property.

wholeListMerge is used only on `OrganizationReference`, `Organization` (deprecated) and `Item`. Item requires `id`, and `OrganizationReference` did require `id` until we realized that was backwards-incompatible. Where is the specification that they do not require `id`?

> Should users be told that these elements are going to be in the next version, or likely to be in it?

We can make the message less about what will happen in 2.0, and more about the fact that these *should* be provided in 1.x (the only reason they aren't required is due to our adherence to backwards compatibility). So, the framing is more SHOULD versus MUST, than *future* versus *now*. What happens in 2.0 is irrelevant to the fact that the fields should be present now.

**Comment by kindly** [comment]
> Where is the specification that they do not require `id`?

I was talking about ```additionalClassifications``` and ```additionalIdentifiers```.  They have `id` fields but are not required and are not necessarily unique either.  I thought `id` was not required in these cases as you can also specify a `uri` as well.  For these and for extensions that specify wholeListMerge we should not be giving the warning.

**Comment by jpmckinney** [comment]
Ah, I misread the JSON nesting, yes. I added logic to https://github.com/open-contracting/standard-maintenance-scripts/blob/master/tests/test_json.py to warn about all of these.

**Comment by kindly** [comment]
@rory09 @edugomez 

I think a way to approach this is the following.  Recurse over the schema like we do in 

https://github.com/OpenDataServices/cove/blob/master/cove/lib/common.py#L532
or 
https://github.com/OpenDataServices/cove/blob/master/cove/lib/common.py#L391

The aim will be to get out a set of paths (without indexes) where the id value should exist i.e
```
{('releases', 'tender', 'tenderers'), ('another', 'path'), ...}
```
This is the tricky bit. As it should exist only when there is an Array of Objects that do not have an 'id' already required and do not have the wholeListMerge property.  (The tenderers path in the example example is a real case of this.)

Once you have this set then you recurse over the data and check if the path without the index numbers is the same as one of them and for every object in the list check if there is an id value.

So the path when recursing could be
('releases', 0,  'tender', 2,  'tenderers')

So you need to strip the numbers then compare.  If they do match then get the list of objects at that point and yield (or save them to another list) the paths when the 'id' does not exist.  You will need to keep a copy of the path with the index number then append the index in the list where the `id` does not i.e  ('releases', 0,  'tender', 2,  'tenderers', 2)

I do not think that there are any examples of doing this we have done so far.

Sorry this may not be much help as it is actually more tricky then I first thought it would be.

**Comment by jpmckinney** [comment]
For recursing over the schema, have a look at https://github.com/open-contracting/standard-maintenance-scripts/blob/master/tests/test_json.py#L530-L565

**Comment by edugomez** [comment]
@timgdavies I've go the code to retrieve the missing ```id```s, could you please suggest a place in the validator results for those to be displayed (as you did here https://github.com/OpenDataServices/cove/issues/675#issuecomment-363443955)?

**Comment by timgdavies** [comment]
Thanks @edugomez. The below is an interim suggestion - as I need to give more thought to the overall layout of boxes, and what lives where. But this is a **warning** about the **structure** of the data (rather than an error). I've suggested some possible text below. 

| Structure warnings | 
|--------------------------------------------------------------------------------|
| *Fixing the following issues will improve the interoperability of your data.* |
| We found [ n ] objects within arrays in your data without an `id` property. This may affect the creation of OCDS records, and conversion of data into other formats. We recommend that all objecs within an array should have an `id` set. |
| [ + ] View all warnings |

**Comment by edugomez** [comment]
![structure_w1](https://user-images.githubusercontent.com/5618508/35977093-10443a6e-0cda-11e8-98ae-d620310162c1.png)

**Comment by edugomez** [comment]
![structure_w2](https://user-images.githubusercontent.com/5618508/35977260-728e4fd4-0cda-11e8-8def-d9690a85f959.png)

**Comment by robredpath** [comment]
Quick comments from call with @jpmckinney today:
- s/objecs/objects'
- If it's a warning it should be yellow :)

**Comment by edugomez** [comment]
> s/objecs/objects/

What does it mean?

> If it's a warning it should be yellow

I thought about that , but for some reason (?) a ```panel-warning``` CSS class defined in Cove looks like this:

![warning_st](https://user-images.githubusercontent.com/5618508/35980367-73f12dee-0ce2-11e8-8c2f-cc6f93f787f7.png)

So I went for ```panel-danger``` (which I agree is not quite right)

I'm not sure why Cove doesn't just follow Bootstrap on this.

**Comment by robredpath** [comment]
> What does it mean?

Heh, sorry - it's `sed`! Just that there's a typo of 'objecs' that should be 'objects'. 

> I'm not sure why Cove doesn't just follow Bootstrap on this.

Ha, amazing. We should definitely fix that. I've added #968 to follow up on that.

**Comment by edugomez** [comment]
> there's a typo of 'objecs' that should be 'objects'.

Now amended.
