### ISSUE TITLE
Move to continuous deployment for OCDS Validator

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#948]

**Comment by robredpath** [comment]
- Automate David's semi-manual tests
- Translation will present some challenges

We understand what's required for this. Well, @Bjwebb does.

**Comment by Bjwebb** [comment]
The pull request at https://github.com/OpenDataServices/cove/pull/957 automates David's semi-manual tests, and tests that translations have been completed.

This removes the bulk of the work needed to make a release. Making a live deploy is now three steps:

1. Do the actual deploy. From the [opendataservices-deploy directory](https://github.com/OpenDataServices/opendataservices-deploy):

```
salt-ssh --state-output=mixed -L 'cove-live-ocds-2' state.highstate
```
2. Check that the latest commit is shown in the footer of http://standard.open-contracting.org/validator/

3. Test that the live site is working as expected. From the cove directory:

```
CUSTOM_SERVER_URL=http://standard.open-contracting.org/ DJANGO_SETTINGS_MODULE=cove_ocds.settings py.test cove_ocds/tests_functional.py -n 4
```

These take <5mins of my time, and are tricky to automate without giving Travis access to our live server.

**Comment by Bjwebb** [comment]
TODO:

- [ ] Add new steps to docs
- [ ] Add description of when it's okay deploy (ie. tests pass)
- [ ] Add rules for updating Transifex (maybe add an integration translation branch)

**Comment by Bjwebb** [comment]
Pull request for docs changes: https://github.com/OpenDataServices/cove/pull/966

**Comment by robredpath** [comment]
@Bjwebb can we close this?
