### ISSUE TITLE
Translations are very incomplete

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#95]
We may want to use online machine translation for these again, and possibly remove some of the translations we don't want to maintain for the immediate future.

We may also want different translations for different front-ends (ie OCDS vs. 360).

**Comment by caprenter** [comment]
Until we have a proper translation process, this always going to be the case.

My suggestion is that once we start to get into some sort of release cycle, then we can update google translations as part of that deployment

**Comment by Bjwebb** [comment]
For replacing the OCDS validator, we want only Spanish. We can redo the google translate and ask Georg to check.

**Comment by stevieflow** [comment]
Observation: this translation only seems to work on the words/terms associated with the data input (upload/paste/link) - whereas on a typical page there are lots of English words (eg: text about how long the data is kept - pushing these to a new page might be one solution: https://github.com/OpenDataServices/cove/issues/223)

We should evaluate where and what for we need translation.

**Comment by caprenter** [comment]
It's also worth noting that the README in this repo contains information about how to do translations and our current approach to it:
https://github.com/OpenDataServices/cove#translations

**Comment by Bjwebb** [comment]
The reason why words with data input were translated is just that they've been around longer.

We now have a complete Spanish machine translation. We're going to be moving to a monthly release process, and re-doing the machine translations will be party of this.
