### ISSUE TITLE
Start to unify OCDS Validator & Standard Docs links & look&feel

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#952]
It's a bit jarring going between the OCDS standard docs and the validator, even though they're quite tightly linked. 

Applying the same theme verbatim probably isn't worth the effort at this stage, but an iteration to move us towards a unified set of links would be good. 

Prep required is to review the current state of both tools and decide on changes to be made.

**Comment by edugomez** [comment]
Some visualisation on this issue:

### OCDS Docs
![ocds_docs](https://user-images.githubusercontent.com/5618508/35521300-499a4aa4-0511-11e8-9ca3-20e3cbad408d.png)

### OCDS Validator Home
![ocds_validator](https://user-images.githubusercontent.com/5618508/35521332-607c6a72-0511-11e8-9932-772a2adc7f5e.png)

### OCDS Validator Results
![ocds_validator_result](https://user-images.githubusercontent.com/5618508/35521405-8d48c7a8-0511-11e8-928d-9342034cea00.png)

**Comment by edugomez** [comment]
One thing missing in the docs and the validator is the tab favicon:

![favicon_ocds](https://user-images.githubusercontent.com/5618508/35525317-0fee1ffa-051c-11e8-9d9b-607e6e1a08d1.png)

![missing_favicon_ocds](https://user-images.githubusercontent.com/5618508/35525327-16ccd794-051c-11e8-9b15-ebcd56390f55.png)

**Comment by robredpath** [comment]
Favicons are important!

Also - the font is different between the two pages. 

But, now that I'm looking into this in more detail, the most jarring thing is that the massive block of black moves around, which isn't really up for changing here. 

@timgdavies , I think you had some thoughts on this relating to links?

**Comment by edugomez** [comment]
> Favicons are important 
Agree, that little page icon with the top right corner folded is a bit sloppy.

**Comment by timgdavies** [comment]
I think this is more about updates to the **documentation theme** - so I would suggest we leave this low priority right now.

**Comment by robredpath** [comment]
Thanks, @timgdavies . We'll drop this from the Validator sprint then, and can examine documentation theme updates in due course.

**Comment by robredpath** [comment]
The work here is just the font and the favicon, then it's Done.

**Comment by robredpath** [comment]
To be clear, by "the font" I mean making the font-family for the 'normal' text of the validator match that of the standard docs - ie, `font-family: "Lato", "proxima-nova"...`

**Comment by jpmckinney** [comment]
I see the same favicon and the same font (Lato) so this can be closed.
