### ISSUE TITLE
Date issue in IATI cove is back

### ISSUE THREAD

**Issue by rory09** [OpenDataServices/cove#954]
In some specific circumstances, cove is reading dates that are formatted as dates as integers, causing a schema validation error for IATI

Please see this file - it's a copy of the one she used and will give the errors concerned: https://opendataservices.plan.io/attachments/15782 (unpublished data so only accessible to our team)

@Bjwebb  has done some preliminary digging and found that an update of openpyxl will fix this error, but that this will need corresponding updates to the rest of the codebase.

This is quite urgent.

**Comment by Bjwebb** [comment]
Here's a dev deploy with a fix: http://954-update-openpyxl.dev.cove.opendataservices.coop/

**Comment by Bjwebb** [comment]
I'm looking into making this fix live soon, but first want to check there's no regressions.

@rory09 Have you had chance to test using the dev link above? Could you double check that your template with a lot of comments etc. in still converts as expected?

**Comment by rory09** [comment]
Hi @Bjwebb - sorry for the delay. I just tested it with a download of [this file](https://docs.google.com/spreadsheets/d/1EhsYU-ExwVSc3t7Hmib1H86r_5cLsIj1a1drztahHxE/edit#gid=981153564), changed some dates to different formats before and after downloading as a .xlsx file, and the conversion behaved as expected. (Save from the error messages highlighted in #940.

Thanks for a speedy resolution - I'm happy for this to go live asap.

**Comment by robredpath** [comment]
@Bjwebb can we close this now?

**Comment by Bjwebb** [comment]
Yep. Change is on http://iati.cove.opendataservices.coop/
