### ISSUE TITLE
Add explanation of Additional Fields box to OCDS Validator

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#962]
This is a requirement of a short bit of text in the interface to: 
- Explain what additional fields are
- Encourage the user to look for potential typos from OCDS fields
- Encourage the user to look for mappings to OCDS fields

**Comment by jpmckinney** [comment]
I see:

> This data includes the following fields which are not part of the OCDS schema. You should check whether the data in these fields could be provided by using a field in the OCDS schema or by using an existing extension to the schema.

I think this issue can be closed?
