### ISSUE TITLE
panel-warning in OCDS is green, not yellow

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#968]
See #947 . We'd like to be able to display warnings, but they come out green, so we resort to errors.

**Comment by jpmckinney** [comment]
If fixing colors, may want to also fix #846

**Comment by rhiaro** [comment]
Commented out the bit of custom OCDS CSS that overrides bootstrap, so `panel-warning` now looks like this:

![screenshot at 2018-10-17 17-58-53](https://user-images.githubusercontent.com/466229/47095843-abf7a280-d236-11e8-9e8d-db8ffb70e4f5.png)
