### ISSUE TITLE
IATI version 2.03 is live

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#979]
How soon can we use 2.03 in IATI CoVE?

https://www.aidtransparency.net/news/iati-upgrade-to-version-2-03-goes-live

**Comment by Bjwebb** [comment]
Switching from 2.02 to 2.03 would be fairly straightforward to do this week. All files would be validated against 2.03, because we don't do any version detection yet.

**Comment by stevieflow** [comment]
ok thanks @Bjwebb 

I guess we would also need to generate a new all-headers file?

And - @rory09 reflect any updates in the template(s)?

**Comment by rory09** [comment]
Here's an updated template including the use of the `tag` element and declaring the version as 2.03: https://docs.google.com/spreadsheets/d/1sPrss-bMgU2LiM1tsOgensnh2yJKPXKc1S8VrhQe0eY/edit#gid=448577087  

@stevieflow if we want to have a more humanitarian focused one we could do that as well.

**Comment by Bjwebb** [comment]
I have a deploy with the 2.03 schema: http://979-203.dev.cove.opendataservices.coop/

Still need to update the openag rulesets for 2.03.

**Comment by Bjwebb** [comment]
This is now ready, just needs reviewing. https://github.com/OpenDataServices/cove/pull/985

**Comment by Bjwebb** [comment]
This is live now on http://iati.cove.opendataservices.coop/
