### ISSUE TITLE
Add 'how-to' guide to IATI CoVE

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#981]
Basic 'how to use' info probably isn't that useful. 

Need input from @stevieflow and @rory09 on what kind of thing they want to appear where in the user flow.

**Comment by stevieflow** [comment]
What's the best way to do that?

**Comment by robredpath** [comment]
> What's the best way to do that?

If you've got clear ideas of what you want IATI CoVE to look like, then probably an annotated screenshot with suggested text

If it's something that you'd prefer to explore a bit, then I'd suggest that we try and get together (ideally with @rory09 as well) next week and work through it together.

**Comment by rory09** [comment]
I've started a doc for this and other related issues [here](https://docs.google.com/document/d/1-QKxzXQaHDzBI8W3FsIG83Cp-GkJ8F1a46P2OuSRWDk/edit).
