### ISSUE TITLE
Add link to test sample data in IATI CoVE

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#982]
@rory09 @stevieflow do you have data that we can make an OCDS-style 'click here to load sample data' link with?

**Comment by stevieflow** [comment]
Yes - internal ticket 13284 is all about that --> @rory09

**Comment by rory09** [comment]
I've started a doc for this and other related issues [here](https://docs.google.com/document/d/1-QKxzXQaHDzBI8W3FsIG83Cp-GkJ8F1a46P2OuSRWDk/edit).

**Comment by BibianaC** [comment]
Done
