### ISSUE TITLE
Pivot tables break IATI CoVE, even if commented out.

### ISSUE THREAD

**Issue by rory09** [OpenDataServices/cove#990]
See [this file](https://opendataservices.plan.io/attachments/16911).

I believe this is down the the newer version of openpyxl. Is there any scope to fix this? It's making it really hard to include some of the newer features of cove to more advance spreadsheets, because deleting pivots can break dependencies (where a pivot of all the transactions drives the participating orgs, for example).

**Comment by Bjwebb** [comment]
So apparently this is a LibreOffice bug - https://bitbucket.org/openpyxl/openpyxl/issues/981/can-not-open-file-due-to-typeerror

Could you try upgrading LibreOffice, to see if that helps?

**Comment by Bjwebb** [comment]
That file works for me. I thought this might be due to openpyxl 2.5.1, but it works with 2.5.0 also. Closing, but suspect this will get reopened when it break again
