### ISSUE TITLE
What should “IATI Schema” link to?

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/cove#998]
Just here:
https://github.com/OpenDataServices/cove/blob/9072e97265142c6167f56d917b3cff2bbc6887b6/cove_iati/templates/cove_iati/explore.html#L112

I guess it should at least state the version (currently v2.02) and perhaps link to http://iatistandard.org/202/schema/ or something.

Also, why isn’t “IATI Schema” translated?

**Comment by Bjwebb** [comment]
Thanks. Yes, I think this is right, and we're now 2.03.
